INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', '24 DE MAYO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'AGUARICO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'ALAUSI');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'ALFREDO BAQUERIZO MORENO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'AMBATO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'ANTONIO ANTE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'ARAJUNO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'ARCHIDONA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'ARENILLAS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'ATACAMES');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'ATAHUALPA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'AZOGUES');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'BABA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'BABAHOYO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'BALAO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'BALSAS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'BALZAR');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'BAÑOS DE AGUA SANTA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'BIBLIAN');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'BOLIVAR');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'BUENA FE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'CALUMA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'CALVAS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'CAMILO PONCE ENRIQUEZ');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'CARLOS JULIO AROSEMENA TOLA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'CASCALES');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'CATAMAYO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'CAYAMBE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'CAÑAR');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'CELICA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'CENTINELA DEL CONDOR');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'CEVALLOS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'CHAGUARPAMBA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'CHAMBO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'CHILLA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'CHILLANES');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'CHIMBO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'CHINCHIPE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'CHONE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'CHORDELEG');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'CHUNCHI');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'COLIMES');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'COLTA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'COTACACHI');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'CRNEL. MARCELINO MARIDUEÐA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'CRNEL. MARCELINO MARIDUEÑA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'CUENCA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'CUMANDA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'CUYABENO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'DAULE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'DELEG');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'DMG');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'DMQ');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'DURAN');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'ECHEANDIA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'EL CARMEN');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'EL CHACO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'EL GUABO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'EL PAN');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'EL PANGUI');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'EL PIEDRERO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'EL TAMBO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'EL TRIUNFO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'ELOY ALFARO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'EMPALME');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'ESMERALDAS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'ESPEJO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'ESPINDOLA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'FLAVIO ALFARO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'GIRON');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'GNRAL. ANTONIO ELIZALDE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'GONZALO PIZARRO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'GONZANAMA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'GUACHAPALA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'GUALACEO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'GUALAQUIZA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'GUAMOTE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'GUANO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'GUARANDA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'GUAYAQUIL');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'HUAMBOYA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'HUAQUILLAS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'IBARRA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'ISABELA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'ISIDRO AYORA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'JAMA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'JARAMIJO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'JIPIJAPA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'JUNIN');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'LA CONCORDIA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'LA JOYA DE LOS SACHAS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'LA LIBERTAD');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'LA MANA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'LA TRONCAL');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'LAGO AGRIO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'LAS GOLONDRINAS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'LAS LAJAS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'LAS NAVES');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'LATACUNGA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'LIMON INDANZA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'LOGROÐO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'LOGROÑO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'LOJA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'LOMAS DE SARGENTILLO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'LORETO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'MACARA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'MACHALA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'MANGA DEL CURA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'MANTA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'MAR TERRITORIAL');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'MARCABELI');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'MEJIA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'MERA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'MILAGRO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'MIRA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'MOCACHE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'MOCHA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'MONTALVO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'MONTECRISTI');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'MONTUFAR');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'MORONA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'MUISNE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'NABON');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'NANGARITZA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'NARANJAL');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'NARANJITO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'NOBOL');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'OLMEDO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'ORELLANA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'OTAVALO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'OÑA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PABLO SEXTO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PAJAN');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PALANDA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PALENQUE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PALESTINA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PALLATANGA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PALORA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PALTAS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PANGUA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PAQUISHA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PASAJE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PASTAZA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PATATE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PAUTE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PEDERNALES');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PEDRO CARBO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PEDRO MONCAYO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PEDRO VICENTE MALDONADO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PENIPE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PICHINCHA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PIMAMPIRO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PINDAL');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PIÑAS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PLAYAS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PORTOVELO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PORTOVIEJO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PUCARA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PUEBLO VIEJO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PUEBLOVIEJO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PUERTO FRANCISCO DE ORELLANA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PUERTO LOPEZ');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PUERTO QUITO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PUJILI');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PUTUMAYO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'PUYANGO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'QUERO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'QUEVEDO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'QUIJOS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'QUILANGA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'QUININDE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'QUINSALOMA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'QUITO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'RIOBAMBA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'RIOVERDE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'ROCAFUERTE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'RUMIÑAHUI');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SALCEDO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SALINAS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SALITRE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SAMBORONDON');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SAN CRISTOBAL');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SAN FERNANDO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SAN JACINTO DE YAGUACHI');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SAN JUAN BOSCO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SAN LORENZO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SAN MIGUEL');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SAN MIGUEL DE  BOLIVAR');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SAN MIGUEL DE LOS BANCOS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SAN MIGUEL DE SALCEDO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SAN MIGUEL DE URCUQUI');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SAN PEDRO DE HUACA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SAN PEDRO DE PELILEO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SAN VICENTE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SANTA ANA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SANTA CLARA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SANTA CRUZ');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SANTA ELENA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SANTA ISABEL');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SANTA LUCIA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SANTA ROSA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SANTIAGO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SANTIAGO DE PILLARO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SANTO DOMINGO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SAQUISILI');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SARAGURO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SEVILLA DE ORO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SHUSHUFINDI');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SIGCHOS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SIGSIG');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SIMON BOLIVAR');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SOZORANGA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SUCRE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SUCUA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SUCUMBIOS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'SUSCAL');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'TAISHA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'TENA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'TISALEO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'TIWINTZA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'TOSAGUA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'TULCAN');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'URDANETA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'VALENCIA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'VENTANAS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'VINCES');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'YACUAMBI');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'YANTZAZA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'ZAMORA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'ZAPOTILLO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, 'null', 'ZARUMA');
