INSERT INTO canton(id, codigo, nombre) VALUES(0, '0', 'MAR TERRITORIAL');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1001', 'IBARRA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1002', 'ANTONIO ANTE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1003', 'COTACACHI');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1004', 'OTAVALO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1005', 'PIMAMPIRO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1006', 'SAN MIGUEL DE URCUQUI');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '101', 'CUENCA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '102', 'GIRON');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '103', 'GUALACEO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '104', 'NABON');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '105', 'PAUTE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '106', 'PUCARA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '107', 'SAN FERNANDO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '108', 'SANTA ISABEL');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '109', 'SIGSIG');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '110', 'OÑA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1101', 'LOJA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1102', 'CALVAS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1103', 'CATAMAYO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1104', 'CELICA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1105', 'CHAGUARPAMBA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1106', 'ESPINDOLA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1107', 'GONZANAMA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1108', 'MACARA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1109', 'PALTAS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '111', 'CHORDELEG');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1110', 'PUYANGO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1111', 'SARAGURO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1112', 'SOZORANGA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1113', 'ZAPOTILLO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1114', 'PINDAL');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1115', 'QUILANGA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1116', 'OLMEDO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '112', 'EL PAN');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '113', 'SEVILLA DE ORO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '114', 'GUACHAPALA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '115', 'CAMILO PONCE ENRIQUEZ');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1201', 'BABAHOYO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1202', 'BABA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1203', 'MONTALVO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1204', 'PUEBLOVIEJO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1205', 'QUEVEDO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1206', 'URDANETA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1207', 'VENTANAS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1208', 'VINCES');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1209', 'PALENQUE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1210', 'BUENA FE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1211', 'VALENCIA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1212', 'MOCACHE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1213', 'QUINSALOMA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1301', 'PORTOVIEJO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1302', 'BOLIVAR');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1303', 'CHONE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1304', 'EL CARMEN');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1305', 'FLAVIO ALFARO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1306', 'JIPIJAPA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1307', 'JUNIN');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1308', 'MANTA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1309', 'MONTECRISTI');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1310', 'PAJAN');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1311', 'PICHINCHA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1312', 'ROCAFUERTE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1313', 'SANTA ANA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1314', 'SUCRE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1315', 'TOSAGUA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1316', '24 DE MAYO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1317', 'PEDERNALES');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1318', 'OLMEDO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1319', 'PUERTO LOPEZ');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1320', 'JAMA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1321', 'JARAMIJO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1322', 'SAN VICENTE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1401', 'MORONA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1402', 'GUALAQUIZA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1403', 'LIMON INDANZA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1404', 'PALORA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1405', 'SANTIAGO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1406', 'SUCUA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1407', 'HUAMBOYA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1408', 'SAN JUAN BOSCO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1409', 'TAISHA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1410', 'LOGROÑO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1411', 'PABLO SEXTO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1412', 'TIWINTZA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1501', 'TENA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1503', 'ARCHIDONA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1504', 'EL CHACO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1507', 'QUIJOS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1509', 'CARLOS JULIO AROSEMENA TOLA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1601', 'PASTAZA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1602', 'MERA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1603', 'SANTA CLARA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1604', 'ARAJUNO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1701', 'QUITO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1702', 'CAYAMBE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1703', 'MEJIA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1704', 'PEDRO MONCAYO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1705', 'RUMIÑAHUI');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1707', 'SAN MIGUEL DE LOS BANCOS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1708', 'PEDRO VICENTE MALDONADO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1709', 'PUERTO QUITO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1801', 'AMBATO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1802', 'BAÑOS DE AGUA SANTA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1803', 'CEVALLOS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1804', 'MOCHA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1805', 'PATATE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1806', 'QUERO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1807', 'SAN PEDRO DE PELILEO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1808', 'SANTIAGO DE PILLARO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1809', 'TISALEO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1901', 'ZAMORA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1902', 'CHINCHIPE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1903', 'NANGARITZA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1904', 'YACUAMBI');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1905', 'YANTZAZA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1906', 'EL PANGUI');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1907', 'CENTINELA DEL CONDOR');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1908', 'PALANDA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '1909', 'PAQUISHA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '2001', 'SAN CRISTOBAL');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '2002', 'ISABELA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '2003', 'SANTA CRUZ');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '201', 'GUARANDA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '202', 'CHILLANES');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '203', 'CHIMBO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '204', 'ECHEANDIA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '205', 'SAN MIGUEL');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '206', 'CALUMA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '207', 'LAS NAVES');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '2101', 'LAGO AGRIO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '2102', 'GONZALO PIZARRO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '2103', 'PUTUMAYO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '2104', 'SHUSHUFINDI');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '2105', 'SUCUMBIOS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '2106', 'CASCALES');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '2107', 'CUYABENO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '2201', 'ORELLANA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '2202', 'AGUARICO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '2203', 'LA JOYA DE LOS SACHAS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '2204', 'LORETO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '2301', 'SANTO DOMINGO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '2401', 'SANTA ELENA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '2402', 'LA LIBERTAD');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '2403', 'SALINAS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '301', 'AZOGUES');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '302', 'BIBLIAN');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '303', 'CAÑAR');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '304', 'LA TRONCAL');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '305', 'EL TAMBO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '306', 'DELEG');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '307', 'SUSCAL');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '401', 'TULCAN');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '402', 'BOLIVAR');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '403', 'ESPEJO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '404', 'MIRA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '405', 'MONTUFAR');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '406', 'SAN PEDRO DE HUACA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '501', 'LATACUNGA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '502', 'LA MANA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '503', 'PANGUA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '504', 'PUJILI');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '505', 'SALCEDO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '506', 'SAQUISILI');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '507', 'SIGCHOS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '601', 'RIOBAMBA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '602', 'ALAUSI');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '603', 'COLTA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '604', 'CHAMBO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '605', 'CHUNCHI');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '606', 'GUAMOTE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '607', 'GUANO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '608', 'PALLATANGA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '609', 'PENIPE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '610', 'CUMANDA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '701', 'MACHALA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '702', 'ARENILLAS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '703', 'ATAHUALPA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '704', 'BALSAS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '705', 'CHILLA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '706', 'EL GUABO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '707', 'HUAQUILLAS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '708', 'MARCABELI');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '709', 'PASAJE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '710', 'PIÑAS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '711', 'PORTOVELO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '712', 'SANTA ROSA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '713', 'ZARUMA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '714', 'LAS LAJAS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '801', 'ESMERALDAS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '802', 'ELOY ALFARO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '803', 'MUISNE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '804', 'QUININDE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '805', 'SAN LORENZO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '806', 'ATACAMES');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '807', 'RIOVERDE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '808', 'LA CONCORDIA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '9004', 'EL PIEDRERO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '901', 'GUAYAQUIL');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '902', 'ALFREDO BAQUERIZO MORENO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '903', 'BALAO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '904', 'BALZAR');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '905', 'COLIMES');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '906', 'DAULE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '907', 'DURAN');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '908', 'EMPALME');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '909', 'EL TRIUNFO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '910', 'MILAGRO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '911', 'NARANJAL');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '912', 'NARANJITO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '913', 'PALESTINA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '914', 'PEDRO CARBO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '916', 'SAMBORONDON');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '918', 'SANTA LUCIA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '919', 'SALITRE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '920', 'SAN JACINTO DE YAGUACHI');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '921', 'PLAYAS');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '922', 'SIMON BOLIVAR');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '923', 'CRNEL. MARCELINO MARIDUEÑA');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '924', 'LOMAS DE SARGENTILLO');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '925', 'NOBOL');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '927', 'GNRAL. ANTONIO ELIZALDE');
INSERT INTO canton(id, codigo, nombre) VALUES(0, '928', 'ISIDRO AYORA');
