INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('0', 'MAR TERRITORIAL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('000C01', 'EL PIEDRERO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D01C01', 'CAÑARIBAMBA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D01C02', 'SAN BLAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D01C03', 'BELLAVISTA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D01C04', 'VERDE LOMA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D01C05', 'EL VECINO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D01C06', 'BARRIAL BLANCO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D01C07', 'EL SAGRARIO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D01C08', 'HERMANO MIGUEL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D01C09', 'MACHANGARA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D01C10', 'QUINTA CHICA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D01C11', 'TERMINAL TERRESTRE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D01C12', 'TOTORACOCHA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D01C13', 'GIL RAMIREZ DAVALOS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D01C14', 'SAYAUSI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D01C15', 'SAN JOAQUIN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D01C16', 'PACCHA Y NULTI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D01C17', 'RICAURTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D01C18', 'CHECA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D01C19', 'OCTAVIO CORDERO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D01C20', 'SININCAY');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D02C01', 'YANUNCAY');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D02C02', 'EL SALADO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D02C03', 'NARANCAY');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D02C04', 'SUCRE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D02C05', 'MONAY');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D02C06', 'HUAYNA CAPAC');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D02C07', 'EL BATAN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D02C08', 'SAN SEBASTIAN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D02C09', 'CAYAMBE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D02C10', 'MOLLETURO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D02C12', 'BAÑOS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D02C13', 'TARQUI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D02C14', 'TURI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D02C15', 'CUMBE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D02C16', 'QUINGEO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D02C17', 'SANTA ANA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D02C18', 'EL VALLE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D02C19', 'COCHAPAMBA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D03C01', 'GIRON');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D03C02', 'SAN RAFAEL SHARUG');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D03C03', 'PUCARA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D03C04', 'CERRO NEGRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D03C05', 'SAN FERNANDO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D03C06', 'LA UNION');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D04C01', 'SAN JUAN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D04C02', 'JADAN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D04C03', 'ZHIMAD');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D04C04', 'GUALACEO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D04C05', 'GUALACEO SUR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D04C06', 'REMIGIO CRESPO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D04C07', 'CHORDELEG');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D05C01', 'NABON');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D05C02', 'LAS NIEVES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D05C03', 'OÑA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D06C01', 'DUG DUG');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D06C02', 'PAUTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D06C03', 'EL PAN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D06C04', 'AMALUZA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D06C05', 'SEVILLA DE ORO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D06C06', 'GUACHAPALA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D07C01', 'SHUMIRAL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D07C02', 'CAMILO PONCE ENRIQUEZ');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D07C03', 'CARMEN DE PIJILI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D08C01', 'SIGSIG');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D08C02', 'JIMA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('01D08C03', 'LUDO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('02D01C01', 'GUARANDA SUR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('02D01C02', '15 DE MAYO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('02D01C03', 'GUANUJO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('02D01C04', '1 DE MAYO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('02D01C05', 'QUINDIGUA BAJO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('02D01C06', 'PALMA LOMA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('02D01C07', 'SIMIATUG');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('02D01C08', 'FACUNDO VELA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('02D01C09', 'SALINAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('02D01C10', 'SAN LUIS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('02D01C11', 'SAN LORENZO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('02D02C01', 'SAN JOSE DEL TAMBO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('02D02C02', 'CHILLANES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('02D03C01', 'TELIMBELA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('02D03C02', 'MAGDALENA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('02D03C03', 'CHIMBO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('02D03C04', 'SAN MIGUEL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('02D03C05', 'SAN PABLO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('02D03C06', 'SANTIAGO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('02D03C07', 'BALSAPAMBA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('02D04C01', 'ECHEANDIA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('02D04C02', 'CALUMA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('02D04C03', 'LAS NAVES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('03D01C01', 'AZOGUES ORIENTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('03D01C02', 'AZOGUES NORTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('03D01C03', 'UCHUPUCUM');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('03D01C04', 'AZOGUES SUR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('03D01C05', 'GUAPAN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('03D01C06', 'AZOGUES OESTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('03D01C07', 'SAN MIGUEL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('03D01C08', 'LUIS CORDERO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('03D01C09', 'BIBLIAN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('03D01C10', 'JERUSALEN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('03D01C11', 'NAZON');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('03D01C12', 'DELEG');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('03D02C01', 'CAÑAR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('03D02C02', 'CAÑAR OCCIDENTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('03D02C03', 'GUALLETURO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('03D02C04', 'INGAPIRCA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('03D02C05', 'ZHUD');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('03D02C06', 'EL TAMBO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('03D02C07', 'SUSCAL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('03D03C01', 'TRONCAL NORTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('03D03C02', 'TRONCAL CENTRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('03D03C03', 'TRONCAL OESTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('04D01C01', 'SAN PEDRO DE HUACA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('04D01C02', 'OLIMPICO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('04D01C03', 'COMUNEROS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('04D01C04', 'ISIDRO AYORA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('04D01C05', 'EL PORTAL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('04D01C06', 'PARQUE DEL 8');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('04D01C07', 'EL MAESTRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('04D01C08', 'KENNEDY');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('04D01C09', 'SANTA MARTHA DE CUBA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('04D01C10', 'JULIO ANDRADE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('04D01C11', 'TUFIÑO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('04D01C12', 'CHICAL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('04D01C13', 'URBINA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('04D02C01', 'BOLIVAR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('04D02C02', 'SAN RAFAEL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('04D02C03', 'GARCIA MORENO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('04D02C04', 'SAN GABRIEL NORTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('04D02C05', 'SAN GARBRIEL SUR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('04D02C06', 'CRISTOBAL COLON');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('04D02C07', 'LA PAZ');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('04D03C01', 'EL ANGEL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('04D03C02', 'EL GOALTAL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('04D03C03', 'LA CONCEPCION');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('04D03C04', 'MIRA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D01C01', 'TOACAZO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D01C02', 'MULALO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D01C03', 'LASSO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D01C04', 'JOSEGUANGO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D01C05', 'POALO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D01C06', 'SAN JOSE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D01C07', 'ELOY ALFARO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D01C08', 'BETHLEMITAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D01C09', 'SAN CARLOS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D01C10', 'SAN MARTIN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D01C11', 'LA COCHA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D01C12', 'LA CALERA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D01C13', 'CHOFER');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D01C14', 'TERMINAL TERRESTRE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D01C15', 'NUEVA VIDA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D01C16', 'BELISARIO QUEVEDO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D01C17', 'PASTO CALLE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D01C18', 'GUAYTACAMA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D02C01', 'GUASAGANDA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D02C02', 'LA MANA NORTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D02C03', 'LA MANA SUR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D03C01', 'MORASPUNGO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D03C02', 'PILLONPATA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D03C03', 'EL CORAZON');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D04C01', 'SAQUISILI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D04C02', 'CANCHAGUA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D04C03', 'LA ESPERANZA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D04C04', 'ANGAMARCA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D04C05', 'PILALO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D04C06', 'ZUMBAGUA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D04C07', 'GUANGAJE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D04C08', 'ALPAMALA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D04C09', 'PUJILI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D04C10', 'LA MERCED');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D04C11', 'LA VICTORIA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D05C01', 'SIGCHOS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D05C02', 'LAS PAMPAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D05C03', 'CHUGCHILLAN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D05C04', 'ISINLIVI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D06C01', 'CUSUBAMBA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D06C02', 'SALCEDO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D06C03', 'MULALILLO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('05D06C04', 'SANTA ANA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D01C01', 'YARUQUIES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D01C02', 'POLITECNICA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D01C03', 'SHOPPING');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D01C04', 'CAMILO PONCE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D01C05', 'CAMINOS AL SOL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D01C06', 'LA ESTACION');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D01C07', 'SAN ALFONSO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D01C08', 'PUCARA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D01C09', 'LA PAZ');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D01C10', 'TERMINAL TERRESTRE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D01C11', 'LA CONDAMINE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D01C12', 'LA PRIMAVERA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D01C13', 'SANTA CRUZ');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D01C14', 'CALPI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D01C15', '24 DE MAYO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D01C16', 'QUIMIAG');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D01C17', 'LICTO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D01C18', 'PUNIN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D01C19', 'SAN LUIS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D01C20', 'CHAMBO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D02C01', 'HUIGRA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D02C02', 'ALAUSI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D02C03', 'GUASUNTOS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D02C04', 'TIXAN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D02C05', 'ACHUPALLAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D02C06', 'CHUNCHI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D02C07', 'JOYAGSHI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D03C01', 'CUMANDA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D03C02', 'PALLATANGA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D04C01', 'CAJABAMBA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D04C02', 'LIRIO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D04C03', 'COLUMBE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D04C04', 'PANGOR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D04C05', 'SANTIAGO DE QUITO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D04C06', 'GUAMOTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D04C07', 'COCHAPAMBA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D04C08', 'TIO CAJAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D04C09', 'PALMIRA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D04C10', 'CEBADAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D05C01', 'SAN ANDRES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D05C02', 'GUANO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D05C03', 'SANTA FE DE GALAN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('06D05C04', 'PENIPE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D01C01', 'CHILLA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D01C02', 'LA IBERIA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D01C03', 'PRIVILEGIO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D01C04', 'BAJO ALTO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D01C05', 'BARBONES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D01C06', 'RIO BONITO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D01C07', 'BUENA VISTA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D01C08', 'VELASCO IBARRA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D01C09', 'LAS PRADERAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D01C10', 'OCHOA LEON');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D01C11', 'BANANERA SUR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D01C12', 'BANANERA NORTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D01C13', 'PROGRESO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D01C14', 'CASACAY');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D01C15', 'UZCURRUMI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D02C01', '9 DE MAYO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D02C02', 'NUEVO PILO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D02C03', 'LA CUATRO MIL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D02C04', 'RAYITO DE LUZ');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D02C05', 'MACHALA OCCIDENTAL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D02C06', 'GRAL SERRANO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D02C07', '27 DE FEBRERO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D02C08', '19 DE NOVIEMBRE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D02C09', 'JAMBELI CENTRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D02C10', 'LA PROVIDENCIA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D02C11', 'ROCAFUERTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D02C12', 'EL CAMBIO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D02C13', 'PAEZ');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D02C14', 'LAS KATYAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D02C15', 'LA FERROVIARIA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D02C16', 'CRISTO DEL CONSUELO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D02C17', 'PUERTO BOLIVAR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D02C18', 'WILSON FRANCO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D02C19', 'SIMON BOLIVAR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D02C20', 'PARQUE LINEAL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D02C21', 'EL RETIRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D03C01', 'PACHA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D03C02', 'CERRO AZUL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D03C03', 'MORALES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D03C04', 'SALATI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D03C05', 'PORTOVELO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D03C06', 'GUANAZAN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D03C07', 'GUIZHAGUIÑA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D03C08', 'ZARUMA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D03C09', 'ARCAPAMBA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D04C01', 'BALSAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D04C02', 'MARCABELI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D04C03', 'MOROMORO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D04C04', 'SAN ROQUE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D04C05', 'SARACAY');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D04C06', 'CAPIRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D05C01', 'LA LIBERTAD');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D05C02', 'ARENILLAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D05C03', 'PALMALES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D05C04', 'GUABILLO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D05C05', 'UNION LOJANA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D05C06', 'HUALTACO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D05C07', 'MILTON REYES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D05C08', 'LA VICTORIA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D06C01', 'TORATA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D06C02', 'BELLA MARIA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D06C03', 'VEGA RIVERA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D06C04', 'SANTA ROSA ESTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D06C05', 'SANTA ROSA OESTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D06C06', 'LAS PALMERAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('07D06C07', 'JAMBELI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D01C01', 'CODESA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D01C02', 'LAS PALMAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D01C03', 'AIRE LIBRE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D01C04', 'LA TOLITA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D01C05', 'EL ARENAL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D01C06', 'BELLAVISTA NORTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D01C07', 'COLECTIVA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D01C08', 'VALLE HERMOSO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D01C09', 'CORDERO CRESPO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D01C10', 'ESMERALDAS LIBRE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D01C11', 'GUACHARACA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D01C12', 'SANTA MARTHA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D01C13', 'CENTRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D01C14', 'SANTA VAINAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D01C15', 'PROPICIA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D01C16', 'VUELTA LARGA NORTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D01C17', 'PUMPULA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D01C18', 'VUELTA LARGA SUR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D01C19', 'TABIAZO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D01C20', 'CAMARONES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D01C21', 'SAN MATEO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D02C01', 'LIMONES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D02C02', 'ANCHAYACU');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D02C03', 'BORBON');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D02C04', 'SELVA ALEGRE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D03C01', 'GALERAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D03C02', 'MUISNE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D03C03', 'CHAMANGA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D03C04', 'MOMPICHE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D03C05', 'ATACAMES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D03C06', 'TONSUPA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D03C07', 'LA UNION DE ATACAMES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D03C08', 'TONCHIGUE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D04C01', 'CUPA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D04C02', 'ROSA ZARATE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D04C03', 'QUININDE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D04C04', 'LA SEXTA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D04C05', 'PUEBLO NUEVO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D04C06', 'BOCANA DE BUA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D04C07', 'LA INDEPENDENCIA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D04C08', 'LA UNION');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D04C09', 'VICHE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D04C10', 'CUBE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D04C11', 'MALIMPIA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D05C01', 'FRONTERA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D05C02', 'URBINA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D05C03', 'TAMBILLO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D05C04', 'CARONDELET');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D06C01', 'PALESTINA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('08D06C02', 'MONTALVO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D01C01', 'GUASMO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D01C02', 'UNION DE BANANEROS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D01C03', 'FLORESTA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D01C04', '7 LAGOS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D01C05', 'CENTENARIO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D01C06', 'PUNA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D02C01', 'ESTEROS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D02C02', 'MALVINAS SUR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D02C03', 'MALVINAS NORTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D02C04', 'TRINITARIA NORTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D02C05', 'TRINITARIA SUR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D03C01', 'CHILE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D03C02', 'VICTORIA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D03C03', '9 DE OCTUBRE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D03C04', 'GARAY');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D03C05', 'VENEZUELA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D03C06', 'ANTEPARA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D03C07', 'CRISTO DEL CONSUELO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D04C01', 'CISNE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D04C02', 'CHALA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D04C03', 'SALINAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D04C04', 'PORTETE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D04C05', 'BATALLON DEL SUBURBIO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D04C06', 'SUBURBIO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D05C01', 'ATARAZANA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D05C02', 'SAUCES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D05C03', 'GUAYACANES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D05C04', 'ALBORADA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D05C05', 'URDESA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D05C06', 'KENNEDY');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D05C07', 'TENGUEL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D06C01', 'BELLAVISTA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D06C02', 'MARTHA DE ROLDOS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D06C03', 'SAMANES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D06C04', 'JUAN MONTALVO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D06C05', 'FLORIDA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D06C06', 'MAPASINGUE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D07C01', 'MONTE BELLO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D07C02', 'BASTION POPULAR SUR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D07C03', 'BASTION POPULAR NORTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D07C04', 'MUCHO LOTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D07C05', 'ORQUIDEAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D07C06', 'PASCUALES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D07C07', 'SAN FRANCISCO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D07C08', 'PUENTE LUCIA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D08C01', 'NUEVA PROSPERINA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D08C02', 'FORTIN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D08C03', 'PARAISO LA FLOR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D08C04', 'FLOR DE BASTION');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D08C05', 'MONTE SINAI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D08C06', 'NUEVO GUAYAQUIL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D09C01', 'LOS CEIBOS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D09C02', 'PUERTO HONDO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D09C03', 'CHONGON');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D10C01', 'MORRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D10C02', 'POSORJA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D10C03', 'PROGRESO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D11C01', 'JUJAN ESTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D11C02', 'JUJAN OESTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D11C03', 'SIMON BOLIVAR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D11C04', 'LORENZO DE GARAICOA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D12C01', 'SAN CARLOS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D12C02', 'BALAO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D12C03', 'NARANJAL CENTRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D12C04', 'NARANJAL SUR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D12C05', 'JAIME ROLDOS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D12C06', 'TAURA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D12C07', 'PUERTO INCA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D12C08', 'VILLA NUEVA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D13C01', 'BALZAR OESTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D13C02', 'LA GUAYAQUIL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D13C03', 'ROSA PAREDES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D13C04', 'BALZAR CENTRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D13C05', 'BALZAR SUR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D13C06', 'COLIMES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D13C07', 'COLIMES RURAL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D13C08', 'SAN JACINTO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D13C09', 'PALESTINA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D13C10', 'PALESTINA RURAL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D14C01', 'PEDRO CARBO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D14C02', 'ESTACADA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D14C03', 'SABANILLA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D14C04', 'VALLE DE LA VIRGEN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D14C05', 'LOMAS DE SARGENTILLO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D14C06', 'ISIDRO AYORA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D15C01', 'EL ROSARIO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D15C02', 'PUERTO DEL MONO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D15C03', 'CARLOS JULIO AROSEMENA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D15C04', 'EMPALME SUROESTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D15C05', 'EMPALME SURESTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D15C06', 'EMPALME CENTRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D16C01', 'EL TRIUNFO ESTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D16C02', 'EL TRIUNFO OESTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D16C03', 'EL TRIUNFO CENTRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D16C04', 'BUCAY');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D17C01', 'BELLAVISTA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D17C02', 'UNIVERSITARIO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D17C03', 'LAS PILAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D17C04', 'MAR NEGRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D17C05', 'CENTRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D17C06', 'VALDEZ');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D17C07', 'VISALTUR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D17C08', 'APOLO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D17C09', 'ALMEIDA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D17C10', 'SAN MIGUEL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D17C11', 'SAN PEDRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D17C12', 'LAS PIÑAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D17C13', 'CHOBO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D17C14', 'MARISCAL SUCRE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D17C15', 'ROBERTO ASTUDILLO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D18C01', 'NARANJITO ESTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D18C02', 'NARANJITO SUR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D18C03', 'NARANJITO CENTRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D18C04', 'MARCELINO MARIDUEÑA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D19C01', 'LA YOLITA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D19C02', 'JUAN BAUTISTA AGUIRRE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D19C03', 'DAULE CENTRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D19C04', 'LIMONAL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D19C05', 'LA T');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D19C06', 'LAS LOJAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D19C07', 'SANTA LUCIA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D19C08', 'CABUYAL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D19C09', 'PORVENIR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D19C10', 'NOBOL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D20C01', 'SALITRE NORTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D20C02', 'SALITRE SAUCES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D20C03', 'VERNAZA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D20C04', 'VICTORIA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D20C05', 'JUNQUILLAL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D21C01', 'YAGUACHI SUR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D21C02', 'YAGUACHI NORTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D21C03', 'BOLICHE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D21C04', 'VIRGEN DE FATIMA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D21C05', 'CONE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D22C01', 'PLAYAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D22C02', 'GENERAL VILLAMIL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D22C03', 'ENGABAO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D23C01', 'SAMBORONDON');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D23C02', 'TARIFA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D24C01', 'ABEL GILBERT');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D24C02', 'CENTRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D24C03', 'PANORAMA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D24C04', 'LA HERRADURA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D24C05', 'RECREO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D24C06', 'DIVINO NIÑO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D24C07', 'ARBOLITO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('09D24C08', 'LIGA CANTONAL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D01C01', 'ARCANGEL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D01C02', 'CARANQUIS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D01C03', 'LOS CEIBOS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D01C04', 'GUAYABILLAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D01C05', 'COMPLEJO DEPORTIVO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D01C06', 'LA FLORIDA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D01C07', 'AMAZONAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D01C08', 'LAS RIELES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D01C09', 'LAS LOMAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D01C10', 'ESTADIO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D01C11', 'AZAYA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D01C12', 'LAS TOTORAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D01C13', 'EL NOGAL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D01C14', 'AMBUQUI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D01C15', 'LA CAROLINA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D01C16', 'SALINAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D01C17', 'LITA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D01C18', 'GALO PLAZA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D01C19', 'PIMAMPIRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D01C20', 'LAS TERMAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D01C21', 'ARRAYANES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D01C22', 'BUENOS AIRES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D02C01', 'ANDRADE MARIN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D02C02', 'TEXTILERO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D02C03', 'SAN ROQUE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D02C04', 'LOS GUABOS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D02C05', 'EL JORDAN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D02C06', 'LOS LAGOS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D02C07', 'LA MONTAÑA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D02C08', 'SAN LUIS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D02C09', 'MOJANDA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D02C10', 'LA CASCADA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D02C11', 'GONZALEZ');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D02C12', 'SAN PABLO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D02C13', 'PUERTO LAGO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D02C15', 'QUICHINCHE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D02C16', 'SELVA ALEGRE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D03C01', 'COTACACHI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D03C02', 'QUIROGA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D03C03', 'INTAG');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D03C04', 'LAS TOLAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D03C05', 'IMANTAG');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D03C06', 'GARCIA MORENO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('10D03C06', 'LAS GOLONDRINAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D01C01', 'VILCABAMBA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D01C02', 'YANGANA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D01C03', 'MALACATOS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D01C04', 'TAQUIL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D01C05', 'ZAMORA HUAYCO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D01C06', 'ESTEBAN GODOY');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D01C07', 'EL PARAISO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D01C08', 'CELI ROMAN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D01C09', 'IV CENTENARIO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D01C10', 'TEBAIDA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D01C11', 'LOS MOLINOS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D01C12', 'CHONTACRUZ');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D01C13', 'SAGRARIO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D01C14', 'EL VALLE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D01C15', 'CLODOVEO JARAMILLO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D01C16', 'LA BANDA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D01C17', 'SAUCES NORTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D01C18', 'LA ARGELIA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D01C19', 'CONSACOLA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D01C20', 'SAN LUCAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D01C21', 'EL CISNE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D02C01', 'EL TAMBO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D02C02', 'CATAMAYO NORTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D02C03', 'CATAMAYO SAN JOSE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D02C04', 'GUAYQUICHUMA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D02C05', 'SAN PEDRO DE LA BENDITA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D02C06', 'CHAGUARPAMBA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D02C07', 'BUENAVISTA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D02C08', 'OLMEDO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D02C09', 'LA TINGUE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D03C01', 'CATACOCHA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D03C02', 'YAMANA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D03C03', 'LAURO GUERRERO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D03C04', 'GUACHANAMA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D03C05', 'ORIANGA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D04C01', 'SABANILLA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D04C02', 'CELICA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D04C03', 'EL ARENAL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D04C04', 'ALAMOR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D04C06', '12 DE DICIEMBRE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D04C07', 'PINDAL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D05C01', 'JIMBURA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D05C02', 'EL INGENIO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D05C03', 'AMALUZA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D06C01', 'COLAISACA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D06C02', 'CARIAMANGA ESTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D06C03', 'CARIAMANGA OESTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D06C04', 'SANGUILLIN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D06C05', 'LUCERO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D06C06', 'CHANGAIMINA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D06C07', 'GONZANAMA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D06C08', 'NAMBACOLA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D06C09', 'SAN ANTONIO DE LAS ARADAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D07C01', 'MACARA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D07C02', 'LA VICTORIA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D07C03', 'LA RAMA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D07C04', 'SOZORANGA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D07C05', 'TACAMOROS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D08C01', 'URDANETA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D08C02', 'SARAGURO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D08C03', 'SAN PABLO DE TENTA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D08C04', 'SELVA ALEGRE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D08C05', 'SUMAYPAMBA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D08C06', 'MANU');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D09C01', 'ZAPOTILLO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D09C02', 'PALETILLAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D09C03', 'CAZADEROS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D09C04', 'GARZAREAL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('11D09C05', 'LIMONES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D01C01', 'SAN JOSE DE JUJAN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D01C02', 'PUERTA NEGRA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D01C03', 'EL SALTO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D01C04', 'BARREIROS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D01C05', 'CENTRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D01C06', 'TERMINAL TERRESTRE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D01C07', 'SABANA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D01C08', 'UNIVERSIDAD');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D01C09', 'LA UNION');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D01C10', 'POSA DE MATE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D01C11', 'PIMOCHA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D01C12', 'MATA DE CACAO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D01C13', 'CARACOL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D01C14', 'MANTUANO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D01C15', 'BABA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D01C16', 'ISLA DE BEJUCAL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D01C17', 'GUARE DE BABA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D01C18', 'MONTALVO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D01C19', 'LA ESMERALDA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D02C01', 'PUEBLO VIEJO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D02C02', 'SAN JUAN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D02C03', 'PUERTO PECHICHE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D02C04', 'PIJULLO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D02C05', 'RICAURTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D02C06', 'CATARAMA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D03C01', 'LA ESPERANZA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D03C02', 'CONTROL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D03C03', 'LA VALDRAMINA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D03C04', 'LA MERCED');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D03C05', 'GALO PLAZA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D03C06', 'DIVINO NIÑO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D03C07', '7 DE OCTUBRE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D03C08', 'GUAYACAN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D03C09', 'SAN CARLOS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D03C10', 'ALEJO LASCANO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D03C11', 'MOCACHE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D03C12', 'AGUAS FRIAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D04C01', 'ZAPOTAL NUEVO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D04C02', 'ZAPOTAL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D04C03', 'LA ERCILIA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D04C04', 'VENTANAS NORTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D04C05', 'VENTANAS CENTRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D04C06', 'VENTANAS SUR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D04C07', 'QUINSALOMA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D05C01', 'ANTONIO SOTOMAYOR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D05C02', 'BAGATELA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D05C03', 'SANTA MARTHA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D05C04', 'ABRAS DE MANTEQUILLA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D05C05', 'VINCES NORTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D05C06', 'VINCES SUR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D05C07', 'AUGUSTO VALENCIA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D05C08', 'VINCES CENTRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D05C09', 'BALZAR DE VINCES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D05C10', 'JAUNECHE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D05C11', 'PALENQUE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D06C01', 'FUMISA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D06C02', 'LA RESERVA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D06C03', 'BUENA FE OESTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D06C04', 'BUENA FE ESTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D06C05', 'PATRICIA PILAR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D06C06', 'EL VERGEL NORTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D06C07', 'LA NUEVA UNION');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D06C08', 'COSTA AZUL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D06C09', 'EL VERGEL SUR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('12D06C10', 'VALENCIA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D01C01', 'COLON');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D01C02', 'NUEVO PORTOVIEJO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D01C03', 'LOS CEREZOS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D01C04', 'EL FLORON');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D01C05', 'SAN PABLO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D01C06', 'PORTOVIEJO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D01C07', 'PICOAZA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D01C08', 'MEJIA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D01C09', 'EL GUABITO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D01C10', 'CRUCITA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D01C11', 'ALAJUELA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D01C12', 'PUEBLO NUEVO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D01C13', 'ABDON CALDERON');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D01C14', 'SAN PLACIDO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D02C01', 'LOS ESTEROS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D02C02', 'LA PRADERA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D02C03', 'RIO DE CAÑA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D02C04', 'TARQUI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D02C05', 'UNIVERSIDAD');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D02C06', 'MURCIELAGO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D02C07', 'CENTRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D02C08', 'MARIA AUXILIADORA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D02C09', 'MIRAFLORES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D02C10', 'CUBA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D02C11', 'SAN JUAN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D02C12', 'SAN MATEO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D02C13', 'SAN LORENZO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D02C14', 'LA PILA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D02C15', 'LOS BAJOS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D02C16', 'LEONIDAS PROAÃ?O');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D02C16', 'LEONIDAS PROAÐO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D02C17', 'LA FABRIL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D02C18', 'LA SEQUITA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D02C19', 'MONTECRISTI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D02C20', 'JARAMIJO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D03C01', 'SANCAN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D03C02', 'SAN VICENTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D03C03', 'PARQUE CENTRAL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D03C04', 'JIPIJAPA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D03C05', '3 DE MAYO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D03C06', 'LA AMERICA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D03C07', 'JULCUY');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D03C09', 'PUERTO CAYO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D03C10', 'PEDRO PABLO GOMEZ');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D03C11', 'PUERTO LOPEZ');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D04C01', 'LODANA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D04C02', 'SANTA ANA DE VUELTA LARGA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D04C03', 'SANTA ANA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D04C04', 'CHAMUCAME');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D04C05', 'AYACUCHO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D04C06', 'HONORATO VASQUEZ');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D04C07', 'LA UNION');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D04C08', 'SAN PABLO DE PUEBLO NUEVO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D04C09', 'SIXTO DURAN BALLEN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D04C10', 'NOBOA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D04C11', '24 DE MAYO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D04C12', 'BELLAVISTA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D04C13', 'OLMEDO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D04C14', 'SAN ROQUE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D05C01', 'LA BRAMADORA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D05C02', 'EL CHAPARRAL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D05C03', 'EL CARMEN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D05C04', 'EL PORVENIR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D05C05', 'EL PARAISO LA CATORCE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D05C06', 'SAN PEDRO DE SUMA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D05C07', 'WILFRIDO LOOR MOREIRA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D05C08', 'MANGA DEL CURA NORTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D05C09', 'MANGA DEL CURA SUR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D06C01', 'CALCETA CENTRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D06C02', 'CALCETA SUR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D06C03', 'TABLADO DEL TIGRE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D06C04', 'QUIROGA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D06C05', 'MEMBRILLO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D06C06', 'JUNIN NORTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D06C07', 'JUNIN SUR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D07C01', 'BEJUCO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D07C02', 'RANCHO VIEJO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D07C03', 'SAN ANDRES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D07C04', 'CENTRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D07C05', 'SANTA RITA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D07C06', 'TRES PUERTOS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D07C07', 'CONVENTO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D07C08', 'ELOY ALFARO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D07C09', 'BOYACA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D07C10', 'RICAURTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D07C11', 'SAN ANTONIO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D07C12', 'CANUTO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D07C13', 'BEJUQUILLO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D07C14', 'CHIBUNGA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D07C15', 'FLAVIO ALFARO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D07C16', 'PALALACHE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D07C17', 'PALANQUITA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D07C18', 'SAN FRANCISCO DE NOVILLO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D07C19', 'ZAPALLO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D08C01', 'SANTA ROSA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D08C02', 'EL DESVIO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D08C03', 'PICHINCHA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D08C04', 'SAN SEBASTIAN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D08C05', 'BARRAGANETE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D08C06', 'RIO VENDIDO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D09C01', 'MONUMENTOS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D09C02', 'CAMPOZANO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D09C03', 'TIERRAS AMARILLAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D09C04', 'LASCANO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D09C05', 'GUALE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D09C06', 'CASCOL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D10C01', 'ACHIOTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D10C02', 'PEDERNALES SUR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D10C03', 'PEDERNALES NORTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D10C04', 'BECHE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D10C05', 'COJIMIES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D10C06', '10 DE AGOSTO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D10C07', 'ATAHUALPA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D10C08', 'JAMA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D10C09', 'BOCA DE BIGUA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D11C01', 'BAHIA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D11C02', 'LAS CORONAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D11C03', 'CHARAPOTO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D11C04', 'SAN ISIDRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D11C05', 'SAN VICENTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D11C06', 'CANOA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D12C01', 'ROCAFUERTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D12C02', 'DANZARIN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D12C03', 'LA FLORIDA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D12C04', 'JUNCO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('13D12C05', 'BACHILLERO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('14D01C01', 'GENERAL PROAÑO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('14D01C02', 'SINAI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('14D01C03', 'RIO BLANCO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('14D01C04', '9 DE OCTUBRE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('14D01C05', 'MACAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('14D01C06', 'SEVILLA DON BOSCO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('14D01C07', 'CUCHAENTZA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('14D02C01', 'PALORA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('14D02C02', 'SANGAY CENTRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('14D02C03', 'HUAMBOYA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('14D02C04', 'PABLO SEXTO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('14D03C01', 'HUAMBI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('14D03C02', 'SUCUA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('14D03C03', 'LOGROÑO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('14D04C01', 'EL ROSARIO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('14D04C02', 'AMAZONAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('14D04C04', 'BOMBOIZA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('14D04C05', 'GUALAQUIZA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('14D04C06', 'SAN JUAN BOSCO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('14D04C07', 'PANANZA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('14D05C01', 'MACUMA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('14D05C02', 'TAISHA CENTRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('14D05C03', 'FRONTERA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('14D06C01', 'INDANZA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('14D06C02', 'LIMON');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('14D06C03', 'YUNGANZA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('14D06C04', 'PATUCA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('14D06C05', 'SANTIAGO DE MENDEZ');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('14D06C06', 'TWINTZA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('15D01C01', 'ARCHIDONA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('15D01C02', 'KM 24');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('15D01C03', 'AROSEMENA TOLA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('15D01C04', 'AEROPUERTO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('15D01C05', 'PALANDACOCHA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('15D01C06', 'TALAG');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('15D01C07', 'MISAHUALLI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('15D01C08', 'YURALPA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('15D01C09', 'AHUANO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('15D02C01', 'EL CHACO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('15D02C02', 'LINARES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('15D02C03', 'SAN ROSA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('15D02C04', 'OYACACHI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('15D02C05', 'SAN FRANCISCO DE BORJA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('15D02C06', 'PAPALLACTA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('16D01C01', 'PUYO SUR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('16D01C02', 'PUYO NORTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('16D01C03', 'CANELOS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('16D01C04', 'SARAYACU');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('16D01C05', '10 DE AGOSTO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('16D01C06', 'TARQUI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('16D01C07', 'FATIMA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('16D01C09', 'RIO TIGRE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('16D01C10', 'MONTALVO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('16D01C11', 'SHELL MERA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('16D01C12', 'SANTA CLARA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('16D02C01', 'ARAJUNO POBLADO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('16D02C02', 'ARAJUNO SELVA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D01C01', 'PACTO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D01C02', 'GUALEA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D01C03', 'NANEGAL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D01C04', 'NANEGALITO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D02C01', 'LOS LLANOS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D02C02', 'CALDERON');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D02C03', 'SAN JUAN DE CALDERON');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D02C04', 'BELLAVISTA DE CALDERON');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D02C05', 'LADERAS DE SAN FRANCISCO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D02C06', 'OYACOTO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D02C07', 'CARAPUNGO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D02C08', 'BICENTENARIO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D02C09', 'LLANO CHICO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D02C10', 'GUAYLLABAMBA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D03C01', 'PUELLARO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D03C02', 'PERUCHO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D03C03', 'SAN JOSE DE MINAS OCCIDENTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D03C04', 'SAN JOSE DE MINAS ORIENTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D03C05', 'LA ROLDOS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D03C06', 'COLINAS DEL NORTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D03C07', 'MENA DEL HIERRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D03C08', 'EL CONDADO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D03C09', 'PONCIANO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D03C10', 'SAN ANTONIO BAJO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D03C11', 'SAN ANTONIO ALTO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D03C12', 'NONO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D03C13', 'COTOCOLLAO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D03C14', 'POMASQUI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D03C15', 'LA PAMPA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D03C16', 'CALACALI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D03C17', 'CARCELEN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D03C18', 'LA BOTA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D03C19', 'EL MIRADOR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D04C01', 'MONJAS COLLACOTO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D04C02', 'PUENGASI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D04C03', 'CENTRO HISTORICO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D04C04', 'PANECILLO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D04C05', 'EL PLACER');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D04C06', 'SAN JUAN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D04C07', 'LA LIBERTAD');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D04C08', 'ITCHIMBIA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D05C01', 'AEROPUERTO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D05C02', 'LA MARISCAL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D05C03', 'LAS CASAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D05C04', 'UNIVERSITARIO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D05C05', 'SAN ISIDRO DEL INCA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D05C06', 'EL BOSQUE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D05C07', 'DAMMER');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D05C08', 'KENNEDY');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D05C09', 'NAYON');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D05C10', 'IÑAQUITO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D05C11', 'COCHAPAMBA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D05C12', 'JIPIJAPA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D05C13', 'ZAMBIZA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D06C01', 'CHILIBULO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D06C02', 'EL CALZADO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D06C03', 'SANTA ANITA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D06C04', 'CHIMBACALLE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D06C05', 'ARGELIA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D06C06', 'SOLANDA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D06C07', 'BARRIO NUEVO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D06C08', 'MENA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D06C09', 'LLOA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D06C10', 'MAGDALENA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D06C11', 'FERROVIARIA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D07C01', 'CHILLOGALLO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D07C02', 'GUAMANI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D07C03', 'LAS CUADRAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D07C04', 'QUITUMBE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D07C05', 'TURUBAMBA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D07C06', 'ECUATORIANA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D08C01', 'CONOCOTO NORTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D08C02', 'CONOCOTO SUR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D08C03', 'SANTA ROSA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D08C04', 'PINTAG');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D08C05', 'SANTA ISABEL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D08C06', 'AMAGUAÑA CENTRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D08C07', 'EL EJIDO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D08C08', 'ALANGASI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D08C09', 'GUANGOPOLO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D08C10', 'LA MERCED');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D09C01', 'TUMBACO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D09C02', 'TUMBACO SUR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D09C03', 'VIA LACTEA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D09C04', 'CUMBAYA SUR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D09C05', 'PIFO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D09C06', 'TABLON');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D09C07', 'YARUQUI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D09C08', 'QUINCHE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D09C09', 'PUEMBO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D09C10', 'CHECA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D09C11', 'TABABELA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D10C01', 'EL PRADO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D10C02', 'CAYAMBE NORTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D10C03', 'CAYAMBE SUR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D10C04', 'CANGAGUA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D10C05', 'CUSUBAMBA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D10C06', 'OLMEDO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D10C07', 'TABACUNDO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D10C08', 'MALCHINGUI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D11C01', 'MACHACHI SUR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D11C02', 'MACHACHI NORTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D11C03', 'CUTUGLAGUA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D11C04', 'PASOCHOA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D11C05', 'ALOAG');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D11C06', 'TANDAPI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D11C07', 'ILINIZAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D11C08', 'RURAL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D11C09', 'MOLINUCO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D11C10', 'RUMIÑAHUI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D11C11', 'SAN RAFAEL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D11C12', 'SANGOLQUI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D11C13', 'FAJARDO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D12C01', 'MALDONADO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D12C02', 'PUERTO QUITO NORTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D12C03', 'PUERTO QUITO SUR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('17D12C04', 'LOS BANCOS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D01C01', 'MIRAFLORES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D01C02', 'JARDIN AMBATEÑO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D01C03', 'LA MATRIZ');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D01C04', 'ATOCHA FICOA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D01C05', 'LA VICTORIA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D01C06', 'INGAURCO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D01C07', 'PASA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D01C08', 'SAN BARTOLOME DE PINLLO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D01C09', 'QUISAPINCHA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D01C10', 'ATAHUALPA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D01C11', 'CUNCHIBAMBA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D01C12', 'IZAMBA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D02C01', 'HUACHI EL BELEN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D02C02', 'LETAMENDI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D02C03', 'SAN ANTONIO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D02C04', 'NUEVA AMBATO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D02C05', 'TECHO PROPIO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D02C06', 'PISHIDATA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D02C07', 'SIMON BOLIVAR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D02C08', 'MIÑARICA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D02C09', 'PILAHUIN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D02C10', 'SANTA ROSA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D02C11', 'PICAIHUA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D02C12', 'HUACHI GRANDE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D03C01', 'BAÑOS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D03C02', 'RIO NEGRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D04C01', 'PATATE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D04C02', 'PELILEO GRANDE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D04C03', 'EL TAMBO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D04C04', 'PELILEO SUR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D04C05', 'SALASACA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D04C06', 'GARCIA MORENO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D04C07', 'COTALO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D05C01', 'PILLARO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D05C02', 'SAN MIGUELITO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D05C03', 'SAN ANDRES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D06C01', 'CEVALLOS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D06C02', 'MOCHA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D06C03', 'QUERO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D06C04', 'RUMIPAMBA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('18D06C05', 'TISALEO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('19D01C01', 'CENTRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('19D01C02', 'LA CHACRA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('19D01C03', 'SABANILLA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('19D01C05', 'GUADALUPE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('19D01C06', 'MANBIJA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('19D01C07', 'YACUAMBI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('19D01C08', 'LA PAZ');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('19D01C09', 'TUTUPALI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('19D02C01', 'GUAYZIMI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('19D02C02', 'ZURMI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('19D02C03', 'NUEVO PASAISO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('19D02C04', 'ZUMBI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('19D02C05', 'PAQUISHA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('19D02C06', 'NUEVO QUITO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('19D03C01', 'SAN ANDRES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('19D03C02', 'LA BALSA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('19D03C03', 'ZUMBA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('19D03C04', 'CHITO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('19D03C05', 'PALANDA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('19D03C06', 'PORVENIR DEL CARMEN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('19D03C07', 'SAN FRANCISCO DEL VERGEL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('19D04C01', 'YANTZAZA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('19D04C02', 'LOS ENCUENTROS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('19D04C03', 'PANGUI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('19D04C04', 'TUNDAYME');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('20D01C01', 'ISABELA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('20D01C02', 'FERNANDINA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('20D01C03', 'SAN CRISTOBAL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('20D01C04', 'PROGRESO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('20D01C05', 'BELLAVISTA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('20D01C06', 'PUERTO AYORA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('20D01C07', 'PINZON');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('21D01C01', 'CASCALES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('21D01C02', 'LUMBAQUI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('21D01C03', 'LA BONITA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('21D02C01', 'NUEVO SUCUMBIOS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('21D02C02', 'EL DORADO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('21D02C03', 'PARQUE ECOLOGICO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('21D02C04', 'LAS PALMERAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('21D02C05', 'SANTA CECILIA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('21D02C06', 'EL ENO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('21D02C07', 'PACAYACU');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('21D02C08', 'GENERAL FARFAN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('21D03C01', 'TARAPOA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('21D03C03', 'PALMA ROJA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('21D03C04', 'PUERTO DEL CARMEN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('21D04C01', 'LA PRIMAVERA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('21D04C02', 'SHUSHUFINDI CENTRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('21D04C03', '7 DE JULIO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('21D04C04', 'PAÑACOCHA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('21D04C05', 'LIMONCOCHA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('22D01C01', 'SAN SEBASTIAN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('22D01C02', 'SAN PEDRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('22D01C03', 'SACHAS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('22D01C04', 'POMPEYA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('22D02C01', '24 DE MAYO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('22D02C02', 'LORETO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('22D02C03', 'PAYAMINO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('22D02C04', 'COCA ORIENTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('22D02C05', 'COCA OCCIDENTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('22D02C06', 'NUEVO PARAISO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('22D02C07', 'LA BELLEZA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('22D02C08', 'DAYUMA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('22D02C09', 'ALEJANDRO LABAKA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('22D02C10', 'INES ARANGO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('22D02C11', 'SAN LUIS DE ARMENIA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('22D03C01', 'AGUARICO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('22D03C02', 'NUEVO ROCAFUERTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('22D03C03', 'RIO NAPO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('23D01C01', 'COLONIA VELASCO IBARRA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('23D01C02', 'CENTRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('23D01C03', 'SANTA MARTHA NORTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('23D01C04', 'SANTA MARTHA SUR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('23D01C05', '3 DE JULIO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('23D01C06', 'UNIFICADOS');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('23D01C07', 'CRISTO VIVE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('23D01C08', 'LAS MERCEDES');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('23D01C09', 'EL TOACHI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('23D01C10', 'BOLIVAR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('23D01C11', 'LA LORENA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('23D01C12', 'EL ESFUERZO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('23D01C13', 'SANTA MARIA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('23D01C14', 'ALLURIQUIN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('23D01C15', 'LELIA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('23D01C16', 'LUZ DE AMERICA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('23D01C17', 'JULIO MORENO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('23D02C01', 'JUAN EULOGIO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('23D02C02', 'CHILA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('23D02C03', 'BOMBOLI');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('23D02C04', 'EL COLORADO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('23D02C05', 'EL PROLETARIADO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('23D02C06', 'PLAN DE VIVIENDA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('23D02C07', 'NUEVO ISRAEL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('23D02C08', 'VALLE HERMOSO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('23D02C09', 'SAN JACINTO DEL BUA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('23D02C10', 'SAN VICENTE DE BUA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('23D02C11', 'PUERTO LIMON');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('23D03C01', 'CONCORDIA NORTE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('23D03C02', 'MONTE REY');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('23D03C03', 'PLAN PILOTO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('24D01C01', 'CHANDUY');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('24D01C02', 'JULIO MORENO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('24D01C03', 'ATAHUALPA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('24D01C04', 'SANTA ELENA CENTRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('24D01C05', 'SAN PABLO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('24D01C06', 'MANANTIAL');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('24D01C07', 'PALMAR');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('24D01C08', 'COLONCHE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('24D01C09', 'OLON');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('24D01C10', 'MONTAÑITA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('24D02C01', 'LIBERTAD CENTRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('24D02C02', 'VIRGEN DEL CARMEN');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('24D02C03', '5 DE JUNIO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('24D02C04', 'ENRIQUEZ GALLO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('24D02C05', 'SALINAS CENTRO');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('24D02C06', 'SANTA ROSA');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('24D02C07', 'PUERTO AGUAJE');
INSERT INTO circuito(codigo_distrito, codigo, nombre) VALUES('24D02C08', 'ANCONCITO');
