INSERT INTO distrito(codigo, nombre) VALUES('0', 'MAR TERRITORIAL');
INSERT INTO distrito(codigo, nombre) VALUES('01D01', 'CUENCA NORTE');
INSERT INTO distrito(codigo, nombre) VALUES('01D02', 'CUENCA SUR');
INSERT INTO distrito(codigo, nombre) VALUES('01D03', 'GIRON');
INSERT INTO distrito(codigo, nombre) VALUES('01D04', 'GUALACEO');
INSERT INTO distrito(codigo, nombre) VALUES('01D05', 'NABON');
INSERT INTO distrito(codigo, nombre) VALUES('01D06', 'PAUTE');
INSERT INTO distrito(codigo, nombre) VALUES('01D07', 'PONCE ENRIQUEZ');
INSERT INTO distrito(codigo, nombre) VALUES('01D08', 'SIGSIG');
INSERT INTO distrito(codigo, nombre) VALUES('02D01', 'GUARANDA');
INSERT INTO distrito(codigo, nombre) VALUES('02D02', 'CHILLANES');
INSERT INTO distrito(codigo, nombre) VALUES('02D03', 'SAN MIGUEL');
INSERT INTO distrito(codigo, nombre) VALUES('02D04', 'SUBTROPICO');
INSERT INTO distrito(codigo, nombre) VALUES('03D01', 'AZOGUES');
INSERT INTO distrito(codigo, nombre) VALUES('03D02', 'CAÑAR');
INSERT INTO distrito(codigo, nombre) VALUES('03D03', 'LA TRONCAL');
INSERT INTO distrito(codigo, nombre) VALUES('04D01', 'TULCAN');
INSERT INTO distrito(codigo, nombre) VALUES('04D02', 'MONTUFAR');
INSERT INTO distrito(codigo, nombre) VALUES('04D03', 'ESPEJO');
INSERT INTO distrito(codigo, nombre) VALUES('05D01', 'LATACUNGA');
INSERT INTO distrito(codigo, nombre) VALUES('05D02', 'LA MANA');
INSERT INTO distrito(codigo, nombre) VALUES('05D03', 'PANGUA');
INSERT INTO distrito(codigo, nombre) VALUES('05D04', 'DANSANTE');
INSERT INTO distrito(codigo, nombre) VALUES('05D05', 'SIGCHOS');
INSERT INTO distrito(codigo, nombre) VALUES('05D06', 'SALCEDO');
INSERT INTO distrito(codigo, nombre) VALUES('06D01', 'RIOBAMBA');
INSERT INTO distrito(codigo, nombre) VALUES('06D02', 'ALAUSI');
INSERT INTO distrito(codigo, nombre) VALUES('06D03', 'PALLATANGA');
INSERT INTO distrito(codigo, nombre) VALUES('06D04', 'COLTA');
INSERT INTO distrito(codigo, nombre) VALUES('06D05', 'GUANO');
INSERT INTO distrito(codigo, nombre) VALUES('07D01', 'PASAJE');
INSERT INTO distrito(codigo, nombre) VALUES('07D02', 'MACHALA');
INSERT INTO distrito(codigo, nombre) VALUES('07D03', 'ZARUMA');
INSERT INTO distrito(codigo, nombre) VALUES('07D04', 'PIÑAS');
INSERT INTO distrito(codigo, nombre) VALUES('07D05', 'HUAQUILLAS');
INSERT INTO distrito(codigo, nombre) VALUES('07D06', 'SANTA ROSA');
INSERT INTO distrito(codigo, nombre) VALUES('08D01', 'ESMERALDAS');
INSERT INTO distrito(codigo, nombre) VALUES('08D02', 'ELOY ALFARO');
INSERT INTO distrito(codigo, nombre) VALUES('08D03', 'ATACAMES');
INSERT INTO distrito(codigo, nombre) VALUES('08D04', 'QUININDE');
INSERT INTO distrito(codigo, nombre) VALUES('08D05', 'SAN LORENZO');
INSERT INTO distrito(codigo, nombre) VALUES('08D06', 'RIO VERDE');
INSERT INTO distrito(codigo, nombre) VALUES('09D01', 'SUR');
INSERT INTO distrito(codigo, nombre) VALUES('09D02', 'ESTEROS');
INSERT INTO distrito(codigo, nombre) VALUES('09D03', '9 DE OCTUBRE');
INSERT INTO distrito(codigo, nombre) VALUES('09D04', 'PORTETE');
INSERT INTO distrito(codigo, nombre) VALUES('09D05', 'MODELO');
INSERT INTO distrito(codigo, nombre) VALUES('09D06', 'FLORIDA');
INSERT INTO distrito(codigo, nombre) VALUES('09D07', 'PASCUALES');
INSERT INTO distrito(codigo, nombre) VALUES('09D08', 'NUEVA PROSPERINA');
INSERT INTO distrito(codigo, nombre) VALUES('09D09', 'CEIBOS');
INSERT INTO distrito(codigo, nombre) VALUES('09D10', 'PROGRESO');
INSERT INTO distrito(codigo, nombre) VALUES('09D11', 'JUJAN SIMON BOLIVAR');
INSERT INTO distrito(codigo, nombre) VALUES('09D12', 'NARANJAL BALAO');
INSERT INTO distrito(codigo, nombre) VALUES('09D13', 'BALZAR');
INSERT INTO distrito(codigo, nombre) VALUES('09D14', 'PEDRO CARBO');
INSERT INTO distrito(codigo, nombre) VALUES('09D15', 'EL EMPALME');
INSERT INTO distrito(codigo, nombre) VALUES('09D16', 'EL TRIUNFO BUCAY');
INSERT INTO distrito(codigo, nombre) VALUES('09D17', 'MILAGRO');
INSERT INTO distrito(codigo, nombre) VALUES('09D18', 'NARANJITO MARCELINO MARIDUEÑA');
INSERT INTO distrito(codigo, nombre) VALUES('09D19', 'DAULE');
INSERT INTO distrito(codigo, nombre) VALUES('09D20', 'SALITRE');
INSERT INTO distrito(codigo, nombre) VALUES('09D21', 'YAGUACHI');
INSERT INTO distrito(codigo, nombre) VALUES('09D22', 'PLAYAS');
INSERT INTO distrito(codigo, nombre) VALUES('09D23', 'SAMBORONDON');
INSERT INTO distrito(codigo, nombre) VALUES('09D24', 'DURAN');
INSERT INTO distrito(codigo, nombre) VALUES('10D01', 'CIUDAD BLANCA');
INSERT INTO distrito(codigo, nombre) VALUES('10D02', 'VALLE DEL AMANECER');
INSERT INTO distrito(codigo, nombre) VALUES('10D03', 'LAS GOLONDRINAS');
INSERT INTO distrito(codigo, nombre) VALUES('10D03', 'TIERRA DEL SOL');
INSERT INTO distrito(codigo, nombre) VALUES('11D01', 'LOJA');
INSERT INTO distrito(codigo, nombre) VALUES('11D02', 'CATAMAYO');
INSERT INTO distrito(codigo, nombre) VALUES('11D03', 'CATACOCHA');
INSERT INTO distrito(codigo, nombre) VALUES('11D04', 'SABANILLA');
INSERT INTO distrito(codigo, nombre) VALUES('11D05', 'ESPINDOLA');
INSERT INTO distrito(codigo, nombre) VALUES('11D06', 'CALVAS');
INSERT INTO distrito(codigo, nombre) VALUES('11D07', 'MACARA');
INSERT INTO distrito(codigo, nombre) VALUES('11D08', 'SARAGURO');
INSERT INTO distrito(codigo, nombre) VALUES('11D09', 'ZAPOTILLO');
INSERT INTO distrito(codigo, nombre) VALUES('12D01', 'BABAHOYO');
INSERT INTO distrito(codigo, nombre) VALUES('12D02', 'PUEBLOVIEJO');
INSERT INTO distrito(codigo, nombre) VALUES('12D03', 'QUEVEDO');
INSERT INTO distrito(codigo, nombre) VALUES('12D04', 'VENTANAS');
INSERT INTO distrito(codigo, nombre) VALUES('12D05', 'VINCES');
INSERT INTO distrito(codigo, nombre) VALUES('12D06', 'BUENA FE');
INSERT INTO distrito(codigo, nombre) VALUES('13D01', 'PORTOVIEJO');
INSERT INTO distrito(codigo, nombre) VALUES('13D02', 'MANTA');
INSERT INTO distrito(codigo, nombre) VALUES('13D03', 'JIPIJAPA');
INSERT INTO distrito(codigo, nombre) VALUES('13D04', '24 DE MAYO');
INSERT INTO distrito(codigo, nombre) VALUES('13D05', 'EL CARMEN');
INSERT INTO distrito(codigo, nombre) VALUES('13D06', 'BOLIVAR JUNIN');
INSERT INTO distrito(codigo, nombre) VALUES('13D07', 'CHONE');
INSERT INTO distrito(codigo, nombre) VALUES('13D08', 'PICHINCHA');
INSERT INTO distrito(codigo, nombre) VALUES('13D09', 'PAJAN');
INSERT INTO distrito(codigo, nombre) VALUES('13D10', 'PEDERNALES');
INSERT INTO distrito(codigo, nombre) VALUES('13D11', 'SUCRE');
INSERT INTO distrito(codigo, nombre) VALUES('13D12', 'ROCAFUERTE');
INSERT INTO distrito(codigo, nombre) VALUES('14D01', 'MORONA');
INSERT INTO distrito(codigo, nombre) VALUES('14D02', 'SANGAY');
INSERT INTO distrito(codigo, nombre) VALUES('14D03', 'CENTRO SUR');
INSERT INTO distrito(codigo, nombre) VALUES('14D04', 'SUR');
INSERT INTO distrito(codigo, nombre) VALUES('14D05', 'TAISHA');
INSERT INTO distrito(codigo, nombre) VALUES('14D06', 'MENDEZ');
INSERT INTO distrito(codigo, nombre) VALUES('15D01', 'TENA');
INSERT INTO distrito(codigo, nombre) VALUES('15D02', 'EL VALLE DE QUIJOS');
INSERT INTO distrito(codigo, nombre) VALUES('16D01', 'PASTAZA');
INSERT INTO distrito(codigo, nombre) VALUES('16D02', 'ARAJUNO');
INSERT INTO distrito(codigo, nombre) VALUES('17D01', 'NANEGAL');
INSERT INTO distrito(codigo, nombre) VALUES('17D02', 'CALDERON');
INSERT INTO distrito(codigo, nombre) VALUES('17D03', 'LA DELICIA');
INSERT INTO distrito(codigo, nombre) VALUES('17D04', 'MANUELA SAENZ');
INSERT INTO distrito(codigo, nombre) VALUES('17D05', 'EUGENIO ESPEJO');
INSERT INTO distrito(codigo, nombre) VALUES('17D06', 'ELOY ALFARO');
INSERT INTO distrito(codigo, nombre) VALUES('17D07', 'QUITUMBE');
INSERT INTO distrito(codigo, nombre) VALUES('17D08', 'LOS CHILLOS');
INSERT INTO distrito(codigo, nombre) VALUES('17D09', 'TUMBACO');
INSERT INTO distrito(codigo, nombre) VALUES('17D10', 'CAYAMBE');
INSERT INTO distrito(codigo, nombre) VALUES('17D11', 'RUMIÑAHUI - MEJIA');
INSERT INTO distrito(codigo, nombre) VALUES('17D12', 'NOROCCIDENTE');
INSERT INTO distrito(codigo, nombre) VALUES('18D01', 'AMBATO NORTE');
INSERT INTO distrito(codigo, nombre) VALUES('18D02', 'AMBATO SUR');
INSERT INTO distrito(codigo, nombre) VALUES('18D03', 'BAÑOS');
INSERT INTO distrito(codigo, nombre) VALUES('18D04', 'PATATE');
INSERT INTO distrito(codigo, nombre) VALUES('18D05', 'PILLARO');
INSERT INTO distrito(codigo, nombre) VALUES('18D06', 'QUERO');
INSERT INTO distrito(codigo, nombre) VALUES('19D01', 'ZAMORA');
INSERT INTO distrito(codigo, nombre) VALUES('19D02', 'PAQUISHA');
INSERT INTO distrito(codigo, nombre) VALUES('19D03', 'CHINCHIPE');
INSERT INTO distrito(codigo, nombre) VALUES('19D04', 'YANTZAZA');
INSERT INTO distrito(codigo, nombre) VALUES('20D01', 'GALAPAGOS');
INSERT INTO distrito(codigo, nombre) VALUES('21D01', 'SUCUMBIOS');
INSERT INTO distrito(codigo, nombre) VALUES('21D02', 'LAGO AGRIO');
INSERT INTO distrito(codigo, nombre) VALUES('21D03', 'PUTUMAYO');
INSERT INTO distrito(codigo, nombre) VALUES('21D04', 'SHUSHUFINDI');
INSERT INTO distrito(codigo, nombre) VALUES('22D01', 'LA JOYA DE LOS SACHAS');
INSERT INTO distrito(codigo, nombre) VALUES('22D02', 'ORELLANA LORETO');
INSERT INTO distrito(codigo, nombre) VALUES('22D03', 'AGUARICO');
INSERT INTO distrito(codigo, nombre) VALUES('23D01', 'SANTO DOMINGO ESTE');
INSERT INTO distrito(codigo, nombre) VALUES('23D02', 'SANTO DOMINGO OESTE');
INSERT INTO distrito(codigo, nombre) VALUES('23D03', 'LA CONCORDIA');
INSERT INTO distrito(codigo, nombre) VALUES('24D01', 'SANTA ELENA');
INSERT INTO distrito(codigo, nombre) VALUES('24D02', 'LIBERTAD SALINAS');
INSERT INTO distrito(codigo, nombre) VALUES('90D01', 'EL PIEDRERO');
