INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '0', 'ABANIN, GUANAZAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '0', 'ALHAJUELA (BAJO GRANDE), CHIRIJOS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '0', 'CAPZOL, COMPUD, LLAGOS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '0', 'EL GOALTAL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '0', 'MAR TERRITORIAL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '0', 'OYACACHI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '0', 'VALLE DE LA VIRGEN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100150', 'SAN MIGUEL DE IBARRA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100151', 'AMBUQUI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100152', 'ANGOCHAGUA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100153', 'CAROLINA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100154', 'LA ESPERANZA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100155', 'LITA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100156', 'SALINAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100157', 'SAN ANTONIO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100250', 'ATUNTAQUI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100251', 'IMBAYA (SAN LUIS DE COBUENDO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100252', 'SAN FCO. DE NATABUELA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100253', 'SAN JOSE DE CHALTURA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100254', 'SAN ROQUE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100350', 'COTACACHI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100351', 'APUELA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100352', 'GARCIA MORENO (LLURIMAGUA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100352', 'LAS GOLONDRINAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100353', 'IMANTAG');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100355', 'PLAZA GUTIERREZ (CALVARIO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100356', 'QUIROGA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100450', 'OTAVALO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100451', 'DOCTOR MIGUEL EGAS CABEZAS (PEGUCHE)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100452', 'EUGENIO ESPEJO (CALPAQUI)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100453', 'GONZALEZ SUAREZ');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100455', 'SAN JOSE DE QUICHINCHE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100456', 'SAN JUAN DE ILUMAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100457', 'SAN PABLO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100458', 'SAN RAFAEL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100550', 'PIMAMPIRO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100551', 'CHUGA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100553', 'SAN  FCO. DE SIGSIPAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100650', 'URCUQUI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100651', 'CAHUASQUI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100652', 'LA MERCED DE BUENOS AIRES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100653', 'PABLO ARENAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100654', 'SAN BLAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '100655', 'TUMBABIRO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10150', 'CUENCA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10151', 'BAÑOS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10152', 'CUMBE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10154', 'CHECA (JIDCAY)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10155', 'CHIQUINTAD');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10156', 'LLACAO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10157', 'MOLLETURO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10158', 'NULTI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10159', 'OCTAVIO CORDERO PALACIOS (STA. ROSA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10160', 'PACCHA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10161', 'QUINGEO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10162', 'RICAURTE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10163', 'SAN JOAQUIN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10164', 'SANTA ANA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10165', 'SAYAUSI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10166', 'SIDCAY');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10167', 'SININCAY');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10168', 'TARQUI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10169', 'TURI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10170', 'VALLE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10171', 'VICTORIA DEL PORTETE (IRQUIS)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10250', 'GIRON');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10251', 'ASUNCION');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10350', 'GUALACEO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10353', 'JADAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10354', 'MARIANO MORENO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10356', 'REMIGIO CRESPO TORAL (GULAG)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10357', 'SAN JUAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10358', 'ZHIDMAD');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10359', 'LUIS CORDERO VEGA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10360', 'SIMON BOLIVAR (CAB. EN GAÑANZOL)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10450', 'NABON');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10451', 'COCHAPATA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10452', 'EL PROGRESO (CAB. EN ZHOTA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10453', 'LAS NIEVES (CHAYA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10550', 'PAUTE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10553', 'CHICAN (GUILLERMO ORTEGA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10554', 'EL CABO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10556', 'GUARAINAG');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10559', 'SAN CRISTOBAL (CARLOS ORDOÑEZ LAZO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10561', 'TOMEBAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10562', 'DUG DUG');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10650', 'PUCARA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10652', 'SAN RAFAEL DE SHARUG');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10750', 'SAN FERNANDO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10751', 'CHUMBLIN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10850', 'SANTA ISABEL (CHAGUARURCO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10851', 'ABDON CALDERON (LA UNION)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10854', 'SAN SALVADOR DE CAÑARIBAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10950', 'SIGSIG');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10951', 'CUCHIL (CUTCHIL)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10952', 'GIMA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10954', 'LUDO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10955', 'SAN BARTOLOME');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '10956', 'SAN JOSE DE RARANGA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110150', 'LOJA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110151', 'CHANTACO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110152', 'CHUQUIRIBAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110153', 'EL CISNE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110154', 'GUALEL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110156', 'MALACATOS (VALLADOLID)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110157', 'SAN LUCAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110158', 'SAN PEDRO DE VILCABAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110159', 'SANTIAGO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110160', 'TAQUIL (MIGUEL RIOFRIO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110161', 'VILCABAMBA (VICTORIA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110162', 'YANGANA (ARSENIO CASTILLO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110163', 'QUINARA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110250', 'CARIAMANGA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110251', 'COLAISACA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110252', 'EL LUCERO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110254', 'SANGUILLIN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110350', 'CATAMAYO (LA TOMA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110351', 'EL TAMBO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110353', 'SAN PEDRO DE LA BENDITA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110354', 'ZAMBI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110450', 'CELICA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110451', 'CRUZPAMBA (CAB EN CARLOS BUSTAMANTE)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110455', 'POZUL (SAN JUAN DE POZUL)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110456', 'SABANILLA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '11050', 'SAN FELIPE DE OÑA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '11051', 'SUSUDEL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110550', 'CHAGUARPAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110551', 'BUENAVISTA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110554', 'AMARILLOS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110554', 'AMARILLOS, BUENAVISTA, SANTA RUFINA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110650', 'AMALUZA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110651', 'BELLAVISTA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110652', 'JIMBURA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110653', 'SANTA TERESITA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110750', 'GONZANAMA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110751', 'CHANGAIMINA (LA LIBERTAD)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110753', 'NAMBACOLA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110754', 'PURUNUMA (EGUIGUREN)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110756', 'SACAPALCA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110850', 'MACARA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110851', 'LARAMA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110852', 'LA VICTORIA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110853', 'SABIANGO (LA CAPILLA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110950', 'CATACOCHA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110952', 'GUACHANAMA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110954', 'LAURO GUERRERO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110956', 'ORIANGA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110958', 'CASANGA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '110959', 'YAMANA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '111050', 'ALAMOR');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '111054', 'MERCADILLO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '111055', 'VICENTINO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '111150', 'SARAGURO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '111151', 'EL PARAISO DE CELEN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '111152', 'EL TABLON');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '111153', 'LLUZHAPA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '111154', 'MANU');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '111155', 'SAN ANTONIO DE QUMBE (CUMBE)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '111156', 'SAN PABLO DE TENTA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '111157', 'SAN SEBASTIAN DE YULUC');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '111159', 'URDANETA (PAQUISHAPA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '111160', 'SUMAYPAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '111250', 'SOZORANGA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '111252', 'TACAMOROS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '111350', 'ZAPOTILLO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '111352', 'GARZAREAL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '111354', 'PALETILLAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '111450', 'PINDAL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '111452', '12 DE DICIEMBRE (CAB. EN ACHIOTES)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '111453', 'MILAGROS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '11150', 'CHORDELEG');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '11151', 'PRINCIPAL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '11152', 'LA UNION');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '111550', 'QUILANGA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '111552', 'SAN ANTONIO DE LAS ARADAS (CAB. EN LAS ARADAS)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '111650', 'OLMEDO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '111651', 'LA TINGUE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '11250', 'EL PAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '11350', 'SEVILLA DE ORO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '11351', 'AMALUZA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '11450', 'GUACHAPALA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '11550', 'CAMILO PONCE ENRIQUEZ');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '11551', 'EL CARMEN DE PIJILI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '120150', 'BABAHOYO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '120152', 'CARACOL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '120153', 'FEBRES CORDERO (LAS JUNTAS)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '120154', 'PIMOCHA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '120155', 'LA UNION');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '120250', 'BABA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '120251', 'GUARE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '120252', 'ISLA DE BEJUCAL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '120350', 'MONTALVO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '120351', 'LA ESMERALDA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '120450', 'PUEBLOVIEJO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '120451', 'PUERTO PECHICHE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '120452', 'SAN JUAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '120550', 'QUEVEDO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '120553', 'SAN CARLOS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '120555', 'LA ESPERANZA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '120650', 'CATARAMA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '120651', 'RICAURTE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '120750', 'VENTANAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '120752', 'ZAPOTAL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '120753', 'CHACARITA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '120754', 'LOS ANGELES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '120850', 'VINCES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '120851', 'ANTONIO SOTOMAYOR (CAB. EN PLAYAS DE VINCES)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '120950', 'PALENQUE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '121050', 'SAN JACINTO DE BUENA FE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '121051', 'PATRICIA PILAR');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '121150', 'VALENCIA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '121250', 'MOCACHE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '121350', 'QUINSALOMA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130150', 'PORTOVIEJO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130151', 'ABDON CALDERON (SAN FRANCISCO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130152', 'ALHAJUELA (BAJO GRANDE)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130153', 'CRUCITA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130154', 'PUEBLO NUEVO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130155', 'RIOCHICO (RIO CHICO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130156', 'SAN PLACIDO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130157', 'CHIRIJOS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130250', 'CALCETA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130251', 'MEMBRILLO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130252', 'QUIROGA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130350', 'CHONE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130351', 'BOYACA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130352', 'CANUTO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130353', 'CONVENTO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130354', 'CHIBUNGA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130355', 'ELOY ALFARO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130356', 'RICAURTE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130357', 'SAN ANTONIO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130450', 'EL CARMEN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130450', 'MANGA DEL CURA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130451', 'WILFRIDO LOOR MOREIRA (MAICITO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130452', 'SAN PEDRO DE SUMA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130550', 'FLAVIO ALFARO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130551', 'SAN FRANCISCO DE NOVILLO (CAB. EN NOVILLO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130552', 'ZAPALLO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130650', 'JIPIJAPA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130651', 'AMERICA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130652', 'EL ANEGADO (CAB. EN ELOY ALFARO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130653', 'JULCUY');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130654', 'LA UNION');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130657', 'PEDRO PABLO GOMEZ');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130658', 'PUERTO DE CAYO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130750', 'JUNIN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130850', 'MANTA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130851', 'SAN LORENZO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130950', 'MONTECRISTI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '130952', 'LA PILA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '131050', 'PAJAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '131051', 'CAMPOZANO (LA PALMA DE PAJAN)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '131052', 'CASCOL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '131053', 'GUALE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '131054', 'LASCANO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '131150', 'PICHINCHA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '131151', 'BARRAGANETE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '131152', 'SAN SEBASTIAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '131250', 'ROCAFUERTE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '131350', 'SANTA ANA DE VUELTA LARGA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '131351', 'AYACUCHO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '131352', 'HONORATO VASQUEZ (CAB EN VASQUEZ)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '131355', 'SAN PABLO (CAB EN PUEBLO NUEVO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '131450', 'BAHIA DE CARAQUEZ');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '131453', 'CHARAPOTO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '131457', 'SAN ISIDRO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '131550', 'TOSAGUA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '131551', 'BACHILLERO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '131552', 'ANGEL PEDRO GILER (LA ESTANCILLA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '131650', 'SUCRE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '131651', 'BELLAVISTA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '131652', 'NOBOA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '131653', 'ARQ. SIXTO DURAN BALLEN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '131750', 'PEDERNALES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '131751', 'COJIMIES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '131752', '10 DE AGOSTO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '131753', 'ATAHUALPA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '131850', 'OLMEDO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '131950', 'PUERTO LOPEZ');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '131951', 'MACHALILLA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '131952', 'SALANGO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '132050', 'JAMA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '132150', 'JARAMIJO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '132250', 'SAN VICENTE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '132251', 'CANOA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140150', 'MACAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140153', 'GENERAL PROAÑO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140156', 'SAN ISIDRO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140157', 'SEVILLA DON BOSCO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140158', 'SINAI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140160', 'ZUÑA (ZUÑAC)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140162', 'CUCHAENTZA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140164', 'RIO BLANCO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140250', 'GUALAQUIZA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140251', 'AMAZONAS (ROSARIO DE CUYES)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140253', 'BOMBOIZA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140254', 'CHIGUINDA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140255', 'EL ROSARIO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140256', 'NUEVA TARQUI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140258', 'EL IDEAL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140350', 'GRAL. LEONIDAS PLAZA GUTIERREZ');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140353', 'SAN ANTONIO (CAB EN SAN ANTONIO CENTRO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140357', 'STA SUSANA DE CHIVIAZA (CAB EN CHIVIAZA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140358', 'YUNGANZA (CAB EN EL ROSARIO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140450', 'PALORA (METZERA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140451', 'ARAPICOS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140452', 'CUMANDA (CAB EN COLONIA AGRICOLA SEVILLA DEL ORO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140454', 'SANGAY (CAB EN NAYAMANACA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140455', '16 DE AGOSTO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140550', 'SANTIAGO DE MENDEZ');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140552', 'CHUPIANZA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140553', 'PATUCA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140554', 'SAN LUIS DE EL ACHO (CAB EN EL ACHO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140556', 'TAYUZA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140557', 'SAN FRANCISCO DE CHINIMBIMI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140650', 'SUCUA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140651', 'ASUNCION');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140652', 'HUAMBI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140655', 'SANTA MARIANITA DE JESUS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140750', 'HUAMBOYA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140751', 'CHIGUAZA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140850', 'SAN JUAN BOSCO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140852', 'SAN CARLOS DE LIMON');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140854', 'SAN CARLOS DE LIMON, SANTIAGO DE PANANZA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140950', 'TAISHA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '140952', 'MACUMA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '141050', 'LOGROÑO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '141052', 'SHIMPIS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '141150', 'PABLO SEXTO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '141250', 'SANTIAGO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '141251', 'SAN JOSE DE MORONA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '150150', 'TENA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '150151', 'AHUANO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '150153', 'CHONTAPUNTA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '150154', 'PANO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '150155', 'PUERTO MISAHUALLI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '150156', 'PUERTO NAPO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '150157', 'TALAG');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '150158', 'SAN JUAN DE MUYUNA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '150350', 'ARCHIDONA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '150352', 'COTUNDO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '150354', 'SAN PABLO DE USHPAYACU');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '150356', 'HATUN SUMAKU');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '150450', 'EL CHACO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '150451', 'GONZALO DIAZ DE PINEDA (EL BOMBON)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '150452', 'LINARES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '150454', 'SANTA ROSA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '150455', 'SARDINAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '150750', 'BAEZA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '150751', 'COSANGA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '150752', 'CUYUJA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '150753', 'PAPALLACTA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '150754', 'SAN FRANCISCO DE BORJA (VIRGILIO DAVILA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '150756', 'SUMACO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '150950', 'CARLOS JULIO AROSEMENA TOLA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '160150', 'PUYO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '160152', 'CANELOS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '160154', 'DIEZ DE AGOSTO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '160155', 'FATIMA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '160156', 'MONTALVO (ANDOAS)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '160159', 'RIO TIGRE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '160161', 'SARAYACU');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '160162', 'SIMON BOLIVAR (CAB. EN MUSHULLACTA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '160163', 'TARQUI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '160164', 'TENIENTE HUGO ORTIZ');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '160165', 'VERACRUZ (INDILLAMA) (CAB. EN INDILLAMA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '160166', 'EL TRIUNFO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '160250', 'MERA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '160251', 'MADRE TIERRA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '160252', 'SHELL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '160350', 'SANTA CLARA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '160351', 'SAN JOSE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '160450', 'ARAJUNO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '160451', 'CURARAY');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170150', 'QUITO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170151', 'ALANGASI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170152', 'AMAGUAÑA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170154', 'CALACALI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170155', 'CALDERON (CARAPUNGO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170156', 'CONOCOTO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170157', 'CUMBAYA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170158', 'CHAVEZPAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170159', 'CHECA (CHILPA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170160', 'EL QUINCHE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170161', 'GUALEA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170162', 'GUANGOPOLO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170163', 'GUAYLLABAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170164', 'LA MERCED');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170165', 'LLANO CHICO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170166', 'LLOA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170168', 'NANEGAL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170169', 'NANEGALITO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170170', 'NAYON');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170171', 'NONO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170172', 'PACTO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170174', 'PERUCHO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170175', 'PIFO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170176', 'PINTAG');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170177', 'POMASQUI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170178', 'PUELLARO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170179', 'PUEMBO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170180', 'SAN ANTONIO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170181', 'SAN JOSE DE MINAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170183', 'TABABELA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170184', 'TUMBACO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170185', 'YARUQUI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170186', 'ZAMBIZA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170250', 'CAYAMBE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170251', 'ASCAZUBI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170252', 'CANGAHUA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170253', 'OLMEDO (PESILLO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170254', 'OTON');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170255', 'SANTA ROSA DE CUZUBAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170256', 'SAN JOSE DE AYORA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170350', 'MACHACHI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170351', 'ALOAG');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170352', 'ALOASI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170353', 'CUTUGLAHUA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170354', 'EL CHAUPI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170355', 'MANUEL CORNEJO ASTORGA (TANDAPI)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170356', 'TAMBILLO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170357', 'UYUMBICHO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170450', 'TABACUNDO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170451', 'LA ESPERANZA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170452', 'MALCHINGUI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170453', 'TOCACHI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170454', 'TUPIGACHI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170550', 'SANGOLQUI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170551', 'COTOGCHOA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170552', 'RUMIPAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170750', 'SAN MIGUEL DE LOS BANCOS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170751', 'MINDO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170850', 'PEDRO VICENTE MALDONADO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '170950', 'PUERTO QUITO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180150', 'AMBATO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180151', 'AMBATILLO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180152', 'ATAHUALPA (CHISALATA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180153', 'AUGUSTO N. MARTINEZ (MUNDUGLEO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180154', 'CONSTANTINO FERNANDEZ (CAB. EN CULLITAHUA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180155', 'HUACHI GRANDE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180156', 'IZAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180157', 'JUAN BENIGNO VELA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180158', 'MONTALVO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180159', 'PASA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180160', 'PICAIGUA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180161', 'PILAGUIN (PILAHUIN)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180162', 'QUISAPINCHA (QUIZAPINCHA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180163', 'SAN BARTOLOME DE PINLLOG');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180165', 'SANTA ROSA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180166', 'TOTORAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180167', 'CUNCHIBAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180168', 'UNAMUNCHO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180250', 'BAÑOS DE AGUA SANTA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180252', 'RIO NEGRO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180253', 'RIO VERDE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180254', 'ULBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180350', 'CEVALLOS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180450', 'MOCHA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180451', 'PINGUILI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180550', 'PATATE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180551', 'EL TRIUNFO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180553', 'SUCRE (CAB. EN SUCRE-PATATE URCU)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180650', 'QUERO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180651', 'RUMIPAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180652', 'YANAYACU - MOCHAPATA (CAB. EN YANAYACU)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180750', 'PELILEO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180751', 'BENITEZ (PACHANLICA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180752', 'BOLIVAR');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180753', 'COTALO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180754', 'CHIQUICHA (CAB. EN CHIQUICHA GRANDE)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180755', 'EL ROSARIO (RUMICHACA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180756', 'GARCIA MORENO (CHUMAQUI)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180757', 'GUAMBALO (HUAMBALO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180758', 'SALASACA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180850', 'PILLARO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180852', 'EMILIO MARIA TERAN (RUMIPAMBA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180853', 'MARCOS ESPINEL (CHACATA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180854', 'PRESIDENTE URBINA (CHAGRAPAMBA -PATZUCUL)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180855', 'SAN ANDRES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180856', 'SAN JOSE DE POALO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180857', 'SAN MIGUELITO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180950', 'TISALEO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '180951', 'QUINCHICOTO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '190150', 'ZAMORA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '190151', 'CUMBARATZA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '190152', 'GUADALUPE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '190155', 'SABANILLA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '190156', 'TIMBARA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '190158', 'SAN CARLOS DE LAS MINAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '190250', 'ZUMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '190251', 'CHITO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '190254', 'LA CHONTA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '190256', 'PUCAPAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '190350', 'GUAYZIMI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '190351', 'ZURMI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '190352', 'NUEVO PARAISO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '190450', '28 DE MAYO (SAN JOSE DE YACUAMBI)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '190451', 'LA PAZ');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '190550', 'YANTZAZA (YANZATZA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '190551', 'CHICAÑA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '190553', 'LOS ENCUENTROS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '190650', 'EL PANGUI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '190651', 'EL GUISME');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '190652', 'PACHICUTZA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '190653', 'TUNDAYME');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '190750', 'ZUMBI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '190752', 'TRIUNFO-DORADO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '190753', 'PANGUINTZA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '190850', 'PALANDA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '190852', 'SAN FRANCISCO DEL VERGEL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '190853', 'VALLADOLID');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '190854', 'LA CANELA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '190950', 'PAQUISHA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '190951', 'BELLAVISTA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '190952', 'NUEVO QUITO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '200150', 'PUERTO BAQUERIZO MORENO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '200151', 'EL PROGRESO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '200250', 'PUERTO VILLAMIL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '200251', 'TOMAS DE BERLANGA (SANTO TOMAS)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '200350', 'PUERTO AYORA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '200351', 'BELLAVISTA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '200352', 'SANTA ROSA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '20150', 'GUARANDA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '20151', 'FACUNDO VELA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '20153', 'JULIO E. MORENO (CATANAHUAN GRANDE)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '20155', 'SALINAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '20156', 'SAN LORENZO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '20157', 'SAN SIMON (YACOTO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '20158', 'SANTA FE (SANTA FE)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '20159', 'SIMIATUG');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '20160', 'SAN LUIS DE PAMBIL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '20250', 'CHILLANES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '20251', 'SAN JOSE DEL TAMBO (TAMBOPAMBA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '20350', 'SAN JOSE DE CHIMBO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '20351', 'ASUNCION (ASANCOTO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '20353', 'MAGDALENA (CHAPACOTO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '20354', 'SAN SEBASTIAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '20355', 'TELIMBELA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '20450', 'ECHEANDIA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '20550', 'SAN MIGUEL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '20551', 'BALSAPAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '20552', 'BILOVAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '20553', 'REGULO DE MORA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '20554', 'SAN PABLO (SAN PABLO DE ATENAS)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '20555', 'SANTIAGO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '20650', 'CALUMA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '20750', 'LAS NAVES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '210150', 'NUEVA LOJA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '210152', 'DURENO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '210153', 'GENERAL FARFAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '210155', 'EL ENO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '210156', 'PACAYACU');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '210157', 'JAMBELI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '210158', 'SANTA CECILIA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '210160', '10 DE AGOSTO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '210250', 'LUMBAQUI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '210251', 'EL REVENTADOR');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '210252', 'GONZALO PIZARRO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '210350', 'PUERTO EL CARMEN DEL PUTUMAYO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '210351', 'PALMA ROJA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '210352', 'PUERTO BOLIVAR (PUERTO MONTUFAR)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '210450', 'SHUSHUFINDI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '210451', 'LIMONCOCHA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '210452', 'PAÑACOCHA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '210453', 'SAN ROQUE (CAB. EN SAN VICENTE)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '210454', 'SAN PEDRO DE LOS COFANES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '210455', 'SIETE DE JULIO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '210550', 'LA BONITA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '210554', 'SANTA BARBARA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '210650', 'EL DORADO DE CASCALES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '210651', 'SANTA ROSA DE SUCUMBIOS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '210652', 'SEVILLA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '210750', 'TARAPOA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '210752', 'AGUAS NEGRAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '220150', 'PUERTO FRANCISCO DE ORELLANA (EL COCA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '220151', 'DAYUMA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '220152', 'TARACOA (NUEVA ESPERANZA: YUCA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '220153', 'ALEJANDRO LABAKA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '220154', 'EL DORADO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '220156', 'GARCIA MORENO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '220157', 'INES ARANGO (CAB. EN WESTERN)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '220158', 'LA BELLEZA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '220159', 'NUEVO PARAISO (CAB. EN UNION )');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '220160', 'SAN JOSE DE GUAYUSA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '220161', 'SAN LUIS DE ARMENIA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '220250', 'NUEVO ROCAFUERTE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '220252', 'CONONACO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '220254', 'TIPUTINI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '220350', 'LA JOYA DE LOS SACHAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '220351', 'ENOKANQUI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '220352', 'POMPEYA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '220353', 'SAN CARLOS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '220354', 'SAN SEBASTIAN DEL COCA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '220355', 'LAGO SAN PEDRO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '220356', 'RUMIPAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '220357', 'TRES DE NOVIEMBRE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '220358', 'UNION MILAGREÑA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '220450', 'LORETO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '220451', 'AVILA (CAB. EN HUIRUNO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '220452', 'PUERTO MURIALDO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '220453', 'SAN JOSE DE PAYAMINO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '220454', 'SAN JOSE DE DAHUANO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '220455', 'SAN VICENTE DE HUATICOCHA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '230150', 'SANTO DOMINGO DE LOS COLORADOS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '230151', 'ALLURIQUIN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '230152', 'PUERTO LIMON');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '230153', 'LUZ DE AMERICA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '230154', 'SAN JACINTO DEL BUA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '230155', 'VALLE HERMOSO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '230156', 'EL ESFUERZO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '230157', 'SANTA MARIA DEL TOACHI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '240150', 'SANTA ELENA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '240151', 'ATAHUALPA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '240152', 'COLONCHE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '240153', 'CHANDUY');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '240154', 'MANGLARALTO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '240156', 'SAN JOSE DE ANCON');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '240250', 'LA LIBERTAD');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '240350', 'SALINAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '240351', 'ANCONCITO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '240352', 'JOSE LUIS TAMAYO (MUEY)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '30150', 'AZOGUES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '30151', 'COJITAMBO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '30153', 'GUAPAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '30154', 'JAVIER LOYOLA (CHUQUIPATA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '30155', 'LUIS CORDERO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '30158', 'SAN MIGUEL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '30160', 'TADAY');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '30250', 'BIBLIAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '30251', 'NAZON (CAB. EN PAMPA DE DOMINGUEZ)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '30252', 'SAN FRANCISCO DE SAGEO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '30253', 'TURUPAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '30254', 'JERUSALEN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '30350', 'CAÑAR');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '30352', 'CHOROCOPTE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '30353', 'GENERAL MORALES (SOCARTE)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '30354', 'GUALLETURO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '30355', 'HONORATO VASQUEZ (TAMBO VIEJO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '30356', 'INGAPIRCA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '30357', 'JUNCAL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '30358', 'SAN ANTONIO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '30361', 'ZHUD');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '30363', 'DUCUR');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '30450', 'LA TRONCAL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '30451', 'MANUEL J. CALLE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '30452', 'PANCHO NEGRO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '30550', 'EL TAMBO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '30650', 'DELEG');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '30651', 'SOLANO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '30750', 'SUSCAL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '40150', 'TULCAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '40151', 'EL CARMELO (EL PUN)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '40153', 'JULIO ANDRADE (OREJUELA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '40156', 'TOBAR DONOSO (LA BOCANA DE CAMUMBI)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '40157', 'TUFIÑO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '40158', 'URBINA (TAYA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '40159', 'EL CHICAL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '40161', 'SANTA MARTHA DE CUBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '40250', 'BOLIVAR');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '40251', 'GARCIA MORENO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '40252', 'LOS ANDES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '40253', 'MONTE OLIVO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '40255', 'SAN RAFAEL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '40350', 'EL ANGEL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '40352', 'LA LIBERTAD (ALIZO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '40353', 'SAN ISIDRO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '40450', 'MIRA (CHONTAHUASI)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '40451', 'CONCEPCION');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '40452', 'JIJON Y CAAMAÑO (CAB. EN RIO BLANCO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '40453', 'JUAN MONTALVO (SAN IGNACIO DE QUIL)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '40550', 'SAN GABRIEL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '40551', 'CRISTOBAL COLON');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '40552', 'CHITAN DE NAVARRETE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '40553', 'FERNANDEZ SALVADOR');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '40554', 'LA PAZ');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '40650', 'HUACA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '40651', 'MARISCAL SUCRE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50150', 'LATACUNGA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50151', 'ALAQUES (ALAQUEZ)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50152', 'BELISARIO QUEVEDO (GUANAILIN)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50153', 'GUAITACAMA (GUAYTACAMA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50154', 'JOSEGUANGO BAJO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50156', 'MULALO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50157', '11 DE NOVIEMBRE (ILINCHISI)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50158', 'POALO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50159', 'SAN JUAN DE PASTOCALLE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50161', 'TANICUCHI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50162', 'TOACASO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50250', 'LA MANA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50251', 'GUASAGANDA (CAB. EN GUASAGANDA CENTRO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50252', 'PUCAYACU');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50350', 'EL CORAZON');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50351', 'MORASPUNGO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50352', 'PINLLOPATA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50450', 'PUJILI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50455', 'LA VICTORIA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50456', 'PILALO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50457', 'TINGO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50458', 'ZUMBAHUA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50550', 'SAN MIGUEL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50551', 'ANTONIO JOSE HOLGUIN (SANTA LUCIA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50552', 'CUSUBAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50553', 'MULALILLO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50554', 'MULLIQUINDIL (SANTA ANA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50555', 'PANSALEO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50650', 'SAQUISILI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50651', 'CANCHAGUA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50652', 'CHANTILIN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50653', 'COCHAPAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50750', 'SIGCHOS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50751', 'CHUGCHILLAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '50752', 'ISINLIVI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60150', 'RIOBAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60152', 'CALPI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60153', 'CUBIJIES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60155', 'LICAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60156', 'LICTO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60157', 'PUNGALA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60158', 'PUNIN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60159', 'QUIMIAG');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60160', 'SAN JUAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60161', 'CACHA (CAB. EN MACHANGARA), SAN LUIS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60161', 'SAN LUIS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60250', 'ALAUSI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60251', 'ACHUPALLAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60253', 'GUASUNTOS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60254', 'HUIGRA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60255', 'MULTITUD');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60258', 'SEVILLA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60259', 'SIBAMBE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60350', 'VILLA LA UNION (CAJABAMBA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60352', 'COLUMBE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60353', 'JUAN DE VELASCO (PANGOR)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60354', 'SANTIAGO DE QUITO (CAB. EN SAN ANTONIO DE QUITO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60450', 'CHAMBO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60550', 'CHUNCHI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60552', 'COMPUD');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60554', 'LLAGOS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60650', 'GUAMOTE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60651', 'CEBADAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60652', 'PALMIRA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60750', 'GUANO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60751', 'GUANANDO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60752', 'ILAPO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60753', 'LA PROVIDENCIA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60754', 'SAN ANDRES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60755', 'SAN GERARDO DE PACAICAGUAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60756', 'SAN ISIDRO DE PATULU');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60758', 'SANTA FE DE GALAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60850', 'PALLATANGA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60950', 'PENIPE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60952', 'MATUS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '60954', 'SAN ANTONIO DE BAYUSHIG');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '61050', 'CUMANDA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '70150', 'MACHALA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '70152', 'EL RETIRO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '70250', 'ARENILLAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '70251', 'CHACRAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '70254', 'PALMALES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '70255', 'CARCABON');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '70350', 'PACCHA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '70351', 'AYAPAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '70352', 'CORDONCILLO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '70353', 'MILAGRO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '70355', 'SAN JUAN DE CERRO AZUL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '70450', 'BALSAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '70451', 'BELLAMARIA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '70550', 'CHILLA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '70650', 'EL GUABO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '70651', 'BARBONES (SUCRE)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '70652', 'LA IBERIA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '70653', 'TENDALES (CAB. EN PUERTO TENDALES)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '70654', 'RIO BONITO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '70750', 'HUAQUILLAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '70850', 'MARCABELI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '70851', 'EL INGENIO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '70950', 'PASAJE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '70951', 'BUENAVISTA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '70952', 'CASACAY');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '70953', 'LA PEAÑA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '70954', 'PROGRESO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '70955', 'UZHCURRUMI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '70956', 'CAÑAQUEMADA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '71050', 'PIÑAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '71052', 'LA BOCANA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '71054', 'PIEDRAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '71055', 'SAN ROQUE (AMBROSIO MALDONADO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '71056', 'SARACAY');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '71150', 'PORTOVELO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '71151', 'CURTINCAPA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '71152', 'MORALES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '71250', 'SANTA ROSA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '71251', 'BELLAVISTA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '71252', 'JAMBELI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '71253', 'LA AVANZADA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '71254', 'SAN ANTONIO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '71255', 'TORATA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '71256', 'VICTORIA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '71257', 'BELLAMARIA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '71350', 'ZARUMA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '71352', 'ARCAPAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '71353', 'GUANAZAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '71354', 'GUIZHAGUIÑA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '71355', 'HUERTAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '71356', 'MALVAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '71357', 'MULUNCAY GRANDE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '71358', 'SINSAO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '71450', 'LA VICTORIA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '71452', 'EL PARAISO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '71453', 'SAN ISIDRO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80150', 'ESMERALDAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80152', 'CAMARONES (CAB. EN SAN VICENTE)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80154', 'CHINCA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80159', 'MAJUA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80163', 'SAN MATEO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80165', 'TABIAZO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80166', 'TACHINA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80168', 'VUELTA LARGA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80250', 'VALDEZ (LIMONES)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80253', 'BORBON');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80254', 'LA TOLA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80255', 'LUIS VARGAS TORRES (CAB. EN PLAYA DE ORO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80256', 'MALDONADO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80257', 'PAMPANAL DE BOLIVAR');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80258', 'SAN FRANCISCO DE ONZOLE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80259', 'SANTO DOMINGO DE ONZOLE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80260', 'SELVA ALEGRE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80261', 'TELEMBI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80262', 'COLON ELOY DEL MARIA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80265', 'SANTA LUCIA DE LAS PEÑAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80350', 'MUISNE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80352', 'DAULE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80354', 'QUINGUE (OLMEDO PERDOMO FRANCO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80355', 'SALIMA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80356', 'SAN FRANCISCO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80357', 'SAN GREGORIO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80358', 'SAN JOSE DE CHAMANGA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80450', 'ROSA ZARATE (QUININDE)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80451', 'CUBE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80452', 'CHURA (CHANCAMA) (CAB. EN EL YERBERO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80453', 'MALIMPIA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80454', 'VICHE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80455', 'LA UNION');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80550', 'SAN LORENZO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80551', 'ALTO TAMBO (CAB EN GUADUAL)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80552', 'ANCON (PICHANGAL) (CAB. EN PALMA REAL)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80553', 'CALDERON');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80554', 'CARONDELET');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80556', 'CONCEPCION');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80557', 'MATAJE (CAB. EN SANTANDER)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80559', 'SANTA RITA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80560', 'TAMBILLO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80561', 'TULULBI (CAB. EN RICAURTE)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80562', 'URBINA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80650', 'ATACAMES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80651', 'LA UNION');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80652', 'SUA (CAB. EN LA BOCANA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80653', 'TONCHIGUE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80654', 'TONSUPA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80750', 'RIOVERDE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80751', 'CHONTADURO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80752', 'CHUMUNDE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80753', 'LAGARTO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80754', 'MONTALVO (CAB EN HORQUETA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80755', 'ROCAFUERTE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80850', 'LA CONCORDIA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80851', 'MONTERREY');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80852', 'LA VILLEGAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '80853', 'PLAN PILOTO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '900451', 'EL PIEDRERO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '90150', 'GUAYAQUIL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '90152', 'JUAN GOMEZ RENDON (PROGRESO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '90153', 'MORRO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '90156', 'POSORJA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '90157', 'PUNA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '90158', 'TENGUEL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '90250', 'ALFREDO BAQUERIZO MORENO (JUJAN)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '90350', 'BALAO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '90450', 'BALZAR');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '90550', 'COLIMES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '90551', 'SAN JACINTO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '90650', 'DAULE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '90652', 'JUAN BAUTISTA AGUIRRE (LOS TINTOS)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '90653', 'LAUREL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '90654', 'LIMONAL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '90656', 'LOS LOJAS (ENRIQUE BAQUERIZO MORENO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '90750', 'ELOY ALFARO (DURAN)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '90850', 'VELASCO IBARRA (CAB. EL EMPALME)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '90851', 'GUAYAS (PUEBLO NUEVO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '90852', 'EL ROSARIO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '90950', 'EL TRIUNFO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '91050', 'MILAGRO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '91051', 'CHOBO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '91053', 'MARISCAL SUCRE (HUAQUES)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '91054', 'ROBERTO ASTUDILLO (CAB. EN CRUCE DE VENECIA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '91150', 'NARANJAL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '91151', 'JESUS MARIA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '91152', 'SAN CARLOS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '91153', 'SANTA ROSA DE FLANDES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '91154', 'TAURA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '91250', 'NARANJITO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '91350', 'PALESTINA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '91450', 'PEDRO CARBO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '91451', 'VALLE DE LA VIRGEN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '91452', 'SABANILLA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '91650', 'SAMBORONDON');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '91651', 'TARIFA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '91850', 'SANTA LUCIA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '91950', 'EL SALITRE (LAS RAMAS)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '91951', 'GRAL. VERNAZA (DOS ESTEROS)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '91952', 'LA VICTORIA (ÑAUZA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '91953', 'JUNQUILLAL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '92050', 'SAN JACINTO DE YAGUACHI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '92053', 'GRAL. PEDRO J. MONTERO (BOLICHE)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '92055', 'YAGUACHI VIEJO (CONE)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '92056', 'VIRGEN DE FATIMA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '92150', 'GENERAL VILLAMIL (PLAYAS)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '92250', 'SIMON BOLIVAR');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '92251', 'CRNEL. LORENZO DE GARAICOA (PEDREGAL)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '92350', 'CORONEL MARCELINO MARIDUEÑA (SAN CARLOS)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '92450', 'LOMAS DE SARGENTILLO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '92550', 'NARCISA DE JESUS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '92750', 'GRAL. ANTONIO ELIZALDE (BUCAY)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, '92850', 'ISIDRO AYORA');
