INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', '10 DE AGOSTO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', '11 DE NOVIEMBRE (ILINCHISI)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', '12 DE DICIEMBRE (CAB. EN ACHIOTES)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', '16 DE AGOSTO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', '28 DE MAYO (SAN JOSE DE YACUAMBI)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', '6 DE JULIO DE CUELLAJE (CAB. EN CUELLAJE)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ABDON CALDERON (LA UNION)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ABDON CALDERON (SAN FRANCISCO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ACHUPALLAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'AGUAS NEGRAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'AHUANO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ALAMOR');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ALANGASI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ALAQUES (ALAQUEZ)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ALAUSI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ALEJANDRO LABAKA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ALFREDO BAQUERIZO MORENO (JUJAN)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ALHAJUELA (BAJO GRANDE)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ALLURIQUIN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ALOAG');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ALOASI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ALTO TAMBO (CAB EN GUADUAL)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'AMAGUAÑA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'AMALUZA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'AMBATILLO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'AMBATO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'AMBUQUI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ANCHAYACU');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ANCONCITO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ANGAMARCA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ANGEL PEDRO GILER (LA ESTANCILLA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ANGOCHAGUA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ANTONIO JOSE HOLGUIN (SANTA LUCIA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ANTONIO SOTOMAYOR (CAB. EN PLAYAS DE VINCES)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'APUELA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ARAJUNO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ARCHIDONA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ARENILLAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ARQ. SIXTO DURAN BALLEN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ASCAZUBI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ASUNCION');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ASUNCION (ASANCOTO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ATACAMES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ATAHUALPA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ATAHUALPA (CHISALATA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ATUNTAQUI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'AUGUSTO N. MARTINEZ (MUNDUGLEO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'AVILA (CAB. EN HUIRUNO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'AYACUCHO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'AYAPAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'AZOGUES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'BABA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'BABAHOYO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'BACHILLERO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'BAEZA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'BAHIA DE CARAQUEZ');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'BALAO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'BALSAPAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'BALSAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'BALZAR');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'BARBONES (SUCRE)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'BARRAGANETE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'BAÑOS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'BAÑOS DE AGUA SANTA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'BELISARIO QUEVEDO (GUANAILIN)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'BELLAMARIA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'BELLAVISTA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'BENITEZ (PACHANLICA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'BIBLIAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'BOLIVAR');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'BOMBOIZA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'BORBON');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'BOYACA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'BUENAVISTA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'BULAN (JOSE VICTOR IZQUIERDO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CAHUASQUI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CALACALI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CALCETA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CALDERON');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CALDERON (CARAPUNGO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CALPI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CALUMA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CAMARONES (CAB. EN SAN VICENTE)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CAMILO PONCE ENRIQUEZ');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CAMPOZANO (LA PALMA DE PAJAN)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CANCHAGUA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CANELOS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CANGAHUA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CANOA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CANUTO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CAPIRO (CAB. EN LA CAPILLA DE CAPIRO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CARACOL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CARCABON');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CARIAMANGA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CARLOS JULIO AROSEMENA TOLA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CAROLINA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CARONDELET');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CASACAY');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CASANGA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CASCOL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CATACOCHA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CATAMAYO (LA TOMA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CATARAMA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CAYAMBE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CAÑAQUEMADA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CAÑAR');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CEBADAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CELICA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CEVALLOS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHACARITA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHACRAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHAGUARPAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHAMBO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHANDUY');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHANGAIMINA (LA LIBERTAD)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHANTACO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHANTILIN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHAQUINAL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHARAPOTO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHAVEZPAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHECA (CHILPA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHECA (JIDCAY)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHIBUNGA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHICAN (GUILLERMO ORTEGA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHICAÑA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHIGUAZA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHIGUINDA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHILLA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHILLANES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHINCA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHIQUICHA (CAB. EN CHIQUICHA GRANDE)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHIQUINTAD');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHITAN DE NAVARRETE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHITO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHOBO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHONE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHONTADURO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHONTAMARCA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHONTAPUNTA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHORDELEG');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHOROCOPTE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHUGA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHUGCHILLAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHUMBLIN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHUMUNDE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHUNCHI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHUPIANZA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHUQUIRIBAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CHURA (CHANCAMA) (CAB. EN EL YERBERO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CIANO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'COCHAPATA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'COJIMIES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'COJITAMBO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'COLAISACA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'COLIMES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'COLON ELOY DEL MARIA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'COLONCHE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'COLUMBE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CONCEPCION');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CONOCOTO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CONONACO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CONSTANTINO FERNANDEZ (CAB. EN CULLITAHUA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CONVENTO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'COPAL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CORONEL MARCELINO MARIDUEÑA (SAN CARLOS)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'COSANGA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'COTACACHI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'COTALO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'COTOGCHOA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'COTUNDO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CRISTOBAL COLON');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CRNEL. CARLOS CONCHA TORRES (CAB. EN HUELE)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CRNEL. LORENZO DE GARAICOA (PEDREGAL)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CRUCITA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CRUZPAMBA (CAB EN CARLOS BUSTAMANTE)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CUBE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CUBIJIES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CUCHAENTZA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CUCHIL (CUTCHIL)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CUENCA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CUMANDA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CUMANDA (CAB EN COLONIA AGRICOLA SEVILLA DEL ORO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CUMBARATZA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CUMBAYA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CUMBE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CUNCHIBAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CURARAY');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CURTINCAPA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CUSUBAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CUTUGLAHUA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'CUYUJA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'DANIEL CORDOVA TORAL (EL ORIENTE)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'DAULE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'DAYUMA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'DELEG');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'DIEZ DE AGOSTO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'DOCTOR MIGUEL EGAS CABEZAS (PEGUCHE)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'DUCUR');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'DURENO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ECHEANDIA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL AIRO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL ANEGADO (CAB. EN ELOY ALFARO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL ANGEL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL CABO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL CARMELO (EL PUN)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL CARMEN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL CARMEN DE PIJILI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL CHACO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL CHAUPI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL CHICAL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL CISNE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL CORAZON');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL DORADO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL DORADO DE CASCALES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL ENO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL ESFUERZO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL GUABO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL GUISME');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL IDEAL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL INGENIO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL LUCERO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL PAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL PANGUI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL PARAISO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL PARAISO DE CELEN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL PIEDRERO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL PLAYON DE SAN FRANCISCO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL PORVENIR DEL CARMEN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL PROGRESO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL PROGRESO (CAB. EN ZHOTA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL QUINCHE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL RETIRO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL REVENTADOR');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL ROSARIO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL ROSARIO (RUMICHACA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL SALITRE (LAS RAMAS)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL TABLON');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL TAMBO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EL TRIUNFO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ELOY ALFARO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ELOY ALFARO (DURAN)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EMILIO MARIA TERAN (RUMIPAMBA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ENOKANQUI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ESMERALDAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'EUGENIO ESPEJO (CALPAQUI)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'FACUNDO VELA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'FATIMA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'FEBRES CORDERO (LAS JUNTAS)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'FERNANDEZ SALVADOR');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'FLAVIO ALFARO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'FLORES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GALERA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GARCIA MORENO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GARCIA MORENO (CHUMAQUI)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GARCIA MORENO (LLURIMAGUA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GENERAL FARFAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GENERAL MORALES (SOCARTE)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GENERAL PROAÑO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GENERAL VILLAMIL (PLAYAS)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GIMA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GIRON');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GONZALEZ SUAREZ');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GONZALO DIAZ DE PINEDA (EL BOMBON)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GONZALO PIZARRO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GONZANAMA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GONZOL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GRAL. ANTONIO ELIZALDE (BUCAY)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GRAL. LEONIDAS PLAZA GUTIERREZ');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GRAL. PEDRO J. MONTERO (BOLICHE)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GRAL. VERNAZA (DOS ESTEROS)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GUACHANAMA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GUACHAPALA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GUADALUPE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GUAITACAMA (GUAYTACAMA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GUALACEO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GUALAQUIZA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GUALE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GUALEA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GUALEL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GUALLETURO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GUAMBALO (HUAMBALO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GUAMOTE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GUANANDO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GUANGAJE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GUANGOPOLO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GUANO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GUAPAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GUARAINAG');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GUARANDA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GUARE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GUASAGANDA (CAB. EN GUASAGANDA CENTRO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GUAYAQUIL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GUAYAS (PUEBLO NUEVO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GUAYLLABAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GUAYZIMI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GUEL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'GUIZHAGUIÑA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'HATUN SUMAKU');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'HONORATO VASQUEZ (CAB EN VASQUEZ)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'HONORATO VASQUEZ (TAMBO VIEJO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'HUACA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'HUACHI GRANDE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'HUAMBI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'HUAMBOYA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'HUAQUILLAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'HUERTAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'HUIGRA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ILAPO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'IMANTAG');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'IMBAYA (SAN LUIS DE COBUENDO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'INDANZA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'INES ARANGO (CAB. EN WESTERN)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'INGAPIRCA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ISIDRO AYORA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ISINLIVI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ISLA DE BEJUCAL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'IZAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'JADAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'JAMA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'JAMBELI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'JARAMIJO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'JAVIER LOYOLA (CHUQUIPATA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'JERUSALEN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'JESUS MARIA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'JIJON Y CAAMAÑO (CAB. EN RIO BLANCO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'JIMBURA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'JIPIJAPA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'JOSE LUIS TAMAYO (MUEY)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'JOSEGUANGO BAJO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'JUAN BAUTISTA AGUIRRE (LOS TINTOS)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'JUAN BENIGNO VELA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'JUAN DE VELASCO (PANGOR)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'JUAN GOMEZ RENDON (PROGRESO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'JULCUY');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'JULIO ANDRADE (OREJUELA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'JULIO E. MORENO (CATANAHUAN GRANDE)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'JUNCAL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'JUNIN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'JUNQUILLAL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LA AVANZADA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LA BELLEZA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LA BOCANA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LA BONITA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LA CONCORDIA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LA ESMERALDA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LA ESPERANZA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LA IBERIA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LA JOYA DE LOS SACHAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LA LIBERTAD');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LA LIBERTAD (ALIZO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LA MANA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LA MERCED');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LA MERCED DE BUENOS AIRES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LA PAZ');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LA PEAÑA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LA PILA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LA PROVIDENCIA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LA TOLA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LA TRONCAL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LA UNION');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LA VICTORIA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LA VICTORIA (ÑAUZA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LA VILLEGAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LAGARTO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LAGO SAN PEDRO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LARAMA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LAS GOLONDRINAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LAS NAVES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LAS NIEVES (CHAYA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LAS PAMPAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LASCANO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LATACUNGA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LAUREL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LAURO GUERRERO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LICAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LICTO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LIMONAL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LIMONCOCHA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LIMONES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LITA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LLACAO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LLANO CHICO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LLOA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LLUZHAPA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LOGROÑO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LOJA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LOMAS DE SARGENTILLO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LORETO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LOS ANDES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LOS ANDES (CAB. EN POATUG)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LOS ANGELES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LOS ENCUENTROS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LOS LOJAS (ENRIQUE BAQUERIZO MORENO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LUDO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LUIS CORDERO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LUIS CORDERO VEGA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LUIS VARGAS TORRES (CAB. EN PLAYA DE ORO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LUMBAQUI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'LUZ DE AMERICA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MACARA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MACAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MACHACHI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MACHALA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MACHALILLA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MACUMA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MADRE TIERRA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MAGDALENA (CHAPACOTO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MAJUA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MALACATOS (VALLADOLID)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MALCHINGUI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MALDONADO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MALIMPIA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MALVAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MANGA DEL CURA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MANGAHURCO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MANGLARALTO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MANTA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MANU');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MANUEL CORNEJO ASTORGA (TANDAPI)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MANUEL J. CALLE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MAR TERRITORIAL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MARCABELI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MARCOS ESPINEL (CHACATA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MARIANO MORENO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MARISCAL SUCRE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MARISCAL SUCRE (HUAQUES)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MATAJE (CAB. EN SANTANDER)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MATUS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MEMBRILLO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MERA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MERCADILLO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MILAGRO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MINDO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MIRA (CHONTAHUASI)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MOCACHE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MOCHA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MOLLETURO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MONTALVO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MONTALVO (ANDOAS)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MONTALVO (CAB EN HORQUETA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MONTE OLIVO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MONTECRISTI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MONTERREY');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MORASPUNGO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MOROMORO (CAB. EN EL VADO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MORRO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MUISNE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MULALILLO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MULALO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MULLIQUINDIL (SANTA ANA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MULTITUD');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'MULUNCAY GRANDE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'NABON');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'NAMBACOLA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'NANEGAL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'NANEGALITO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'NARANJAL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'NARANJITO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'NARCISA DE JESUS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'NAYON');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'NAZON (CAB. EN PAMPA DE DOMINGUEZ)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'NOBOA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'NONO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'NUEVA FATIMA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'NUEVA LOJA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'NUEVO PARAISO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'NUEVO PARAISO (CAB. EN UNION )');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'NUEVO QUITO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'NUEVO ROCAFUERTE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'NULTI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'OCTAVIO CORDERO PALACIOS (STA. ROSA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'OLMEDO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'OLMEDO (PESILLO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ORIANGA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'OTAVALO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'OTON');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PABLO ARENAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PABLO SEXTO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PACAYACU');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PACCHA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PACHICUTZA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PACTO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PAJAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PALENQUE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PALESTINA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PALLATANGA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PALMA ROJA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PALMALES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PALMAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PALMIRA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PALORA (METZERA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PANCHO NEGRO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PANGUINTZA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PANO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PANSALEO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PAPALLACTA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PAQUISHA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PASA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PASAJE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PATATE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PATRICIA PILAR');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PATUCA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PAUTE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PAÑACOCHA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PEDERNALES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PEDRO CARBO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PEDRO PABLO GOMEZ');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PEDRO VICENTE MALDONADO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PELILEO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PENIPE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PERUCHO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PEÑAHERRERA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PIARTAL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PICAIGUA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PICHINCHA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PIEDRAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PIFO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PILAGUIN (PILAHUIN)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PILALO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PILLARO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PIMAMPIRO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PIMOCHA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PINDAL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PINDILIG');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PINGUILI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PINTAG');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PIOTER');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PIÑAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PLAN PILOTO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PLAZA GUTIERREZ (CALVARIO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'POALO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'POMASQUI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'POMONA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'POMPEYA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PORTOVELO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PORTOVIEJO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'POSORJA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PRESIDENTE URBINA (CHAGRAPAMBA -PATZUCUL)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PRINCIPAL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PROGRESO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PUCAPAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PUCARA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PUEBLO NUEVO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PUEBLOVIEJO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PUELA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PUELLARO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PUEMBO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PUERTO AYORA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PUERTO BAQUERIZO MORENO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PUERTO DE CAYO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PUERTO EL CARMEN DEL PUTUMAYO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PUERTO FRANCISCO DE ORELLANA (EL COCA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PUERTO LIBRE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PUERTO LIMON');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PUERTO LOPEZ');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PUERTO MISAHUALLI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PUERTO MURIALDO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PUERTO NAPO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PUERTO PECHICHE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PUERTO QUITO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PUERTO VILLAMIL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PUJILI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PUMPUENTSA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PUNA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PUNGALA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PUNIN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PURUNUMA (EGUIGUREN)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'PUYO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'QUERO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'QUEVEDO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'QUILANGA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'QUIMIAG');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'QUINARA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'QUINCHICOTO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'QUINGEO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'QUINSALOMA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'QUIROGA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'QUISAPINCHA (QUIZAPINCHA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'QUITO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'REGULO DE MORA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'REMIGIO CRESPO TORAL (GULAG)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'RICAURTE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'RIO BLANCO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'RIO BONITO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'RIO NEGRO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'RIO TIGRE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'RIO VERDE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'RIOBAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'RIOCHICO (RIO CHICO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'RIOVERDE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'RIVERA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ROBERTO ASTUDILLO (CAB. EN CRUCE DE VENECIA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ROCAFUERTE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ROSA FLORIDA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ROSA ZARATE (QUININDE)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'RUMIPAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SABANILLA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SABIANGO (LA CAPILLA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SACAPALCA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SALANGO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SALASACA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SALATI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SALIMA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SALINAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAMBORONDON');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN ANDRES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN ANTONIO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN ANTONIO (CAB EN SAN ANTONIO CENTRO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN ANTONIO DE BAYUSHIG');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN BARTOLOME');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN BARTOLOME DE PINLLOG');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN BLAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN CARLOS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN CARLOS DE LAS MINAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN CRISTOBAL (CARLOS ORDOÑEZ LAZO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN FCO. DE NATABUELA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN FELIPE DE OÑA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN FERNANDO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN FERNANDO (PASA SAN FERNANDO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN FRANCISCO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN FRANCISCO DE BORJA (VIRGILIO DAVILA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN FRANCISCO DE CHINIMBIMI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN FRANCISCO DE NOVILLO (CAB. EN NOVILLO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN FRANCISCO DE ONZOLE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN FRANCISCO DE SAGEO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN GABRIEL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN GERARDO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN GERARDO DE PACAICAGUAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN GREGORIO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN ISIDRO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN ISIDRO DE PATULU');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN JACINTO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN JACINTO DE BUENA FE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN JACINTO DE YAGUACHI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN JACINTO DEL BUA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN JAVIER DE CACHAVI (CAB. EN SAN JAVIER)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN JOAQUIN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN JOSE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN JOSE DE ANCON');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN JOSE DE AYORA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN JOSE DE CHALTURA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN JOSE DE CHAMANGA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN JOSE DE CHIMBO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN JOSE DE DAHUANO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN JOSE DE GUAYUSA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN JOSE DE MINAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN JOSE DE MORONA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN JOSE DE PAYAMINO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN JOSE DE POALO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN JOSE DE QUICHINCHE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN JOSE DE RARANGA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN JOSE DEL TAMBO (TAMBOPAMBA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN JUAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN JUAN BOSCO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN JUAN DE CERRO AZUL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN JUAN DE ILUMAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN JUAN DE MUYUNA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN JUAN DE PASTOCALLE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN LORENZO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN LUCAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN LUIS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN LUIS DE ARMENIA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN LUIS DE EL ACHO (CAB EN EL ACHO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN LUIS DE PAMBIL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN MARTIN DE PUZHIO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN MATEO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN MIGUEL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN MIGUEL DE IBARRA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN MIGUEL DE LOS BANCOS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN MIGUELITO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN PABLO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN PABLO (CAB EN PUEBLO NUEVO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN PABLO (SAN PABLO DE ATENAS)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN PABLO DE TENTA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN PABLO DE USHPAYACU');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN PEDRO DE LA BENDITA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN PEDRO DE LOS COFANES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN PEDRO DE SUMA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN PEDRO DE VILCABAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN PLACIDO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN RAFAEL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN RAFAEL DE SHARUG');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN ROQUE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN ROQUE (CAB. EN SAN VICENTE)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN SALVADOR DE CAÑARIBAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN SEBASTIAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN SEBASTIAN DE YULUC');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN SEBASTIAN DEL COCA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN SIMON (YACOTO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN VICENTE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN VICENTE DE HUATICOCHA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAN VICENTE DE PUSIR');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SANGAY (CAB EN NAYAMANACA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SANGOLQUI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SANGUILLIN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SANTA ANA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SANTA ANA DE VUELTA LARGA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SANTA BARBARA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SANTA CECILIA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SANTA CLARA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SANTA ELENA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SANTA FE (SANTA FE)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SANTA FE DE GALAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SANTA ISABEL (CHAGUARURCO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SANTA LUCIA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SANTA LUCIA DE LAS PEÑAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SANTA MARIA DE HUIRIRIMA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SANTA MARIA DEL TOACHI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SANTA MARIANITA DE JESUS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SANTA MARTHA DE CUBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SANTA RITA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SANTA ROSA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SANTA ROSA DE CUZUBAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SANTA ROSA DE FLANDES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SANTA ROSA DE SUCUMBIOS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SANTA TERESITA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SANTIAGO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SANTIAGO DE MENDEZ');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SANTIAGO DE QUITO (CAB. EN SAN ANTONIO DE QUITO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SANTO DOMINGO DE LOS COLORADOS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SANTO DOMINGO DE ONZOLE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAQUISILI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SARACAY');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SARAGURO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SARDINAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SAYAUSI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SELVA ALEGRE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SELVA ALEGRE (CAB. EN SAN MIGUEL DE PAMPLONA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SEVILLA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SEVILLA DE ORO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SEVILLA DON BOSCO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SHELL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SHIMPIS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SHUSHUFINDI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SIBAMBE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SIDCAY');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SIETE DE JULIO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SIGCHOS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SIGSIG');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SIMIATUG');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SIMON BOLIVAR');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SIMON BOLIVAR (CAB. EN GAÑANZOL)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SIMON BOLIVAR (CAB. EN MUSHULLACTA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SIMON BOLIVAR (JULIO MORENO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SINAI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SININCAY');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SINSAO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SOLANO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SOZORANGA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'STA SUSANA DE CHIVIAZA (CAB EN CHIVIAZA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SUA (CAB. EN LA BOCANA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SUCRE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SUCRE (CAB. EN SUCRE-PATATE URCU)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SUCUA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SUMAYPAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'SUSCAL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TABABELA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TABACUNDO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TABIAZO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TACAMOROS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TACHINA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TADAY');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TAISHA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TALAG');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TAMBILLO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TANICUCHI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TAQUIL (MIGUEL RIOFRIO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TARACOA (NUEVA ESPERANZA: YUCA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TARAPOA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TARIFA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TARQUI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TAURA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TAYUZA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TELIMBELA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TENA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TENDALES (CAB. EN PUERTO TENDALES)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TENGUEL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TENIENTE HUGO ORTIZ');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TIMBARA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TIMBIRE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TINGO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TIPUTINI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TISALEO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TIXAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TOACASO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TOCACHI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TOMAS DE BERLANGA (SANTO TOMAS)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TOMEBAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TONCHIGUE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TONSUPA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TORATA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TOSAGUA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TOTORAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TRES DE NOVIEMBRE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TRIUNFO-DORADO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TUFIÑO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TULCAN');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TULULBI (CAB. EN RICAURTE)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TUMBABIRO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TUMBACO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TUNDAYME');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TUPIGACHI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TURI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TURUPAMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'TUTUPALI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ULBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'UNAMUNCHO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'UNION MILAGREÑA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'URBINA (TAYA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'URCUQUI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'UYUMBICHO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'UZHCURRUMI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'VALDEZ (LIMONES)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'VALENCIA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'VALLADOLID');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'VALLE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'VALLE HERMOSO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'VELASCO IBARRA (CAB. EL EMPALME)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'VENTANAS');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'VERACRUZ (INDILLAMA) (CAB. EN INDILLAMA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'VICHE');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'VICTORIA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'VICTORIA DEL PORTETE (IRQUIS)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'VILCABAMBA (VICTORIA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'VILLA LA UNION (CAJABAMBA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'VINCES');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'VIRGEN DE FATIMA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'VUELTA LARGA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'WILFRIDO LOOR MOREIRA (MAICITO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'YAGUACHI VIEJO (CONE)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'YAMANA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'YANAYACU - MOCHAPATA (CAB. EN YANAYACU)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'YANGANA (ARSENIO CASTILLO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'YANTZAZA (YANZATZA)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'YARUQUI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'YASUNI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'YUNGANZA (CAB EN EL ROSARIO)');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ZAMBIZA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ZAMORA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ZAPALLO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ZAPOTAL');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ZAPOTILLO');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ZARUMA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ZHAGLLI (SHAGLLI )');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ZHIDMAD');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ZHUD');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ZUMBA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ZUMBAHUA');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ZUMBI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ZURMI');
INSERT INTO parroquia(id, codigo, nombre) VALUES(0, 'null', 'ZUÑA (ZUÑAC)');
