INSERT INTO provincia(id, codigo, nombre) VALUES(0, '0', 'MAR TERRITORIAL');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, '1', 'AZUAY');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, '10', 'IMBABURA');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, '11', 'LOJA');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, '12', 'LOS RIOS');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, '13', 'MANABI');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, '14', 'MORONA SANTIAGO');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, '15', 'NAPO');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, '16', 'PASTAZA');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, '17', 'PICHINCHA');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, '18', 'TUNGURAHUA');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, '19', 'ZAMORA CHINCHIPE');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, '2', 'BOLIVAR');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, '20', 'GALAPAGOS');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, '21', 'SUCUMBIOS');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, '22', 'ORELLANA');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, '23', 'SANTO DOMINGO DE LOS TSACHILAS');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, '24', 'SANTA ELENA');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, '3', 'CAÑAR');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, '4', 'CARCHI');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, '5', 'COTOPAXI');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, '6', 'CHIMBORAZO');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, '7', 'EL ORO');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, '8', 'ESMERALDAS');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, '9', 'GUAYAS');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, '90', 'CAÑAR');
