INSERT INTO provincia(id, codigo, nombre) VALUES(0, 'null', 'AZUAY');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, 'null', 'BOLIVAR');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, 'null', 'CARCHI');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, 'null', 'CAÑAR');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, 'null', 'CHIMBORAZO');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, 'null', 'COTOPAXI');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, 'null', 'EL ORO');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, 'null', 'ESMERALDAS');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, 'null', 'GALAPAGOS');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, 'null', 'GUAYAS');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, 'null', 'IMBABURA');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, 'null', 'LOJA');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, 'null', 'LOS RIOS');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, 'null', 'MANABI');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, 'null', 'MAR TERRITORIAL');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, 'null', 'MORONA SANTIAGO');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, 'null', 'NAPO');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, 'null', 'ORELLANA');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, 'null', 'PASTAZA');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, 'null', 'PICHINCHA');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, 'null', 'SANTA ELENA');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, 'null', 'SANTO DOMINGO DE LOS TSACHILAS');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, 'null', 'SUCUMBIOS');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, 'null', 'TUNGURAHUA');
INSERT INTO provincia(id, codigo, nombre) VALUES(0, 'null', 'ZAMORA CHINCHIPE');
