INSERT INTO zona(nombre, nombre_subzona) VALUES('ZND', 'CAÑAR');
INSERT INTO zona(nombre, nombre_subzona) VALUES('ZND', 'MANABI');
INSERT INTO zona(nombre, nombre_subzona) VALUES('ZND', 'MAR TERRITORIAL');
INSERT INTO zona(nombre, nombre_subzona) VALUES('ZND', 'PICHINCHA');
INSERT INTO zona(nombre, nombre_subzona) VALUES('ZONA 1', 'CARCHI');
INSERT INTO zona(nombre, nombre_subzona) VALUES('ZONA 1', 'ESMERALDAS');
INSERT INTO zona(nombre, nombre_subzona) VALUES('ZONA 1', 'IMBABURA');
INSERT INTO zona(nombre, nombre_subzona) VALUES('ZONA 1', 'SUCUMBIOS');
INSERT INTO zona(nombre, nombre_subzona) VALUES('ZONA 2', 'NAPO');
INSERT INTO zona(nombre, nombre_subzona) VALUES('ZONA 2', 'ORELLANA');
INSERT INTO zona(nombre, nombre_subzona) VALUES('ZONA 2', 'PICHINCHA');
INSERT INTO zona(nombre, nombre_subzona) VALUES('ZONA 3', 'CHIMBORAZO');
INSERT INTO zona(nombre, nombre_subzona) VALUES('ZONA 3', 'COTOPAXI');
INSERT INTO zona(nombre, nombre_subzona) VALUES('ZONA 3', 'PASTAZA');
INSERT INTO zona(nombre, nombre_subzona) VALUES('ZONA 3', 'TUNGURAHUA');
INSERT INTO zona(nombre, nombre_subzona) VALUES('ZONA 4', 'MANABI');
INSERT INTO zona(nombre, nombre_subzona) VALUES('ZONA 4', 'SANTO DOMINGO DE LOS TSACHILAS');
INSERT INTO zona(nombre, nombre_subzona) VALUES('ZONA 5', 'BOLIVAR');
INSERT INTO zona(nombre, nombre_subzona) VALUES('ZONA 5', 'GALAPAGOS');
INSERT INTO zona(nombre, nombre_subzona) VALUES('ZONA 5', 'GUAYAS');
INSERT INTO zona(nombre, nombre_subzona) VALUES('ZONA 5', 'LOS RIOS');
INSERT INTO zona(nombre, nombre_subzona) VALUES('ZONA 5', 'SANTA ELENA');
INSERT INTO zona(nombre, nombre_subzona) VALUES('ZONA 6', 'AZUAY');
INSERT INTO zona(nombre, nombre_subzona) VALUES('ZONA 6', 'CAÑAR');
INSERT INTO zona(nombre, nombre_subzona) VALUES('ZONA 6', 'MORONA SANTIAGO');
INSERT INTO zona(nombre, nombre_subzona) VALUES('ZONA 7', 'EL ORO');
INSERT INTO zona(nombre, nombre_subzona) VALUES('ZONA 7', 'LOJA');
INSERT INTO zona(nombre, nombre_subzona) VALUES('ZONA 7', 'ZAMORA CHINCHIPE');
INSERT INTO zona(nombre, nombre_subzona) VALUES('ZONA 8', 'DMG');
INSERT INTO zona(nombre, nombre_subzona) VALUES('ZONA 9', 'DMQ');
