USE detenidos;

INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('0', 'EL ORO', '0', 'MAR TERRITORIAL');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('01', 'MAR TERRITORIAL', '0', 'MAR TERRITORIAL');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1001', 'IMBABURA', '10', 'IBARRA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1002', 'IMBABURA', '10', 'ANTONIO ANTE');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1003', 'IMBABURA', '10', 'COTACACHI');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1004', 'IMBABURA', '10', 'OTAVALO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1005', 'IMBABURA', '10', 'PIMAMPIRO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1006', 'IMBABURA', '10', 'SAN MIGUEL DE URCUQUI');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('101', 'AZUAY', '1', 'CUENCA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('102', 'AZUAY', '1', 'GIRON');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('103', 'AZUAY', '1', 'GUALACEO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('104', 'AZUAY', '1', 'NABON');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('105', 'AZUAY', '1', 'PAUTE');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('106', 'AZUAY', '1', 'PUCARA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('107', 'AZUAY', '1', 'SAN FERNANDO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('108', 'AZUAY', '1', 'SANTA ISABEL');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('109', 'AZUAY', '1', 'SIGSIG');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('110', 'AZUAY', '1', 'OÑA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1101', 'LOJA', '11', 'LOJA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1102', 'LOJA', '11', 'CALVAS');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1103', 'LOJA', '11', 'CATAMAYO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1104', 'LOJA', '11', 'CELICA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1105', 'LOJA', '11', 'CHAGUARPAMBA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1106', 'LOJA', '11', 'ESPINDOLA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1107', 'LOJA', '11', 'GONZANAMA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1108', 'LOJA', '11', 'MACARA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1109', 'LOJA', '11', 'PALTAS');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('111', 'AZUAY', '1', 'CHORDELEG');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1110', 'LOJA', '11', 'PUYANGO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1111', 'LOJA', '11', 'SARAGURO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1112', 'LOJA', '11', 'SOZORANGA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1113', 'LOJA', '11', 'ZAPOTILLO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1114', 'LOJA', '11', 'PINDAL');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1115', 'LOJA', '11', 'QUILANGA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1116', 'LOJA', '11', 'OLMEDO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('112', 'AZUAY', '1', 'EL PAN');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('113', 'AZUAY', '1', 'SEVILLA DE ORO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('114', 'AZUAY', '1', 'GUACHAPALA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('115', 'AZUAY', '1', 'CAMILO PONCE ENRIQUEZ');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1201', 'LOS RIOS', '12', 'BABAHOYO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1202', 'LOS RIOS', '12', 'BABA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1203', 'LOS RIOS', '12', 'MONTALVO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1204', 'LOS RIOS', '12', 'PUEBLOVIEJO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1205', 'LOS RIOS', '12', 'QUEVEDO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1206', 'LOS RIOS', '12', 'URDANETA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1207', 'LOS RIOS', '12', 'VENTANAS');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1208', 'LOS RIOS', '12', 'VINCES');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1209', 'LOS RIOS', '12', 'PALENQUE');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1210', 'LOS RIOS', '12', 'BUENA FE');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1211', 'LOS RIOS', '12', 'VALENCIA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1212', 'LOS RIOS', '12', 'MOCACHE');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1213', 'LOS RIOS', '12', 'QUINSALOMA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1301', 'MANABI', '13', 'PORTOVIEJO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1302', 'MANABI', '13', 'BOLIVAR');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1303', 'MANABI', '13', 'CHONE');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1304', 'MANABI', '13', 'EL CARMEN');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1305', 'MANABI', '13', 'FLAVIO ALFARO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1306', 'MANABI', '13', 'JIPIJAPA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1307', 'MANABI', '13', 'JUNIN');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1308', 'MANABI', '13', 'MANTA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1309', 'MANABI', '13', 'MONTECRISTI');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1310', 'MANABI', '13', 'PAJAN');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1311', 'MANABI', '13', 'PICHINCHA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1312', 'MANABI', '13', 'ROCAFUERTE');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1313', 'MANABI', '13', 'SANTA ANA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1314', 'MANABI', '13', 'SUCRE');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1315', 'MANABI', '13', 'TOSAGUA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1316', 'MANABI', '13', '24 DE MAYO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1317', 'MANABI', '13', 'PEDERNALES');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1318', 'MANABI', '13', 'OLMEDO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1319', 'MANABI', '13', 'PUERTO LOPEZ');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1320', 'MANABI', '13', 'JAMA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1321', 'MANABI', '13', 'JARAMIJO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1322', 'MANABI', '13', 'SAN VICENTE');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1401', 'MORONA SANTIAGO', '14', 'MORONA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1402', 'MORONA SANTIAGO', '14', 'GUALAQUIZA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1403', 'MORONA SANTIAGO', '14', 'LIMON INDANZA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1404', 'MORONA SANTIAGO', '14', 'PALORA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1405', 'MORONA SANTIAGO', '14', 'SANTIAGO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1406', 'MORONA SANTIAGO', '14', 'SUCUA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1407', 'MORONA SANTIAGO', '14', 'HUAMBOYA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1408', 'MORONA SANTIAGO', '14', 'SAN JUAN BOSCO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1409', 'MORONA SANTIAGO', '14', 'TAISHA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1410', 'MORONA SANTIAGO', '14', 'LOGROÑO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1411', 'MORONA SANTIAGO', '14', 'PABLO SEXTO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1412', 'MORONA SANTIAGO', '14', 'TIWINTZA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1501', 'NAPO', '15', 'TENA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1503', 'NAPO', '15', 'ARCHIDONA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1504', 'NAPO', '15', 'EL CHACO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1507', 'NAPO', '15', 'QUIJOS');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1509', 'NAPO', '15', 'CARLOS JULIO AROSEMENA TOLA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1601', 'PASTAZA', '16', 'PASTAZA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1602', 'PASTAZA', '16', 'MERA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1603', 'PASTAZA', '16', 'SANTA CLARA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1604', 'PASTAZA', '16', 'ARAJUNO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1701', 'DMQ', '17', 'QUITO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1702', 'PICHINCHA', '17', 'CAYAMBE');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1703', 'PICHINCHA', '17', 'MEJIA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1704', 'PICHINCHA', '17', 'PEDRO MONCAYO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1705', 'PICHINCHA', '17', 'RUMIÑAHUI');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1707', 'PICHINCHA', '17', 'SAN MIGUEL DE LOS BANCOS');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1708', 'PICHINCHA', '17', 'PEDRO VICENTE MALDONADO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1709', 'PICHINCHA', '17', 'PUERTO QUITO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1801', 'TUNGURAHUA', '18', 'AMBATO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1802', 'TUNGURAHUA', '18', 'BAÑOS DE AGUA SANTA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1803', 'TUNGURAHUA', '18', 'CEVALLOS');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1804', 'TUNGURAHUA', '18', 'MOCHA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1805', 'TUNGURAHUA', '18', 'PATATE');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1806', 'TUNGURAHUA', '18', 'QUERO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1807', 'TUNGURAHUA', '18', 'SAN PEDRO DE PELILEO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1808', 'TUNGURAHUA', '18', 'SANTIAGO DE PILLARO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1809', 'TUNGURAHUA', '18', 'TISALEO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1901', 'ZAMORA CHINCHIPE', '19', 'ZAMORA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1902', 'ZAMORA CHINCHIPE', '19', 'CHINCHIPE');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1903', 'ZAMORA CHINCHIPE', '19', 'NANGARITZA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1904', 'ZAMORA CHINCHIPE', '19', 'YACUAMBI');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1905', 'ZAMORA CHINCHIPE', '19', 'YANTZAZA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1906', 'ZAMORA CHINCHIPE', '19', 'EL PANGUI');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1907', 'ZAMORA CHINCHIPE', '19', 'CENTINELA DEL CONDOR');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1908', 'ZAMORA CHINCHIPE', '19', 'PALANDA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('1909', 'ZAMORA CHINCHIPE', '19', 'PAQUISHA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('2001', 'GALAPAGOS', '20', 'SAN CRISTOBAL');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('2002', 'GALAPAGOS', '20', 'ISABELA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('2003', 'GALAPAGOS', '20', 'SANTA CRUZ');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('201', 'BOLIVAR', '2', 'GUARANDA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('202', 'BOLIVAR', '2', 'CHILLANES');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('203', 'BOLIVAR', '2', 'CHIMBO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('204', 'BOLIVAR', '2', 'ECHEANDIA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('205', 'BOLIVAR', '2', 'SAN MIGUEL');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('206', 'BOLIVAR', '2', 'CALUMA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('207', 'BOLIVAR', '2', 'LAS NAVES');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('2101', 'SUCUMBIOS', '21', 'LAGO AGRIO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('2102', 'SUCUMBIOS', '21', 'GONZALO PIZARRO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('2103', 'SUCUMBIOS', '21', 'PUTUMAYO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('2104', 'SUCUMBIOS', '21', 'SHUSHUFINDI');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('2105', 'SUCUMBIOS', '21', 'SUCUMBIOS');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('2106', 'SUCUMBIOS', '21', 'CASCALES');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('2107', 'SUCUMBIOS', '21', 'CUYABENO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('2201', 'ORELLANA', '22', 'ORELLANA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('2202', 'ORELLANA', '22', 'AGUARICO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('2203', 'ORELLANA', '22', 'LA JOYA DE LOS SACHAS');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('2204', 'ORELLANA', '22', 'LORETO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('2301', 'SANTO DOMINGO DE LOS TSACHILAS', '23', 'SANTO DOMINGO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('2401', 'SANTA ELENA', '24', 'SANTA ELENA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('2402', 'SANTA ELENA', '24', 'LA LIBERTAD');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('2403', 'SANTA ELENA', '24', 'SALINAS');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('301', 'CAÑAR', '3', 'AZOGUES');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('302', 'CAÑAR', '3', 'BIBLIAN');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('303', 'CAÑAR', '3', 'CAÑAR');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('304', 'CAÑAR', '3', 'LA TRONCAL');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('305', 'CAÑAR', '3', 'EL TAMBO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('306', 'CAÑAR', '3', 'DELEG');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('307', 'CAÑAR', '3', 'SUSCAL');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('401', 'CARCHI', '4', 'TULCAN');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('402', 'CARCHI', '4', 'BOLIVAR');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('403', 'CARCHI', '4', 'ESPEJO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('404', 'CARCHI', '4', 'MIRA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('405', 'CARCHI', '4', 'MONTUFAR');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('406', 'CARCHI', '4', 'SAN PEDRO DE HUACA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('501', 'COTOPAXI', '5', 'LATACUNGA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('502', 'COTOPAXI', '5', 'LA MANA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('503', 'COTOPAXI', '5', 'PANGUA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('504', 'COTOPAXI', '5', 'PUJILI');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('505', 'COTOPAXI', '5', 'SALCEDO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('506', 'COTOPAXI', '5', 'SAQUISILI');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('507', 'COTOPAXI', '5', 'SIGCHOS');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('601', 'CHIMBORAZO', '6', 'RIOBAMBA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('602', 'CHIMBORAZO', '6', 'ALAUSI');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('603', 'CHIMBORAZO', '6', 'COLTA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('604', 'CHIMBORAZO', '6', 'CHAMBO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('605', 'CHIMBORAZO', '6', 'CHUNCHI');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('606', 'CHIMBORAZO', '6', 'GUAMOTE');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('607', 'CHIMBORAZO', '6', 'GUANO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('608', 'CHIMBORAZO', '6', 'PALLATANGA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('609', 'CHIMBORAZO', '6', 'PENIPE');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('610', 'CHIMBORAZO', '6', 'CUMANDA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('701', 'EL ORO', '7', 'MACHALA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('702', 'EL ORO', '7', 'ARENILLAS');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('703', 'EL ORO', '7', 'ATAHUALPA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('704', 'EL ORO', '7', 'BALSAS');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('705', 'EL ORO', '7', 'CHILLA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('706', 'EL ORO', '7', 'EL GUABO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('707', 'EL ORO', '7', 'HUAQUILLAS');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('708', 'EL ORO', '7', 'MARCABELI');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('709', 'EL ORO', '7', 'PASAJE');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('710', 'EL ORO', '7', 'PIÑAS');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('711', 'EL ORO', '7', 'PORTOVELO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('712', 'EL ORO', '7', 'SANTA ROSA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('713', 'EL ORO', '7', 'ZARUMA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('714', 'EL ORO', '7', 'LAS LAJAS');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('801', 'ESMERALDAS', '8', 'ESMERALDAS');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('802', 'ESMERALDAS', '8', 'ELOY ALFARO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('803', 'ESMERALDAS', '8', 'MUISNE');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('804', 'ESMERALDAS', '8', 'QUININDE');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('805', 'ESMERALDAS', '8', 'SAN LORENZO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('806', 'ESMERALDAS', '8', 'ATACAMES');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('807', 'ESMERALDAS', '8', 'RIOVERDE');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('808', 'SANTO DOMINGO DE LOS TSACHILAS', '23', 'LA CONCORDIA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('9004', 'CAÑAR', '90', 'EL PIEDRERO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('901', 'DMG', '9', 'GUAYAQUIL');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('902', 'GUAYAS', '9', 'ALFREDO BAQUERIZO MORENO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('903', 'GUAYAS', '9', 'BALAO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('904', 'GUAYAS', '9', 'BALZAR');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('905', 'GUAYAS', '9', 'COLIMES');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('906', 'GUAYAS', '9', 'DAULE');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('907', 'DMG', '9', 'DURAN');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('908', 'GUAYAS', '9', 'EMPALME');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('909', 'GUAYAS', '9', 'EL TRIUNFO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('910', 'GUAYAS', '9', 'MILAGRO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('911', 'GUAYAS', '9', 'NARANJAL');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('912', 'GUAYAS', '9', 'NARANJITO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('913', 'GUAYAS', '9', 'PALESTINA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('914', 'GUAYAS', '9', 'PEDRO CARBO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('916', 'DMG', '9', 'SAMBORONDON');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('918', 'GUAYAS', '9', 'SANTA LUCIA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('919', 'GUAYAS', '9', 'SALITRE');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('920', 'GUAYAS', '9', 'SAN JACINTO DE YAGUACHI');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('921', 'GUAYAS', '9', 'PLAYAS');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('922', 'GUAYAS', '9', 'SIMON BOLIVAR');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('923', 'GUAYAS', '9', 'CRNEL. MARCELINO MARIDUEÑA');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('924', 'GUAYAS', '9', 'LOMAS DE SARGENTILLO');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('925', 'GUAYAS', '9', 'NOBOL');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('927', 'GUAYAS', '9', 'GNRAL. ANTONIO ELIZALDE');
INSERT INTO Canton(codigo_canton, nombre_subzona, codigo_provincia, nombre_canton) VALUES('928', 'GUAYAS', '9', 'ISIDRO AYORA');
