USE detenidos;

INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('0', 'MAR TERRITORIAL', 'MAR TERRITORIAL');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('01D01', 'AZUAY', 'CUENCA NORTE');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('01D02', 'AZUAY', 'CUENCA SUR');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('01D03', 'AZUAY', 'GIRON');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('01D04', 'AZUAY', 'GUALACEO');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('01D05', 'AZUAY', 'NABON');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('01D06', 'AZUAY', 'PAUTE');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('01D07', 'AZUAY', 'PONCE ENRIQUEZ');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('01D08', 'AZUAY', 'SIGSIG');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('02D01', 'BOLIVAR', 'GUARANDA');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('02D02', 'BOLIVAR', 'CHILLANES');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('02D03', 'BOLIVAR', 'SAN MIGUEL');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('02D04', 'BOLIVAR', 'SUBTROPICO');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('03D01', 'CAÑAR', 'AZOGUES');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('03D02', 'CAÑAR', 'CAÑAR');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('03D03', 'CAÑAR', 'LA TRONCAL');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('04D01', 'CARCHI', 'TULCAN');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('04D02', 'CARCHI', 'MONTUFAR');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('04D03', 'CARCHI', 'ESPEJO');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('05D01', 'COTOPAXI', 'LATACUNGA');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('05D02', 'COTOPAXI', 'LA MANA');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('05D03', 'COTOPAXI', 'PANGUA');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('05D04', 'COTOPAXI', 'DANSANTE');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('05D05', 'COTOPAXI', 'SIGCHOS');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('05D06', 'COTOPAXI', 'SALCEDO');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('06D01', 'CHIMBORAZO', 'RIOBAMBA');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('06D02', 'CHIMBORAZO', 'ALAUSI');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('06D03', 'CHIMBORAZO', 'PALLATANGA');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('06D04', 'CHIMBORAZO', 'COLTA');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('06D05', 'CHIMBORAZO', 'GUANO');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('07D01', 'EL ORO', 'PASAJE');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('07D02', 'EL ORO', 'MACHALA');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('07D03', 'EL ORO', 'ZARUMA');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('07D04', 'EL ORO', 'PIÑAS');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('07D05', 'EL ORO', 'HUAQUILLAS');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('07D06', 'EL ORO', 'SANTA ROSA');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('08D01', 'ESMERALDAS', 'ESMERALDAS');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('08D02', 'ESMERALDAS', 'ELOY ALFARO');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('08D03', 'ESMERALDAS', 'ATACAMES');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('08D04', 'ESMERALDAS', 'QUININDE');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('08D05', 'ESMERALDAS', 'SAN LORENZO');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('08D06', 'ESMERALDAS', 'RIO VERDE');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('09D01', 'DMG', 'SUR');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('09D02', 'DMG', 'ESTEROS');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('09D03', 'DMG', '9 DE OCTUBRE');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('09D04', 'DMG', 'PORTETE');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('09D05', 'DMG', 'MODELO');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('09D06', 'DMG', 'FLORIDA');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('09D07', 'DMG', 'PASCUALES');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('09D08', 'DMG', 'NUEVA PROSPERINA');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('09D09', 'DMG', 'CEIBOS');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('09D10', 'DMG', 'PROGRESO');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('09D11', 'GUAYAS', 'JUJAN SIMON BOLIVAR');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('09D12', 'GUAYAS', 'NARANJAL BALAO');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('09D13', 'GUAYAS', 'BALZAR');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('09D14', 'GUAYAS', 'PEDRO CARBO');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('09D15', 'GUAYAS', 'EL EMPALME');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('09D16', 'GUAYAS', 'EL TRIUNFO BUCAY');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('09D17', 'GUAYAS', 'MILAGRO');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('09D18', 'GUAYAS', 'NARANJITO MARCELINO MARIDUEÑA');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('09D19', 'GUAYAS', 'DAULE');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('09D20', 'GUAYAS', 'SALITRE');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('09D21', 'GUAYAS', 'YAGUACHI');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('09D22', 'GUAYAS', 'PLAYAS');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('09D23', 'DMG', 'SAMBORONDON');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('09D24', 'DMG', 'DURAN');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('10D01', 'IMBABURA', 'CIUDAD BLANCA');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('10D02', 'IMBABURA', 'VALLE DEL AMANECER');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('10D03', 'IMBABURA', 'TIERRA DEL SOL');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('10D04', 'IMBABURA', 'LAS GOLONDRINAS');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('11D01', 'LOJA', 'LOJA');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('11D02', 'LOJA', 'CATAMAYO');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('11D03', 'LOJA', 'CATACOCHA');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('11D04', 'LOJA', 'SABANILLA');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('11D05', 'LOJA', 'ESPINDOLA');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('11D06', 'LOJA', 'CALVAS');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('11D07', 'LOJA', 'MACARA');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('11D08', 'LOJA', 'SARAGURO');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('11D09', 'LOJA', 'ZAPOTILLO');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('12D01', 'LOS RIOS', 'BABAHOYO');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('12D02', 'LOS RIOS', 'PUEBLOVIEJO');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('12D03', 'LOS RIOS', 'QUEVEDO');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('12D04', 'LOS RIOS', 'VENTANAS');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('12D05', 'LOS RIOS', 'VINCES');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('12D06', 'LOS RIOS', 'BUENA FE');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('13D01', 'MANABI', 'PORTOVIEJO');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('13D02', 'MANABI', 'MANTA');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('13D03', 'MANABI', 'JIPIJAPA');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('13D04', 'MANABI', '24 DE MAYO');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('13D05', 'MANABI', 'EL CARMEN');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('13D06', 'MANABI', 'BOLIVAR JUNIN');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('13D07', 'MANABI', 'CHONE');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('13D08', 'MANABI', 'PICHINCHA');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('13D09', 'MANABI', 'PAJAN');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('13D10', 'MANABI', 'PEDERNALES');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('13D11', 'MANABI', 'SUCRE');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('13D12', 'MANABI', 'ROCAFUERTE');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('14D01', 'MORONA SANTIAGO', 'MORONA');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('14D02', 'MORONA SANTIAGO', 'SANGAY');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('14D03', 'MORONA SANTIAGO', 'CENTRO SUR');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('14D04', 'MORONA SANTIAGO', 'SUR');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('14D05', 'MORONA SANTIAGO', 'TAISHA');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('14D06', 'MORONA SANTIAGO', 'MENDEZ');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('15D01', 'NAPO', 'TENA');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('15D02', 'NAPO', 'EL VALLE DE QUIJOS');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('16D01', 'PASTAZA', 'PASTAZA');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('16D02', 'PASTAZA', 'ARAJUNO');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('17D01', 'DMQ', 'NANEGAL');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('17D02', 'DMQ', 'CALDERON');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('17D03', 'DMQ', 'LA DELICIA');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('17D04', 'DMQ', 'MANUELA SAENZ');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('17D05', 'DMQ', 'EUGENIO ESPEJO');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('17D06', 'DMQ', 'ELOY ALFARO');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('17D07', 'DMQ', 'QUITUMBE');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('17D08', 'DMQ', 'LOS CHILLOS');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('17D09', 'DMQ', 'TUMBACO');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('17D10', 'PICHINCHA', 'CAYAMBE');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('17D11', 'PICHINCHA', 'RUMIÑAHUI - MEJIA');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('17D12', 'PICHINCHA', 'NOROCCIDENTE');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('18D01', 'TUNGURAHUA', 'AMBATO NORTE');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('18D02', 'TUNGURAHUA', 'AMBATO SUR');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('18D03', 'TUNGURAHUA', 'BAÑOS');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('18D04', 'TUNGURAHUA', 'PATATE');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('18D05', 'TUNGURAHUA', 'PILLARO');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('18D06', 'TUNGURAHUA', 'QUERO');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('19D01', 'ZAMORA CHINCHIPE', 'ZAMORA');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('19D02', 'ZAMORA CHINCHIPE', 'PAQUISHA');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('19D03', 'ZAMORA CHINCHIPE', 'CHINCHIPE');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('19D04', 'ZAMORA CHINCHIPE', 'YANTZAZA');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('20D01', 'GALAPAGOS', 'GALAPAGOS');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('21D01', 'SUCUMBIOS', 'SUCUMBIOS');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('21D02', 'SUCUMBIOS', 'LAGO AGRIO');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('21D03', 'SUCUMBIOS', 'PUTUMAYO');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('21D04', 'SUCUMBIOS', 'SHUSHUFINDI');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('22D01', 'ORELLANA', 'LA JOYA DE LOS SACHAS');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('22D02', 'ORELLANA', 'ORELLANA LORETO');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('22D03', 'ORELLANA', 'AGUARICO');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('23D01', 'SANTO DOMINGO DE LOS TSACHILAS', 'SANTO DOMINGO ESTE');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('23D02', 'SANTO DOMINGO DE LOS TSACHILAS', 'SANTO DOMINGO OESTE');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('23D03', 'SANTO DOMINGO DE LOS TSACHILAS', 'LA CONCORDIA');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('24D01', 'SANTA ELENA', 'SANTA ELENA');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('24D02', 'SANTA ELENA', 'LIBERTAD SALINAS');
INSERT INTO Distrito(codigo_distrito, nombre_subzona, nombre) VALUES('90D01', 'CAÑAR', 'EL PIEDRERO');
