USE detenidos;

INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('0', '0', 'MAR TERRITORIAL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('01', '1301', 'ALHAJUELA (BAJO GRANDE), CHIRIJOS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('02', '1504', 'OYACACHI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('03', '403', 'EL GOALTAL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('04', '605', 'CAPZOL, COMPUD, LLAGOS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('05', '713', 'ABANIN, GUANAZAN');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('06', '914', 'VALLE DE LA VIRGEN');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100150', '1001', 'SAN MIGUEL DE IBARRA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100151', '1001', 'AMBUQUI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100152', '1001', 'ANGOCHAGUA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100153', '1001', 'CAROLINA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100154', '1001', 'LA ESPERANZA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100155', '1001', 'LITA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100156', '1001', 'SALINAS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100157', '1001', 'SAN ANTONIO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100250', '1002', 'ATUNTAQUI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100251', '1002', 'IMBAYA (SAN LUIS DE COBUENDO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100252', '1002', 'SAN FCO. DE NATABUELA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100253', '1002', 'SAN JOSE DE CHALTURA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100254', '1002', 'SAN ROQUE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100350', '1003', 'COTACACHI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100351', '1003', 'APUELA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100352', '1003', 'GARCIA MORENO (LLURIMAGUA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100357', '1003', 'LAS GOLONDRINAS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100353', '1003', 'IMANTAG');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100355', '1003', 'PLAZA GUTIERREZ (CALVARIO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100356', '1003', 'QUIROGA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100450', '1004', 'OTAVALO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100451', '1004', 'DOCTOR MIGUEL EGAS CABEZAS (PEGUCHE)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100452', '1004', 'EUGENIO ESPEJO (CALPAQUI)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100453', '1004', 'GONZALEZ SUAREZ');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100455', '1004', 'SAN JOSE DE QUICHINCHE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100456', '1004', 'SAN JUAN DE ILUMAN');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100457', '1004', 'SAN PABLO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100458', '1004', 'SAN RAFAEL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100550', '1005', 'PIMAMPIRO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100551', '1005', 'CHUGA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100553', '1005', 'SAN  FCO. DE SIGSIPAMBA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100650', '1006', 'URCUQUI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100651', '1006', 'CAHUASQUI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100652', '1006', 'LA MERCED DE BUENOS AIRES');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100653', '1006', 'PABLO ARENAS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100654', '1006', 'SAN BLAS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('100655', '1006', 'TUMBABIRO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10150', '101', 'CUENCA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10151', '101', 'BAÑOS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10152', '101', 'CUMBE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10154', '101', 'CHECA (JIDCAY)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10155', '101', 'CHIQUINTAD');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10156', '101', 'LLACAO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10157', '101', 'MOLLETURO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10158', '101', 'NULTI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10159', '101', 'OCTAVIO CORDERO PALACIOS (STA. ROSA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10160', '101', 'PACCHA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10161', '101', 'QUINGEO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10162', '101', 'RICAURTE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10163', '101', 'SAN JOAQUIN');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10164', '101', 'SANTA ANA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10165', '101', 'SAYAUSI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10166', '101', 'SIDCAY');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10167', '101', 'SININCAY');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10168', '101', 'TARQUI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10169', '101', 'TURI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10170', '101', 'VALLE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10171', '101', 'VICTORIA DEL PORTETE (IRQUIS)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10250', '102', 'GIRON');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10251', '102', 'ASUNCION');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10350', '103', 'GUALACEO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10353', '103', 'JADAN');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10354', '103', 'MARIANO MORENO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10356', '103', 'REMIGIO CRESPO TORAL (GULAG)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10357', '103', 'SAN JUAN');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10358', '103', 'ZHIDMAD');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10359', '103', 'LUIS CORDERO VEGA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10360', '103', 'SIMON BOLIVAR (CAB. EN GAÑANZOL)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10450', '104', 'NABON');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10451', '104', 'COCHAPATA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10452', '104', 'EL PROGRESO (CAB. EN ZHOTA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10453', '104', 'LAS NIEVES (CHAYA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10550', '105', 'PAUTE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10553', '105', 'CHICAN (GUILLERMO ORTEGA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10554', '105', 'EL CABO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10556', '105', 'GUARAINAG');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10559', '105', 'SAN CRISTOBAL (CARLOS ORDOÑEZ LAZO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10561', '105', 'TOMEBAMBA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10562', '105', 'DUG DUG');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10650', '106', 'PUCARA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10652', '106', 'SAN RAFAEL DE SHARUG');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10750', '107', 'SAN FERNANDO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10751', '107', 'CHUMBLIN');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10850', '108', 'SANTA ISABEL (CHAGUARURCO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10851', '108', 'ABDON CALDERON (LA UNION)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10854', '108', 'SAN SALVADOR DE CAÑARIBAMBA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10950', '109', 'SIGSIG');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10951', '109', 'CUCHIL (CUTCHIL)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10952', '109', 'GIMA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10954', '109', 'LUDO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10955', '109', 'SAN BARTOLOME');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('10956', '109', 'SAN JOSE DE RARANGA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110150', '1101', 'LOJA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110151', '1101', 'CHANTACO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110152', '1101', 'CHUQUIRIBAMBA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110153', '1101', 'EL CISNE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110154', '1101', 'GUALEL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110156', '1101', 'MALACATOS (VALLADOLID)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110157', '1101', 'SAN LUCAS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110158', '1101', 'SAN PEDRO DE VILCABAMBA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110159', '1101', 'SANTIAGO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110160', '1101', 'TAQUIL (MIGUEL RIOFRIO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110161', '1101', 'VILCABAMBA (VICTORIA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110162', '1101', 'YANGANA (ARSENIO CASTILLO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110163', '1101', 'QUINARA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110250', '1102', 'CARIAMANGA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110251', '1102', 'COLAISACA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110252', '1102', 'EL LUCERO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110254', '1102', 'SANGUILLIN');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110350', '1103', 'CATAMAYO (LA TOMA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110351', '1103', 'EL TAMBO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110353', '1103', 'SAN PEDRO DE LA BENDITA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110354', '1103', 'ZAMBI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110450', '1104', 'CELICA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110451', '1104', 'CRUZPAMBA (CAB EN CARLOS BUSTAMANTE)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110455', '1104', 'POZUL (SAN JUAN DE POZUL)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110456', '1104', 'SABANILLA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('11050', '110', 'SAN FELIPE DE OÑA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('11051', '110', 'SUSUDEL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110550', '1105', 'CHAGUARPAMBA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110551', '1105', 'BUENAVISTA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110555', '1105', 'SANTA RUFINA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110554', '1105', 'AMARILLOS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110650', '1106', 'AMALUZA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110651', '1106', 'BELLAVISTA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110652', '1106', 'JIMBURA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110653', '1106', 'SANTA TERESITA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110750', '1107', 'GONZANAMA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110751', '1107', 'CHANGAIMINA (LA LIBERTAD)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110753', '1107', 'NAMBACOLA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110754', '1107', 'PURUNUMA (EGUIGUREN)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110756', '1107', 'SACAPALCA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110850', '1108', 'MACARA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110851', '1108', 'LARAMA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110852', '1108', 'LA VICTORIA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110853', '1108', 'SABIANGO (LA CAPILLA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110950', '1109', 'CATACOCHA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110952', '1109', 'GUACHANAMA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110954', '1109', 'LAURO GUERRERO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110956', '1109', 'ORIANGA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110958', '1109', 'CASANGA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('110959', '1109', 'YAMANA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('111050', '1110', 'ALAMOR');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('111054', '1110', 'MERCADILLO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('111055', '1110', 'VICENTINO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('111150', '1111', 'SARAGURO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('111151', '1111', 'EL PARAISO DE CELEN');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('111152', '1111', 'EL TABLON');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('111153', '1111', 'LLUZHAPA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('111154', '1111', 'MANU');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('111155', '1111', 'SAN ANTONIO DE QUMBE (CUMBE)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('111156', '1111', 'SAN PABLO DE TENTA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('111157', '1111', 'SAN SEBASTIAN DE YULUC');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('111159', '1111', 'URDANETA (PAQUISHAPA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('111160', '1111', 'SUMAYPAMBA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('111250', '1112', 'SOZORANGA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('111252', '1112', 'TACAMOROS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('111350', '1113', 'ZAPOTILLO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('111352', '1113', 'GARZAREAL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('111354', '1113', 'PALETILLAS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('111450', '1114', 'PINDAL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('111452', '1114', '12 DE DICIEMBRE (CAB. EN ACHIOTES)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('111453', '1114', 'MILAGROS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('11150', '111', 'CHORDELEG');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('11151', '111', 'PRINCIPAL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('11152', '111', 'LA UNION');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('111550', '1115', 'QUILANGA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('111552', '1115', 'SAN ANTONIO DE LAS ARADAS (CAB. EN LAS ARADAS)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('111650', '1116', 'OLMEDO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('111651', '1116', 'LA TINGUE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('11250', '112', 'EL PAN');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('11350', '113', 'SEVILLA DE ORO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('11351', '113', 'AMALUZA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('11450', '114', 'GUACHAPALA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('11550', '115', 'CAMILO PONCE ENRIQUEZ');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('11551', '115', 'EL CARMEN DE PIJILI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('120150', '1201', 'BABAHOYO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('120152', '1201', 'CARACOL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('120153', '1201', 'FEBRES CORDERO (LAS JUNTAS)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('120154', '1201', 'PIMOCHA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('120155', '1201', 'LA UNION');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('120250', '1202', 'BABA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('120251', '1202', 'GUARE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('120252', '1202', 'ISLA DE BEJUCAL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('120350', '1203', 'MONTALVO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('120351', '1203', 'LA ESMERALDA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('120450', '1204', 'PUEBLOVIEJO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('120451', '1204', 'PUERTO PECHICHE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('120452', '1204', 'SAN JUAN');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('120550', '1205', 'QUEVEDO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('120553', '1205', 'SAN CARLOS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('120555', '1205', 'LA ESPERANZA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('120650', '1206', 'CATARAMA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('120651', '1206', 'RICAURTE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('120750', '1207', 'VENTANAS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('120752', '1207', 'ZAPOTAL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('120753', '1207', 'CHACARITA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('120754', '1207', 'LOS ANGELES');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('120850', '1208', 'VINCES');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('120851', '1208', 'ANTONIO SOTOMAYOR (CAB. EN PLAYAS DE VINCES)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('120950', '1209', 'PALENQUE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('121050', '1210', 'SAN JACINTO DE BUENA FE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('121051', '1210', 'PATRICIA PILAR');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('121150', '1211', 'VALENCIA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('121250', '1212', 'MOCACHE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('121350', '1213', 'QUINSALOMA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130150', '1301', 'PORTOVIEJO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130151', '1301', 'ABDON CALDERON (SAN FRANCISCO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130152', '1301', 'ALHAJUELA (BAJO GRANDE)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130153', '1301', 'CRUCITA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130154', '1301', 'PUEBLO NUEVO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130155', '1301', 'RIOCHICO (RIO CHICO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130156', '1301', 'SAN PLACIDO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130157', '1301', 'CHIRIJOS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130250', '1302', 'CALCETA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130251', '1302', 'MEMBRILLO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130252', '1302', 'QUIROGA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130350', '1303', 'CHONE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130351', '1303', 'BOYACA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130352', '1303', 'CANUTO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130353', '1303', 'CONVENTO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130354', '1303', 'CHIBUNGA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130355', '1303', 'ELOY ALFARO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130356', '1303', 'RICAURTE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130357', '1303', 'SAN ANTONIO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130450', '1304', 'EL CARMEN');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130453', '1304', 'MANGA DEL CURA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130451', '1304', 'WILFRIDO LOOR MOREIRA (MAICITO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130452', '1304', 'SAN PEDRO DE SUMA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130550', '1305', 'FLAVIO ALFARO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130551', '1305', 'SAN FRANCISCO DE NOVILLO (CAB. EN NOVILLO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130552', '1305', 'ZAPALLO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130650', '1306', 'JIPIJAPA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130651', '1306', 'AMERICA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130652', '1306', 'EL ANEGADO (CAB. EN ELOY ALFARO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130653', '1306', 'JULCUY');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130654', '1306', 'LA UNION');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130657', '1306', 'PEDRO PABLO GOMEZ');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130658', '1306', 'PUERTO DE CAYO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130750', '1307', 'JUNIN');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130850', '1308', 'MANTA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130851', '1308', 'SAN LORENZO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130950', '1309', 'MONTECRISTI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('130952', '1309', 'LA PILA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('131050', '1310', 'PAJAN');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('131051', '1310', 'CAMPOZANO (LA PALMA DE PAJAN)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('131052', '1310', 'CASCOL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('131053', '1310', 'GUALE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('131054', '1310', 'LASCANO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('131150', '1311', 'PICHINCHA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('131151', '1311', 'BARRAGANETE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('131152', '1311', 'SAN SEBASTIAN');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('131250', '1312', 'ROCAFUERTE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('131350', '1313', 'SANTA ANA DE VUELTA LARGA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('131351', '1313', 'AYACUCHO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('131352', '1313', 'HONORATO VASQUEZ (CAB EN VASQUEZ)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('131355', '1313', 'SAN PABLO (CAB EN PUEBLO NUEVO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('131450', '1314', 'BAHIA DE CARAQUEZ');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('131453', '1314', 'CHARAPOTO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('131457', '1314', 'SAN ISIDRO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('131550', '1315', 'TOSAGUA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('131551', '1315', 'BACHILLERO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('131552', '1315', 'ANGEL PEDRO GILER (LA ESTANCILLA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('131650', '1316', 'SUCRE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('131651', '1316', 'BELLAVISTA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('131652', '1316', 'NOBOA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('131653', '1316', 'ARQ. SIXTO DURAN BALLEN');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('131750', '1317', 'PEDERNALES');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('131751', '1317', 'COJIMIES');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('131752', '1317', '10 DE AGOSTO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('131753', '1317', 'ATAHUALPA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('131850', '1318', 'OLMEDO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('131950', '1319', 'PUERTO LOPEZ');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('131951', '1319', 'MACHALILLA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('131952', '1319', 'SALANGO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('132050', '1320', 'JAMA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('132150', '1321', 'JARAMIJO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('132250', '1322', 'SAN VICENTE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('132251', '1322', 'CANOA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140150', '1401', 'MACAS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140153', '1401', 'GENERAL PROAÑO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140156', '1401', 'SAN ISIDRO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140157', '1401', 'SEVILLA DON BOSCO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140158', '1401', 'SINAI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140160', '1401', 'ZUÑA (ZUÑAC)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140162', '1401', 'CUCHAENTZA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140164', '1401', 'RIO BLANCO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140250', '1402', 'GUALAQUIZA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140251', '1402', 'AMAZONAS (ROSARIO DE CUYES)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140253', '1402', 'BOMBOIZA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140254', '1402', 'CHIGUINDA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140255', '1402', 'EL ROSARIO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140256', '1402', 'NUEVA TARQUI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140258', '1402', 'EL IDEAL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140350', '1403', 'GRAL. LEONIDAS PLAZA GUTIERREZ');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140353', '1403', 'SAN ANTONIO (CAB EN SAN ANTONIO CENTRO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140357', '1403', 'STA SUSANA DE CHIVIAZA (CAB EN CHIVIAZA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140358', '1403', 'YUNGANZA (CAB EN EL ROSARIO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140450', '1404', 'PALORA (METZERA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140451', '1404', 'ARAPICOS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140452', '1404', 'CUMANDA (CAB EN COLONIA AGRICOLA SEVILLA DEL ORO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140454', '1404', 'SANGAY (CAB EN NAYAMANACA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140455', '1404', '16 DE AGOSTO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140550', '1405', 'SANTIAGO DE MENDEZ');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140552', '1405', 'CHUPIANZA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140553', '1405', 'PATUCA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140554', '1405', 'SAN LUIS DE EL ACHO (CAB EN EL ACHO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140556', '1405', 'TAYUZA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140557', '1405', 'SAN FRANCISCO DE CHINIMBIMI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140650', '1406', 'SUCUA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140651', '1406', 'ASUNCION');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140652', '1406', 'HUAMBI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140655', '1406', 'SANTA MARIANITA DE JESUS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140750', '1407', 'HUAMBOYA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140751', '1407', 'CHIGUAZA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140850', '1408', 'SAN JUAN BOSCO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140852', '1408', 'SAN CARLOS DE LIMON');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140854', '1408', 'SAN CARLOS DE LIMON, SANTIAGO DE PANANZA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140950', '1409', 'TAISHA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('140952', '1409', 'MACUMA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('141050', '1410', 'LOGROÑO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('141052', '1410', 'SHIMPIS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('141150', '1411', 'PABLO SEXTO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('141250', '1412', 'SANTIAGO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('141251', '1412', 'SAN JOSE DE MORONA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('150150', '1501', 'TENA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('150151', '1501', 'AHUANO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('150153', '1501', 'CHONTAPUNTA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('150154', '1501', 'PANO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('150155', '1501', 'PUERTO MISAHUALLI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('150156', '1501', 'PUERTO NAPO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('150157', '1501', 'TALAG');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('150158', '1501', 'SAN JUAN DE MUYUNA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('150350', '1503', 'ARCHIDONA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('150352', '1503', 'COTUNDO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('150354', '1503', 'SAN PABLO DE USHPAYACU');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('150356', '1503', 'HATUN SUMAKU');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('150450', '1504', 'EL CHACO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('150451', '1504', 'GONZALO DIAZ DE PINEDA (EL BOMBON)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('150452', '1504', 'LINARES');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('150454', '1504', 'SANTA ROSA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('150455', '1504', 'SARDINAS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('150750', '1507', 'BAEZA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('150751', '1507', 'COSANGA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('150752', '1507', 'CUYUJA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('150753', '1507', 'PAPALLACTA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('150754', '1507', 'SAN FRANCISCO DE BORJA (VIRGILIO DAVILA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('150756', '1507', 'SUMACO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('150950', '1509', 'CARLOS JULIO AROSEMENA TOLA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('160150', '1601', 'PUYO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('160152', '1601', 'CANELOS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('160154', '1601', 'DIEZ DE AGOSTO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('160155', '1601', 'FATIMA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('160156', '1601', 'MONTALVO (ANDOAS)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('160159', '1601', 'RIO TIGRE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('160161', '1601', 'SARAYACU');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('160162', '1601', 'SIMON BOLIVAR (CAB. EN MUSHULLACTA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('160163', '1601', 'TARQUI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('160164', '1601', 'TENIENTE HUGO ORTIZ');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('160165', '1601', 'VERACRUZ (INDILLAMA) (CAB. EN INDILLAMA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('160166', '1601', 'EL TRIUNFO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('160250', '1602', 'MERA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('160251', '1602', 'MADRE TIERRA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('160252', '1602', 'SHELL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('160350', '1603', 'SANTA CLARA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('160351', '1603', 'SAN JOSE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('160450', '1604', 'ARAJUNO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('160451', '1604', 'CURARAY');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170150', '1701', 'QUITO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170151', '1701', 'ALANGASI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170152', '1701', 'AMAGUAÑA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170154', '1701', 'CALACALI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170155', '1701', 'CALDERON (CARAPUNGO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170156', '1701', 'CONOCOTO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170157', '1701', 'CUMBAYA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170158', '1701', 'CHAVEZPAMBA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170159', '1701', 'CHECA (CHILPA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170160', '1701', 'EL QUINCHE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170161', '1701', 'GUALEA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170162', '1701', 'GUANGOPOLO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170163', '1701', 'GUAYLLABAMBA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170164', '1701', 'LA MERCED');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170165', '1701', 'LLANO CHICO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170166', '1701', 'LLOA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170168', '1701', 'NANEGAL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170169', '1701', 'NANEGALITO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170170', '1701', 'NAYON');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170171', '1701', 'NONO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170172', '1701', 'PACTO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170174', '1701', 'PERUCHO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170175', '1701', 'PIFO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170176', '1701', 'PINTAG');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170177', '1701', 'POMASQUI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170178', '1701', 'PUELLARO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170179', '1701', 'PUEMBO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170180', '1701', 'SAN ANTONIO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170181', '1701', 'SAN JOSE DE MINAS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170183', '1701', 'TABABELA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170184', '1701', 'TUMBACO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170185', '1701', 'YARUQUI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170186', '1701', 'ZAMBIZA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170250', '1702', 'CAYAMBE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170251', '1702', 'ASCAZUBI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170252', '1702', 'CANGAHUA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170253', '1702', 'OLMEDO (PESILLO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170254', '1702', 'OTON');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170255', '1702', 'SANTA ROSA DE CUZUBAMBA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170256', '1702', 'SAN JOSE DE AYORA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170350', '1703', 'MACHACHI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170351', '1703', 'ALOAG');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170352', '1703', 'ALOASI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170353', '1703', 'CUTUGLAHUA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170354', '1703', 'EL CHAUPI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170355', '1703', 'MANUEL CORNEJO ASTORGA (TANDAPI)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170356', '1703', 'TAMBILLO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170357', '1703', 'UYUMBICHO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170450', '1704', 'TABACUNDO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170451', '1704', 'LA ESPERANZA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170452', '1704', 'MALCHINGUI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170453', '1704', 'TOCACHI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170454', '1704', 'TUPIGACHI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170550', '1705', 'SANGOLQUI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170551', '1705', 'COTOGCHOA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170552', '1705', 'RUMIPAMBA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170750', '1707', 'SAN MIGUEL DE LOS BANCOS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170751', '1707', 'MINDO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170850', '1708', 'PEDRO VICENTE MALDONADO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('170950', '1709', 'PUERTO QUITO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180150', '1801', 'AMBATO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180151', '1801', 'AMBATILLO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180152', '1801', 'ATAHUALPA (CHISALATA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180153', '1801', 'AUGUSTO N. MARTINEZ (MUNDUGLEO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180154', '1801', 'CONSTANTINO FERNANDEZ (CAB. EN CULLITAHUA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180155', '1801', 'HUACHI GRANDE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180156', '1801', 'IZAMBA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180157', '1801', 'JUAN BENIGNO VELA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180158', '1801', 'MONTALVO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180159', '1801', 'PASA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180160', '1801', 'PICAIGUA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180161', '1801', 'PILAGUIN (PILAHUIN)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180162', '1801', 'QUISAPINCHA (QUIZAPINCHA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180163', '1801', 'SAN BARTOLOME DE PINLLOG');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180165', '1801', 'SANTA ROSA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180166', '1801', 'TOTORAS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180167', '1801', 'CUNCHIBAMBA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180168', '1801', 'UNAMUNCHO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180250', '1802', 'BAÑOS DE AGUA SANTA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180252', '1802', 'RIO NEGRO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180253', '1802', 'RIO VERDE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180254', '1802', 'ULBA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180350', '1803', 'CEVALLOS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180450', '1804', 'MOCHA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180451', '1804', 'PINGUILI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180550', '1805', 'PATATE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180551', '1805', 'EL TRIUNFO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180553', '1805', 'SUCRE (CAB. EN SUCRE-PATATE URCU)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180650', '1806', 'QUERO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180651', '1806', 'RUMIPAMBA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180652', '1806', 'YANAYACU - MOCHAPATA (CAB. EN YANAYACU)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180750', '1807', 'PELILEO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180751', '1807', 'BENITEZ (PACHANLICA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180752', '1807', 'BOLIVAR');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180753', '1807', 'COTALO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180754', '1807', 'CHIQUICHA (CAB. EN CHIQUICHA GRANDE)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180755', '1807', 'EL ROSARIO (RUMICHACA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180756', '1807', 'GARCIA MORENO (CHUMAQUI)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180757', '1807', 'GUAMBALO (HUAMBALO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180758', '1807', 'SALASACA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180850', '1808', 'PILLARO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180852', '1808', 'EMILIO MARIA TERAN (RUMIPAMBA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180853', '1808', 'MARCOS ESPINEL (CHACATA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180854', '1808', 'PRESIDENTE URBINA (CHAGRAPAMBA -PATZUCUL)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180855', '1808', 'SAN ANDRES');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180856', '1808', 'SAN JOSE DE POALO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180857', '1808', 'SAN MIGUELITO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180950', '1809', 'TISALEO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('180951', '1809', 'QUINCHICOTO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('190150', '1901', 'ZAMORA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('190151', '1901', 'CUMBARATZA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('190152', '1901', 'GUADALUPE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('190155', '1901', 'SABANILLA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('190156', '1901', 'TIMBARA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('190158', '1901', 'SAN CARLOS DE LAS MINAS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('190250', '1902', 'ZUMBA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('190251', '1902', 'CHITO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('190254', '1902', 'LA CHONTA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('190256', '1902', 'PUCAPAMBA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('190350', '1903', 'GUAYZIMI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('190351', '1903', 'ZURMI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('190352', '1903', 'NUEVO PARAISO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('190450', '1904', '28 DE MAYO (SAN JOSE DE YACUAMBI)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('190451', '1904', 'LA PAZ');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('190550', '1905', 'YANTZAZA (YANZATZA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('190551', '1905', 'CHICAÑA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('190553', '1905', 'LOS ENCUENTROS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('190650', '1906', 'EL PANGUI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('190651', '1906', 'EL GUISME');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('190652', '1906', 'PACHICUTZA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('190653', '1906', 'TUNDAYME');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('190750', '1907', 'ZUMBI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('190752', '1907', 'TRIUNFO-DORADO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('190753', '1907', 'PANGUINTZA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('190850', '1908', 'PALANDA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('190852', '1908', 'SAN FRANCISCO DEL VERGEL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('190853', '1908', 'VALLADOLID');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('190854', '1908', 'LA CANELA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('190950', '1909', 'PAQUISHA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('190951', '1909', 'BELLAVISTA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('190952', '1909', 'NUEVO QUITO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('200150', '2001', 'PUERTO BAQUERIZO MORENO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('200151', '2001', 'EL PROGRESO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('200250', '2002', 'PUERTO VILLAMIL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('200251', '2002', 'TOMAS DE BERLANGA (SANTO TOMAS)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('200350', '2003', 'PUERTO AYORA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('200351', '2003', 'BELLAVISTA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('200352', '2003', 'SANTA ROSA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('20150', '201', 'GUARANDA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('20151', '201', 'FACUNDO VELA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('20153', '201', 'JULIO E. MORENO (CATANAHUAN GRANDE)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('20155', '201', 'SALINAS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('20156', '201', 'SAN LORENZO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('20157', '201', 'SAN SIMON (YACOTO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('20158', '201', 'SANTA FE (SANTA FE)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('20159', '201', 'SIMIATUG');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('20160', '201', 'SAN LUIS DE PAMBIL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('20250', '202', 'CHILLANES');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('20251', '202', 'SAN JOSE DEL TAMBO (TAMBOPAMBA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('20350', '203', 'SAN JOSE DE CHIMBO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('20351', '203', 'ASUNCION (ASANCOTO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('20353', '203', 'MAGDALENA (CHAPACOTO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('20354', '203', 'SAN SEBASTIAN');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('20355', '203', 'TELIMBELA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('20450', '204', 'ECHEANDIA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('20550', '205', 'SAN MIGUEL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('20551', '205', 'BALSAPAMBA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('20552', '205', 'BILOVAN');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('20553', '205', 'REGULO DE MORA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('20554', '205', 'SAN PABLO (SAN PABLO DE ATENAS)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('20555', '205', 'SANTIAGO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('20650', '206', 'CALUMA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('20750', '207', 'LAS NAVES');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('210150', '2101', 'NUEVA LOJA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('210152', '2101', 'DURENO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('210153', '2101', 'GENERAL FARFAN');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('210155', '2101', 'EL ENO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('210156', '2101', 'PACAYACU');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('210157', '2101', 'JAMBELI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('210158', '2101', 'SANTA CECILIA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('210160', '2101', '10 DE AGOSTO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('210250', '2102', 'LUMBAQUI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('210251', '2102', 'EL REVENTADOR');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('210252', '2102', 'GONZALO PIZARRO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('210350', '2103', 'PUERTO EL CARMEN DEL PUTUMAYO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('210351', '2103', 'PALMA ROJA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('210352', '2103', 'PUERTO BOLIVAR (PUERTO MONTUFAR)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('210450', '2104', 'SHUSHUFINDI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('210451', '2104', 'LIMONCOCHA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('210452', '2104', 'PAÑACOCHA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('210453', '2104', 'SAN ROQUE (CAB. EN SAN VICENTE)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('210454', '2104', 'SAN PEDRO DE LOS COFANES');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('210455', '2104', 'SIETE DE JULIO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('210550', '2105', 'LA BONITA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('210554', '2105', 'SANTA BARBARA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('210650', '2106', 'EL DORADO DE CASCALES');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('210651', '2106', 'SANTA ROSA DE SUCUMBIOS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('210652', '2106', 'SEVILLA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('210750', '2107', 'TARAPOA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('210752', '2107', 'AGUAS NEGRAS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('220150', '2201', 'PUERTO FRANCISCO DE ORELLANA (EL COCA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('220151', '2201', 'DAYUMA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('220152', '2201', 'TARACOA (NUEVA ESPERANZA: YUCA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('220153', '2201', 'ALEJANDRO LABAKA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('220154', '2201', 'EL DORADO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('220156', '2201', 'GARCIA MORENO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('220157', '2201', 'INES ARANGO (CAB. EN WESTERN)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('220158', '2201', 'LA BELLEZA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('220159', '2201', 'NUEVO PARAISO (CAB. EN UNION )');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('220160', '2201', 'SAN JOSE DE GUAYUSA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('220161', '2201', 'SAN LUIS DE ARMENIA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('220250', '2202', 'NUEVO ROCAFUERTE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('220252', '2202', 'CONONACO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('220254', '2202', 'TIPUTINI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('220350', '2203', 'LA JOYA DE LOS SACHAS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('220351', '2203', 'ENOKANQUI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('220352', '2203', 'POMPEYA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('220353', '2203', 'SAN CARLOS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('220354', '2203', 'SAN SEBASTIAN DEL COCA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('220355', '2203', 'LAGO SAN PEDRO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('220356', '2203', 'RUMIPAMBA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('220357', '2203', 'TRES DE NOVIEMBRE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('220358', '2203', 'UNION MILAGREÑA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('220450', '2204', 'LORETO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('220451', '2204', 'AVILA (CAB. EN HUIRUNO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('220452', '2204', 'PUERTO MURIALDO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('220453', '2204', 'SAN JOSE DE PAYAMINO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('220454', '2204', 'SAN JOSE DE DAHUANO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('220455', '2204', 'SAN VICENTE DE HUATICOCHA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('230150', '2301', 'SANTO DOMINGO DE LOS COLORADOS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('230151', '2301', 'ALLURIQUIN');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('230152', '2301', 'PUERTO LIMON');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('230153', '2301', 'LUZ DE AMERICA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('230154', '2301', 'SAN JACINTO DEL BUA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('230155', '2301', 'VALLE HERMOSO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('230156', '2301', 'EL ESFUERZO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('230157', '2301', 'SANTA MARIA DEL TOACHI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('240150', '2401', 'SANTA ELENA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('240151', '2401', 'ATAHUALPA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('240152', '2401', 'COLONCHE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('240153', '2401', 'CHANDUY');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('240154', '2401', 'MANGLARALTO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('240156', '2401', 'SAN JOSE DE ANCON');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('240250', '2402', 'LA LIBERTAD');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('240350', '2403', 'SALINAS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('240351', '2403', 'ANCONCITO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('240352', '2403', 'JOSE LUIS TAMAYO (MUEY)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('30150', '301', 'AZOGUES');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('30151', '301', 'COJITAMBO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('30153', '301', 'GUAPAN');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('30154', '301', 'JAVIER LOYOLA (CHUQUIPATA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('30155', '301', 'LUIS CORDERO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('30158', '301', 'SAN MIGUEL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('30160', '301', 'TADAY');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('30250', '302', 'BIBLIAN');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('30251', '302', 'NAZON (CAB. EN PAMPA DE DOMINGUEZ)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('30252', '302', 'SAN FRANCISCO DE SAGEO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('30253', '302', 'TURUPAMBA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('30254', '302', 'JERUSALEN');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('30350', '303', 'CAÑAR');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('30352', '303', 'CHOROCOPTE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('30353', '303', 'GENERAL MORALES (SOCARTE)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('30354', '303', 'GUALLETURO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('30355', '303', 'HONORATO VASQUEZ (TAMBO VIEJO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('30356', '303', 'INGAPIRCA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('30357', '303', 'JUNCAL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('30358', '303', 'SAN ANTONIO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('30361', '303', 'ZHUD');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('30363', '303', 'DUCUR');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('30450', '304', 'LA TRONCAL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('30451', '304', 'MANUEL J. CALLE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('30452', '304', 'PANCHO NEGRO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('30550', '305', 'EL TAMBO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('30650', '306', 'DELEG');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('30651', '306', 'SOLANO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('30750', '307', 'SUSCAL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('40150', '401', 'TULCAN');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('40151', '401', 'EL CARMELO (EL PUN)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('40153', '401', 'JULIO ANDRADE (OREJUELA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('40156', '401', 'TOBAR DONOSO (LA BOCANA DE CAMUMBI)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('40157', '401', 'TUFIÑO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('40158', '401', 'URBINA (TAYA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('40159', '401', 'EL CHICAL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('40161', '401', 'SANTA MARTHA DE CUBA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('40250', '402', 'BOLIVAR');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('40251', '402', 'GARCIA MORENO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('40252', '402', 'LOS ANDES');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('40253', '402', 'MONTE OLIVO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('40255', '402', 'SAN RAFAEL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('40350', '403', 'EL ANGEL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('40352', '403', 'LA LIBERTAD (ALIZO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('40353', '403', 'SAN ISIDRO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('40450', '404', 'MIRA (CHONTAHUASI)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('40451', '404', 'CONCEPCION');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('40452', '404', 'JIJON Y CAAMAÑO (CAB. EN RIO BLANCO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('40453', '404', 'JUAN MONTALVO (SAN IGNACIO DE QUIL)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('40550', '405', 'SAN GABRIEL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('40551', '405', 'CRISTOBAL COLON');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('40552', '405', 'CHITAN DE NAVARRETE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('40553', '405', 'FERNANDEZ SALVADOR');
-- INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('40554', '1904', 'LA PAZ');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('40554', '405', 'LA PAZ');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('40650', '406', 'HUACA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('40651', '406', 'MARISCAL SUCRE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50150', '501', 'LATACUNGA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50151', '501', 'ALAQUES (ALAQUEZ)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50152', '501', 'BELISARIO QUEVEDO (GUANAILIN)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50153', '501', 'GUAITACAMA (GUAYTACAMA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50154', '501', 'JOSEGUANGO BAJO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50156', '501', 'MULALO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50157', '501', '11 DE NOVIEMBRE (ILINCHISI)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50158', '501', 'POALO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50159', '501', 'SAN JUAN DE PASTOCALLE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50161', '501', 'TANICUCHI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50162', '501', 'TOACASO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50250', '502', 'LA MANA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50251', '502', 'GUASAGANDA (CAB. EN GUASAGANDA CENTRO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50252', '502', 'PUCAYACU');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50350', '503', 'EL CORAZON');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50351', '503', 'MORASPUNGO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50352', '503', 'PINLLOPATA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50450', '504', 'PUJILI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50455', '504', 'LA VICTORIA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50456', '504', 'PILALO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50457', '504', 'TINGO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50458', '504', 'ZUMBAHUA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50550', '505', 'SAN MIGUEL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50551', '505', 'ANTONIO JOSE HOLGUIN (SANTA LUCIA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50552', '505', 'CUSUBAMBA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50553', '505', 'MULALILLO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50554', '505', 'MULLIQUINDIL (SANTA ANA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50555', '505', 'PANSALEO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50650', '506', 'SAQUISILI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50651', '506', 'CANCHAGUA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50652', '506', 'CHANTILIN');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50653', '506', 'COCHAPAMBA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50750', '507', 'SIGCHOS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50751', '507', 'CHUGCHILLAN');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('50752', '507', 'ISINLIVI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60150', '601', 'RIOBAMBA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60152', '601', 'CALPI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60153', '601', 'CUBIJIES');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60155', '601', 'LICAN');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60156', '601', 'LICTO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60157', '601', 'PUNGALA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60158', '601', 'PUNIN');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60159', '601', 'QUIMIAG');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60160', '601', 'SAN JUAN');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60161', '601', 'SAN LUIS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60162', '601', 'CACHA (CAB. EN MACHANGARA), SAN LUIS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60250', '602', 'ALAUSI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60251', '602', 'ACHUPALLAS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60253', '602', 'GUASUNTOS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60254', '602', 'HUIGRA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60255', '602', 'MULTITUD');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60258', '602', 'SEVILLA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60259', '602', 'SIBAMBE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60350', '603', 'VILLA LA UNION (CAJABAMBA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60352', '603', 'COLUMBE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60353', '603', 'JUAN DE VELASCO (PANGOR)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60354', '603', 'SANTIAGO DE QUITO (CAB. EN SAN ANTONIO DE QUITO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60450', '604', 'CHAMBO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60550', '605', 'CHUNCHI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60552', '605', 'COMPUD');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60554', '605', 'LLAGOS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60650', '606', 'GUAMOTE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60651', '606', 'CEBADAS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60652', '606', 'PALMIRA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60750', '607', 'GUANO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60751', '607', 'GUANANDO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60752', '607', 'ILAPO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60753', '607', 'LA PROVIDENCIA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60754', '607', 'SAN ANDRES');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60755', '607', 'SAN GERARDO DE PACAICAGUAN');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60756', '607', 'SAN ISIDRO DE PATULU');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60758', '607', 'SANTA FE DE GALAN');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60850', '608', 'PALLATANGA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60950', '609', 'PENIPE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60952', '609', 'MATUS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('60954', '609', 'SAN ANTONIO DE BAYUSHIG');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('61050', '610', 'CUMANDA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('70150', '701', 'MACHALA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('70152', '701', 'EL RETIRO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('70250', '702', 'ARENILLAS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('70251', '702', 'CHACRAS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('70254', '702', 'PALMALES');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('70255', '702', 'CARCABON');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('70350', '703', 'PACCHA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('70351', '703', 'AYAPAMBA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('70352', '703', 'CORDONCILLO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('70353', '703', 'MILAGRO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('70355', '703', 'SAN JUAN DE CERRO AZUL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('70450', '704', 'BALSAS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('70451', '704', 'BELLAMARIA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('70550', '705', 'CHILLA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('70650', '706', 'EL GUABO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('70651', '706', 'BARBONES (SUCRE)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('70652', '706', 'LA IBERIA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('70653', '706', 'TENDALES (CAB. EN PUERTO TENDALES)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('70654', '706', 'RIO BONITO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('70750', '707', 'HUAQUILLAS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('70850', '708', 'MARCABELI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('70851', '708', 'EL INGENIO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('70950', '709', 'PASAJE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('70951', '709', 'BUENAVISTA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('70952', '709', 'CASACAY');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('70953', '709', 'LA PEAÑA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('70954', '709', 'PROGRESO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('70955', '709', 'UZHCURRUMI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('70956', '709', 'CAÑAQUEMADA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('71050', '710', 'PIÑAS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('71052', '710', 'LA BOCANA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('71054', '710', 'PIEDRAS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('71055', '710', 'SAN ROQUE (AMBROSIO MALDONADO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('71056', '710', 'SARACAY');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('71150', '711', 'PORTOVELO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('71151', '711', 'CURTINCAPA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('71152', '711', 'MORALES');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('71250', '712', 'SANTA ROSA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('71251', '712', 'BELLAVISTA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('71252', '712', 'JAMBELI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('71253', '712', 'LA AVANZADA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('71254', '712', 'SAN ANTONIO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('71255', '712', 'TORATA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('71256', '712', 'VICTORIA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('71257', '712', 'BELLAMARIA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('71350', '713', 'ZARUMA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('71352', '713', 'ARCAPAMBA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('71353', '713', 'GUANAZAN');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('71354', '713', 'GUIZHAGUIÑA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('71355', '713', 'HUERTAS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('71356', '713', 'MALVAS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('71357', '713', 'MULUNCAY GRANDE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('71358', '713', 'SINSAO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('71450', '714', 'LA VICTORIA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('71452', '714', 'EL PARAISO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('71453', '714', 'SAN ISIDRO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80150', '801', 'ESMERALDAS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80152', '801', 'CAMARONES (CAB. EN SAN VICENTE)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80154', '801', 'CHINCA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80159', '801', 'MAJUA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80163', '801', 'SAN MATEO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80165', '801', 'TABIAZO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80166', '801', 'TACHINA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80168', '801', 'VUELTA LARGA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80250', '802', 'VALDEZ (LIMONES)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80253', '802', 'BORBON');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80254', '802', 'LA TOLA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80255', '802', 'LUIS VARGAS TORRES (CAB. EN PLAYA DE ORO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80256', '802', 'MALDONADO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80257', '802', 'PAMPANAL DE BOLIVAR');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80258', '802', 'SAN FRANCISCO DE ONZOLE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80259', '802', 'SANTO DOMINGO DE ONZOLE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80260', '802', 'SELVA ALEGRE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80261', '802', 'TELEMBI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80262', '802', 'COLON ELOY DEL MARIA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80265', '802', 'SANTA LUCIA DE LAS PEÑAS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80350', '803', 'MUISNE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80352', '803', 'DAULE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80354', '803', 'QUINGUE (OLMEDO PERDOMO FRANCO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80355', '803', 'SALIMA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80356', '803', 'SAN FRANCISCO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80357', '803', 'SAN GREGORIO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80358', '803', 'SAN JOSE DE CHAMANGA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80450', '804', 'ROSA ZARATE (QUININDE)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80451', '804', 'CUBE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80452', '804', 'CHURA (CHANCAMA) (CAB. EN EL YERBERO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80453', '804', 'MALIMPIA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80454', '804', 'VICHE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80455', '804', 'LA UNION');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80550', '805', 'SAN LORENZO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80551', '805', 'ALTO TAMBO (CAB EN GUADUAL)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80552', '805', 'ANCON (PICHANGAL) (CAB. EN PALMA REAL)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80553', '805', 'CALDERON');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80554', '805', 'CARONDELET');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80556', '805', 'CONCEPCION');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80557', '805', 'MATAJE (CAB. EN SANTANDER)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80559', '805', 'SANTA RITA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80560', '805', 'TAMBILLO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80561', '805', 'TULULBI (CAB. EN RICAURTE)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80562', '805', 'URBINA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80650', '806', 'ATACAMES');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80651', '806', 'LA UNION');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80652', '806', 'SUA (CAB. EN LA BOCANA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80653', '806', 'TONCHIGUE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80654', '806', 'TONSUPA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80750', '807', 'RIOVERDE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80751', '807', 'CHONTADURO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80752', '807', 'CHUMUNDE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80753', '807', 'LAGARTO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80754', '807', 'MONTALVO (CAB EN HORQUETA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80755', '807', 'ROCAFUERTE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80850', '808', 'LA CONCORDIA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80851', '808', 'MONTERREY');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80852', '808', 'LA VILLEGAS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('80853', '808', 'PLAN PILOTO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('900451', '9004', 'EL PIEDRERO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('90150', '901', 'GUAYAQUIL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('90152', '901', 'JUAN GOMEZ RENDON (PROGRESO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('90153', '901', 'MORRO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('90156', '901', 'POSORJA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('90157', '901', 'PUNA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('90158', '901', 'TENGUEL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('90250', '902', 'ALFREDO BAQUERIZO MORENO (JUJAN)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('90350', '903', 'BALAO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('90450', '904', 'BALZAR');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('90550', '905', 'COLIMES');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('90551', '905', 'SAN JACINTO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('90650', '906', 'DAULE');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('90652', '906', 'JUAN BAUTISTA AGUIRRE (LOS TINTOS)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('90653', '906', 'LAUREL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('90654', '906', 'LIMONAL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('90656', '906', 'LOS LOJAS (ENRIQUE BAQUERIZO MORENO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('90750', '907', 'ELOY ALFARO (DURAN)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('90850', '908', 'VELASCO IBARRA (CAB. EL EMPALME)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('90851', '908', 'GUAYAS (PUEBLO NUEVO)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('90852', '908', 'EL ROSARIO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('90950', '909', 'EL TRIUNFO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('91050', '910', 'MILAGRO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('91051', '910', 'CHOBO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('91053', '910', 'MARISCAL SUCRE (HUAQUES)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('91054', '910', 'ROBERTO ASTUDILLO (CAB. EN CRUCE DE VENECIA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('91150', '911', 'NARANJAL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('91151', '911', 'JESUS MARIA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('91152', '911', 'SAN CARLOS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('91153', '911', 'SANTA ROSA DE FLANDES');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('91154', '911', 'TAURA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('91250', '912', 'NARANJITO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('91350', '913', 'PALESTINA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('91450', '914', 'PEDRO CARBO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('91451', '914', 'VALLE DE LA VIRGEN');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('91452', '914', 'SABANILLA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('91650', '916', 'SAMBORONDON');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('91651', '916', 'TARIFA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('91850', '918', 'SANTA LUCIA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('91950', '919', 'EL SALITRE (LAS RAMAS)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('91951', '919', 'GRAL. VERNAZA (DOS ESTEROS)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('91952', '919', 'LA VICTORIA (ÑAUZA)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('91953', '919', 'JUNQUILLAL');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('92050', '920', 'SAN JACINTO DE YAGUACHI');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('92053', '920', 'GRAL. PEDRO J. MONTERO (BOLICHE)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('92055', '920', 'YAGUACHI VIEJO (CONE)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('92056', '920', 'VIRGEN DE FATIMA');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('92150', '921', 'GENERAL VILLAMIL (PLAYAS)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('92250', '922', 'SIMON BOLIVAR');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('92251', '922', 'CRNEL. LORENZO DE GARAICOA (PEDREGAL)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('92350', '923', 'CORONEL MARCELINO MARIDUEÑA (SAN CARLOS)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('92450', '924', 'LOMAS DE SARGENTILLO');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('92550', '925', 'NARCISA DE JESUS');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('92750', '927', 'GRAL. ANTONIO ELIZALDE (BUCAY)');
INSERT INTO Parroquia(codigo_parroquia, codigo_canton, nombre) VALUES('92850', '928', 'ISIDRO AYORA');
